### ISSUE TITLE
about swish activation in regressor and classify

### ISSUE THREAD

**Issue by westnight** [zylo117/Yet-Another-EfficientDet-Pytorch#10]
I see you add swish act in regressor and classify, have you campare this with @signatrix version, because he just follow the retinanet's way.

**Comment by zylo117** [comment]
Sorry, I didn't quite get what you said.

I did replace relu with swish. But swish performs almost like relu.

The real problem is the missing BN, I add separate not shared BNs after every separableconv2d just like the official efficientdet did. I think it matters more than swish activation.
