### ISSUE TITLE
why input_sizes have two 1280?

### ISSUE THREAD

**Issue by chunleiml** [zylo117/Yet-Another-EfficientDet-Pytorch#100]
![image](https://user-images.githubusercontent.com/29543941/79412430-1201e900-7fd8-11ea-9c52-8539cb6daf1b.png)

**Comment by zylo117** [comment]
please read the paper first

**Comment by AbyssGaze** [comment]
![image](https://user-images.githubusercontent.com/14217667/79438373-075e4880-8006-11ea-9862-f894d0b782ef.png)

**Comment by chunleiml** [comment]
I don't understand why the author didn't further expand the input size on D6, for example D6=1536, D7=1920？ @AbyssGaze @zylo117

**Comment by AbyssGaze** [comment]
I'm also confused according to the formulation of :
![image](https://user-images.githubusercontent.com/14217667/79450149-1994b280-8017-11ea-88db-dc11b2011c8d.png)
![image](https://user-images.githubusercontent.com/14217667/79450154-1c8fa300-8017-11ea-86fe-87158f0d9957.png)
the value of input size and channels not equal to the table.

**Comment by zylo117** [comment]
that's why I hard-coded the parameters.
