### ISSUE TITLE
Not able to load checkpoint after pressing ctrl+c

### ISSUE THREAD

**Issue by Cli98** [zylo117/Yet-Another-EfficientDet-Pytorch#101]
Not able to load checkpoint after pressing ctrl+c

@zylo117 Do you think if this is expected?

Traceback (most recent call last):
  File "coco_eval.py", line 151, in <module>
    model.load_state_dict(torch.load(weights_path, map_location=torch.device('cpu')))
  File "/home/sumanta/.pyenv/versions/anaconda3-5.3.0/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sumanta/.pyenv/versions/anaconda3-5.3.0/lib/python3.7/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 8 more bytes. The file might be corrupted.

**Comment by zylo117** [comment]
The file might be corrupted. It could be you pressed ctrl+c twice by accidence, killed the program before it saved the checkpoint

**Comment by Cli98** [comment]
I see.

**Comment by Cli98** [comment]
I try to press only once. The program is not able to stop properly. No checkpoint saved. I wait for 5 minutes. Normally it only needs few seconds to store a checkpoint.

**Comment by zylo117** [comment]
with num_worker > 0, it may not be able to stop properly, but the checkpoint should be saved.
ASAIK, different shell could have different behaviors. What's yours? Mine is bash.

If it doesn't help, you can set `--save_interval 50`, the program will checkpoint every 50 steps.

**Comment by Cli98** [comment]
Currently I set the value for --save_interval as 1000, as I do not want to save too much ckpts. I'm good at current setting. I'm using linux terminal. It's better if the behavior you described can achieve. But it should be fine if not. I set num_workers as 12.
