### ISSUE TITLE
How did you find Pi in BiFPN is two different tensor?

### ISSUE THREAD

**Issue by GlacierMelt** [zylo117/Yet-Another-EfficientDet-Pytorch#105]
I haven’t found about it is two different tensors in tensorflow version. Thanks

**Comment by zylo117** [comment]
sorry, already forgotten. it's very tricky because there are lots of condition judgements in tf effdet.

the best way to do this is to debug the model building line by line right after extracting the features of effnet.

**Comment by GlacierMelt** [comment]
That's all right. Thank you for your answer .
