### ISSUE TITLE
数据集格式

### ISSUE THREAD

**Issue by gtgtgt1117** [zylo117/Yet-Another-EfficientDet-Pytorch#107]
@zylo117 您好,请问用自己的数据集训练的时候png.jpeg,jpg格式的图片都可以吗?

**Comment by zylo117** [comment]
for these three formats, yes

**Comment by gtgtgt1117** [comment]
> for these three formats, yes



谢谢您即使回答我,可是我用我的数据集训练的时候显存占满了,GPU利用率却很低.我想是我的数据格式有问题.您方便给我说一下数据格式吗?我转成coco的格式可能有点问题.thank you

**Comment by wxupjack** [comment]
> > for these three formats, yes
> 
> 谢谢您即使回答我,可是我用我的数据集训练的时候显存占满了,GPU利用率却很低.我想是我的数据格式有问题.您方便给我说一下数据格式吗?我转成coco的格式可能有点问题.thank you

Check your **num_worker,** it seems to be an I / O bottleneck. Most of the time may be wasted on loading images.
