### ISSUE TITLE
anchor scales！

### ISSUE THREAD

**Issue by yulei1234** [zylo117/Yet-Another-EfficientDet-Pytorch#108]
Sorry, I encountered a bottleneck，I have a simple question， how can I decompose into the regular two sets of numbers after clustering to get the anchor width and height of my dataset and their aspect ratio，sorry i've never done it before，thank you
![image](https://user-images.githubusercontent.com/37969091/79425852-e5a89580-7ff4-11ea-9041-6977726d4f59.png)

**Comment by Cli98** [comment]
@yulei1234 In case of your need to compute anchors in this repo, please have a look 
https://github.com/Cli98/anchor_computation_tool
