### ISSUE TITLE
How to compute the channels of P2?

### ISSUE THREAD

**Issue by AbyssGaze** [zylo117/Yet-Another-EfficientDet-Pytorch#110]
Thanks for your code. You have set the channels of P3,P4,P5, but need P2 channels for detecting small object.thanks.
```     
 conv_channel_coef = {
            # the channels of P3/P4/P5.
            0: [40, 112, 320],
            1: [40, 112, 320],
            2: [48, 120, 352],
            3: [48, 136, 384],
            4: [56, 160, 448],
            5: [64, 176, 512],
            6: [72, 200, 576],
            7: [72, 200, 576],
        }
```

**Comment by zylo117** [comment]
if so, BiFPN needs to to modified too. it's a lot of work. And the pretained weights is gone, then the performance will be worse.

i suggest you change the Resizer of dataset, so that you can feed larger image to the network, like 1024 for D0.

**Comment by ChrisHaooooooo** [comment]
@zylo117 The meaning of setting the Resizer of d0 larger, in my opinion ,is that we can enlarge the small object so that the detection of small object can be easier,is that right?

**Comment by zylo117** [comment]
yes

**Comment by AbyssGaze** [comment]
I have changed the resolution of D0 to 1024, but the performance is bad.(the elements is **electric eye**, that is why I try P2 for detecting small object).
![image](https://user-images.githubusercontent.com/14217667/79530183-37a6f500-80a1-11ea-841e-4e516f8a1525.png)
and evaluation of efficientdet-d0 for **coco** datasets : 
![image](https://user-images.githubusercontent.com/14217667/79530273-7b016380-80a1-11ea-9df4-d631aec458ce.png)
is also bad for small objects.
Thanks for your solution.

**Comment by zylo117** [comment]
> I have changed the resolution of D0 to 1024, but the performance is bad.(the elements is **electric eye**, that is why I try P2 for detecting small object).
> ![image](https://user-images.githubusercontent.com/14217667/79530183-37a6f500-80a1-11ea-841e-4e516f8a1525.png)
> and evaluation of efficientdet-d0 for **coco** datasets :
> ![image](https://user-images.githubusercontent.com/14217667/79530273-7b016380-80a1-11ea-9df4-d631aec458ce.png)
> is also bad for small objects.
> Thanks for your solution.

It's complicated to explain, can you try running the tutorial but change the resolution to 1024?
If it works, then it is likely that your training method is not appropriate
