### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by Ataraxiaaa** [zylo117/Yet-Another-EfficientDet-Pytorch#112]
我仿照coco_eval.py写了一个demo，输入工程中test/img.png这张图，模型为d0，效果图如下。感觉跟您test/img_inferred_d0_this_repo.jpg这张检测结果还是有些差距，换了最大模型d7效果也没提升多少。猜想可能是代码问题，想请问您的demo是如何实现的。

**Comment by Ataraxiaaa** [comment]
![image_screenshot_16 04 2020](https://user-images.githubusercontent.com/36878231/79442527-3dea9200-800b-11ea-91ff-78fa1cca11da.png)

**Comment by Ataraxiaaa** [comment]
阈值都是coco_eval.py中的默认值。

**Comment by zylo117** [comment]
raise confidence threshold to 0.2

**Comment by zylo117** [comment]
threshold in coco eval is dealt with inside cocoapi, so you don't need to manually set one. But this is testing, you need a normal threshold.

**Comment by Ataraxiaaa** [comment]
其实其他阈值我也试过了，问题还是score普遍比你图中要低。阈值设为0.2的话，漏检就很多了。

**Comment by lovepan1** [comment]
i meet the same phenomenon

**Comment by zylo117** [comment]
It's not right to set such low threshold, there will be lots of false positive boxes.

**Comment by Ataraxiaaa** [comment]
可以看哈您的demo怎么写的吗
