### ISSUE TITLE
Is there a bug in coco_eval.py and efficientdet_test.py?

### ISSUE THREAD

**Issue by wizardk** [zylo117/Yet-Another-EfficientDet-Pytorch#113]
@zylo117 
In the efficientdet/dataset.py, the input image is RGB order.In the coco_eval.py and efficientdet_test.py, the input image is BGR order.

**Comment by zylo117** [comment]
It's RGB. So is the image input.

**Comment by wizardk** [comment]
@zylo117 Sorry to ask again, in the preprocess function of utils/utils.py, I didn't find where you convert the BGR to RGB after imread.

**Comment by zylo117** [comment]
here `[:,:,::-1]`

**Comment by wizardk** [comment]
Thanks for your kindly help!
