### ISSUE TITLE
请教一下，跑d7出现 cuda out of memory，换d6,d5也还是一样

### ISSUE THREAD

**Issue by alphaev9** [zylo117/Yet-Another-EfficientDet-Pytorch#116]
NVIDIA Quadro M4000的卡，8G显存，nvidia-smi -l 看了显存占用，一开始跑模型，差不多7G就没了，这个应该怎么解决？谢谢！

**Comment by zheng-2019** [comment]
> NVIDIA Quadro M4000的卡，8G显存，nvidia-smi -l 看了显存占用，一开始跑模型，差不多7G就没了，这个应该怎么解决？谢谢！

减小batchsize 不行吗？

**Comment by alphaev9** [comment]
@zheng-2019 batchsize减到1还是不行

**Comment by mad-fogs** [comment]
according to my training logs, d4 consumes about 22GB  memory with batch_size=3 per GPU.

**Comment by alphaev9** [comment]
@mad-fogs 那就没得玩了，我跑跑更小的模型吧

**Comment by mad-fogs** [comment]
> @mad-fogs 那就没得玩了，我跑跑更小的模型吧

Hi you may try apex for mixed-precision training, i guess that will work.
and i am working on it currently.

**Comment by zylo117** [comment]
downvote for apex here.
1. apex doesn't improve speed at small batchsize.
2. f16 consumes only 10 to 20% less than f32.
3. applying apex is painful, but you're welcome to try.

**Comment by zylo117** [comment]
d7 takes about 4g, so in training, it takes 12g. 8g is totally hopeless.

**Comment by alphaev9** [comment]
换d0跑了



> > @mad-fogs 那就没得玩了，我跑跑更小的模型吧
> 
> Hi you may try apex for mixed-precision training, i guess that will work.
> and i am working on it currently.
