### ISSUE TITLE
Is the mAP Evaluation result right?

### ISSUE THREAD

**Issue by horse007666** [zylo117/Yet-Another-EfficientDet-Pytorch#119]
I'm looking at the mAP result.
 I find that in your mAP evaluation code coco_eval.py  threshold=0.05 and NMS_threshold=0.5,
 but in efficientdet_test.py the threshold=0.2 and NMS_threshold=0.2,
which you use to get your speed test result.
So tell me which threshold and NMS_threshold value should we use?

When I use 0.05, 0.5 to detect the image for test, the result seems a mess.
![image](https://user-images.githubusercontent.com/22372664/79527835-1e02af00-809b-11ea-9e7b-af0a8cb6fb04.png)

But If I use 0.5,0.5 for threshold and NMS threshold, the mAP can not reach the same result:
![image](https://user-images.githubusercontent.com/22372664/79527774-03303a80-809b-11ea-95a5-6bdb4ff0f162.png)

So which threshold and NMS_threshold value should we use? Is the mAP Evaluation result right?

**Comment by zylo117** [comment]
you should not specify confidence threshold in coco_eval, the cocoapi will deal with it itself.

however, nms threshold can be changed, but 0.5 seems to be a better choice. you can tune it if you like, of course

**Comment by wangerxiao001** [comment]
The same problem of confidence threshold!
We have 3 threshold for object detection. They are confidence threshold before NMS, NMS threshold and the IOU threshold. And I check your code the confidence threshhold is set to 0.05 as follows:
![image](https://user-images.githubusercontent.com/26485642/87539263-27b6a580-c6d0-11ea-9f51-a8ce9194c99f.png)
![image](https://user-images.githubusercontent.com/26485642/87539733-04402a80-c6d1-11ea-9519-22357f4f1642.png)

And as I know, the coco api just deal with iou threshold for calculating the AP and other metrics. Some other model like [YOLO v4 in pytorch](https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/73fa024cc8dbd292dae642f643f58ac6818103ad/tool/yolo_layer.py#L266), they choose different confidence threshold. Was that means that cocoapi doesn't deal with the confidence threshold but only iou threshold? And some other code [faster rcnn](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/7ce9c9e6241609ed9475ee207d7bd8d02278c2ff/model/faster_rcnn.py#L154) choose different confidence threshold for bboxes visualization and inference. It really confuses me, looking forward to you detailed answer!

**Comment by wangerxiao001** [comment]
> Yes cocoapi don't care about the confidence. Confidence threshold 0.05 just seems to be a better choice. You can try some other thresholds, like 0.5, but you should find out the smaller threshold is, the better mAP will be. Probably because filtering out the low confidence boxes will miss some targets. But setting it lower than 0.05 will cause lots of boxes that leads to OOM.
> Using a lower confidence threshold means possibly higher FP rate, yes, but also higher TP rate. And in practice, TP rate is a little bit higher as the threshold goes down, at least it's true for this model.

OK, thanks for your detailed answer!
