### ISSUE TITLE
训练了好几个模型，在评估时得到的结果都一样

### ISSUE THREAD

**Issue by sanli0** [zylo117/Yet-Another-EfficientDet-Pytorch#124]
我分别用自己的数据训练了d0，d1，d2，然后进行评估得到的结果一模一样，这是那里出了问题么？

**Comment by sanli0** [comment]
![捕获](https://user-images.githubusercontent.com/41035501/79542453-40f28a80-80be-11ea-8eec-343974448813.PNG)

**Comment by Cli98** [comment]
You issue looks similar with mine #125

**Comment by Cli98** [comment]
Hi @sanli0 , I think your situation is similar as mine. Please check my issue to see if the solution for mine can help yours. Good luck!

**Comment by sanli0** [comment]
@Cli98 谢谢你，我刚才看了你的问题咱俩的解决方案一样，非常感谢！我将关闭这个问题
