### ISSUE TITLE
Reload multiple checkpoint, get same score

### ISSUE THREAD

**Issue by Cli98** [zylo117/Yet-Another-EfficientDet-Pytorch#125]
Hi author @zylo117 

I use two days to train efficientdet and reloaded checkpoints. However, the evaluation score(AP) is exactly the same!

Check those captures,

<img width="656" alt="image" src="https://user-images.githubusercontent.com/19630616/79542629-fa6b4480-8059-11ea-9ca4-553d056b1ef2.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/19630616/79542659-06ef9d00-805a-11ea-907e-38b37fc255e7.png">

<img width="648" alt="image" src="https://user-images.githubusercontent.com/19630616/79542692-0fe06e80-805a-11ea-8735-548d67be75ca.png">

How could this be possible? No pause during my training and the training process looks okay.

Here is a capture of training.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/19630616/79542763-36060e80-805a-11ea-8196-64145141cb7b.png">

Here is the tensorboard loss,
<img width="655" alt="image" src="https://user-images.githubusercontent.com/19630616/79542926-87ae9900-805a-11ea-94d0-2a212ba636c6.png">

Is that possible for you to double check? I have no idea why this happens

**Comment by Cli98** [comment]
Is this has anything to do with the sync_bn you fixed yesterday? I keep up with your latest code til April 14th.

**Comment by lockeregg** [comment]
You need to remove the val2017_bbox_results.json before running the eval

**Comment by Cli98** [comment]
> You need to remove the val2017_bbox_results.json before running the eval

val2017_bbox_results.json should be the output of evaluation but not an input requirement right? how could this affect evaluation result?

**Comment by Cli98** [comment]
Alright looks like @lockeregg  is correct, although I'm not quite understand why lol. Thank you @lockeregg . Still appreciate if you can indicate why or show me the line of code for this setup.

**Comment by lockeregg** [comment]
> > You need to remove the val2017_bbox_results.json before running the eval
> 
> val2017_bbox_results.json should be the output of evaluation but not an input requirement right? how could this affect evaluation result?

Because the coco_eval.py will check if the val2017_bbox_results.json exists. 
If the file exists it will evaluate the of the output in the file.

**Comment by Cli98** [comment]
> > > You need to remove the val2017_bbox_results.json before running the eval
> > 
> > 
> > val2017_bbox_results.json should be the output of evaluation but not an input requirement right? how could this affect evaluation result?
> 
> Because the coco_eval.py will check if the val2017_bbox_results.json exists.
> If the file exists it will evaluate the of the output in the file.

I see. That's not a requirement but makes sense. Thank you.
