### ISSUE TITLE
the eval json have so many bbox 

### ISSUE THREAD

**Issue by cendelian** [zylo117/Yet-Another-EfficientDet-Pytorch#128]
hi, I train my person data success. and use eval.py to test ,the map is 80%
but i found one issue.

for eaxmple. 2012_00079.jpg have three people. ant i use efficient-test.py to test it.
three people are all can frame. good job!

but if i use eval.py to calculate map and generate josn.
I found 2012_00079 have so many bbox but not just three.

what issue is it?
could you help me

**Comment by zylo117** [comment]
congratulations!

the eval program will collect every possible objects and filter within the cocoapi, so you don't need to worried about that.
