### ISSUE TITLE
The result of test image is diffierent from yours.

### ISSUE THREAD

**Issue by geoffzhang** [zylo117/Yet-Another-EfficientDet-Pytorch#132]
I used the efficientdet-d0.pth and ran efficientdet_test.py. Why? please.

![img_inferred_d0_this_repo_0](https://user-images.githubusercontent.com/35004134/79630706-2be12e80-8186-11ea-9c54-bd9bdfe88729.jpg)

**Comment by zylo117** [comment]
set `force_input_size=1920`

**Comment by geoffzhang** [comment]
@zylo117 thanks, i got the same result.
