### ISSUE TITLE
small objects

### ISSUE THREAD

**Issue by tdn670000** [zylo117/Yet-Another-EfficientDet-Pytorch#134]
My trained model don't predict small car plate numbers
in the training dataset there are both big and small plates

Please tell me please, what can i do?
I think, maybe change anchors? I don't understand well, what anchors are
![12596060 jpg_0](https://user-images.githubusercontent.com/31201238/79639537-20493400-8195-11ea-8ac7-ccbc95dbbe4f.jpg)

**Comment by zylo117** [comment]
try changing this in project.yml

from
`anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'`
to
`anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (2.8, 0.7)]'`

**Comment by jinfagang** [comment]
I also got tiny targets doesn't recognized. Ratio really covers small objects situation? How to make it detection very small objects?

**Comment by zylo117** [comment]
Try using larger image input size, like 1024 for d0. That's what I did on the demo image.
