### ISSUE TITLE
Is there anybody who could run this repo on video instead of image?

### ISSUE THREAD

**Issue by MustafaUysal160207077** [zylo117/Yet-Another-EfficientDet-Pytorch#135]
Hi,
I've been trying to run this repo on video. But I couldn't 
`ori_imgs, framed_imgs, framed_metas = preprocess(img_path, max_size=input_size)`
I cant change this line for video. Is there Is there anybody who could run this repo on video? If he or she shares `efficientdet_test.py` codes, I will be appreciated.

**Comment by winter2897** [comment]
[webcamtest.txt](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/files/4498322/webcamtest.txt)

**Comment by MustafaUysal160207077** [comment]
> [webcamtest.txt](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/files/4498322/webcamtest.txt)

Thank you very much. I see this error:
```
    x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3,
1, 2)
RuntimeError: number of dims don't match in permute
```
Also, I don't use CUDA so I've set 
`use_cuda = False`

**Comment by MustafaUysal160207077** [comment]
I see some error but thanks a lot

**Comment by MustafaUysal160207077** [comment]
> [webcamtest.txt](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/files/4498322/webcamtest.txt)

Could you also share preprocess_video method?

**Comment by winter2897** [comment]
You add it at line 75 in ultis.py:

def preprocess_video(*frame_from_video, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
    ori_imgs = frame_from_video
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
    imgs_meta = [aspectaware_resize_padding(img[..., ::-1], max_size, max_size,
                                            means=None) for img in normalized_imgs]
    framed_imgs = [img_meta[0] for img_meta in imgs_meta]
    framed_metas = [img_meta[1:] for img_meta in imgs_meta]

    return ori_imgs, framed_imgs, framed_metas

**Comment by MustafaUysal160207077** [comment]
> You add it at line 75 in ultis.py:
> '''
> def preprocess_video(*frame_from_video, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
> ori_imgs = frame_from_video
> normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
> imgs_meta = [aspectaware_resize_padding(img[..., ::-1], max_size, max_size,
> means=None) for img in normalized_imgs]
> framed_imgs = [img_meta[0] for img_meta in imgs_meta]
> framed_metas = [img_meta[1:] for img_meta in imgs_meta]
> 
> ```
> return ori_imgs, framed_imgs, framed_metas
> ```
> 
> '''


Thanks a lot!
