### ISSUE TITLE
can i run this code without GPU?

### ISSUE THREAD

**Issue by Aiz-wallenstein** [zylo117/Yet-Another-EfficientDet-Pytorch#141]
Can I run this code without GPU? When I  run train.py , there are some problems without GPU. So I want to know it is necessary or not?

**Comment by zylo117** [comment]
Yes, you can set `use_cuda=False` to run effdet for testing, set `num_gpus=0` in project.yml to train with cpu, set `--cuda False` to eval with cpu.

But it will be super slow.

I recommend you get yourself a gpu or run the code on colab, kaggle, etc

**Comment by Aiz-wallenstein** [comment]
thanks for your advise

**Comment by jingmouren** [comment]
when I change to set
use_cuda = False
use_float16 = True
cudnn.fastest = False
cudnn.benchmark = False
for testing, following error happens
RuntimeError: "unfolded2d_copy" not implemented for 'Half'

**Comment by deepseek** [comment]
@jingmouren 
use_float16 = False

**Comment by zylo117** [comment]
@jingmouren most of the ops doesn't support float16 on cpu
