### ISSUE TITLE
error while following tutorial instructions

### ISSUE THREAD

**Issue by Zheweiqiu** [zylo117/Yet-Another-EfficientDet-Pytorch#147]
Got the following error when I tried to execute command line in tutorial step by step and I have not idea how to fix that. Any help will be appreciate!

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_74396_2983595444>

**Comment by eduardohem** [comment]
The last version of pytorch for don't work well for me,
try torch==1.4.0

**Comment by Zheweiqiu** [comment]
> The last version of pytorch for don't work well for me,
> try torch==1.4.0

I am using torch==1.4.0 and torchvision == 0.5.0

**Comment by zylo117** [comment]
check out here.

> You probably ran out of shared memory.

https://github.com/pytorch/pytorch/issues/2926#issuecomment-333778817

**Comment by Zheweiqiu** [comment]
> check out here.
> 
> > You probably ran out of shared memory.
> 
> [pytorch/pytorch#2926 (comment)](https://github.com/pytorch/pytorch/issues/2926#issuecomment-333778817)

Solved. Thank you!
