### ISSUE TITLE
problem with nms

### ISSUE THREAD

**Issue by ancorasir** [zylo117/Yet-Another-EfficientDet-Pytorch#153]
I use the D0 and the weights provided by you to inference images from realsense. I set

threshold = 0.1
iou_threshold = 0.01 

Below is the results using cv2.show. As you can see, there are many boxes overlapping. How could this happen when I set the iou_threshold to 0.01? Any suggestions? Thank you.

![test](https://user-images.githubusercontent.com/12664844/79736219-0b52d900-832c-11ea-9c34-de9c4ecfcca7.png)

**Comment by zylo117** [comment]
of course, lower iou_threshold mean allow more overlapping.

**Comment by ancorasir** [comment]
@zylo117 From the website https://pytorch.org/docs/stable/torchvision/ops.html it says:

iou_threshold (python:float) – discards all overlapping boxes with IoU > iou_threshold

**Comment by zylo117** [comment]
Yes, you are right, my mistake.

**Comment by zylo117** [comment]
can you share this image so I can debug it?

**Comment by ancorasir** [comment]
I found the problem come from the option use_float16. I tested with the following option

threshold = 0.1
iou_threshold = 0.0001
use_cuda = True
use_float16 = True / False

Obtained the following results:
float16:
![test_float16](https://user-images.githubusercontent.com/12664844/79821575-b661a200-83c1-11ea-91a7-0e28e87575a6.png)
float32:
![test_float32](https://user-images.githubusercontent.com/12664844/79821584-bc578300-83c1-11ea-818c-36d041211c07.png)

The original image is 
![test_nms](https://user-images.githubusercontent.com/12664844/79821621-d5603400-83c1-11ea-8b87-1fada9e90b75.png)
