### ISSUE TITLE
Why we heavily rely on "loss"

### ISSUE THREAD

**Issue by Cli98** [zylo117/Yet-Another-EfficientDet-Pytorch#161]
I want to figure our why nearly all posts in "Issues" focus on comparison of loss. What can it tell for a loss ~0.12? It means great? Or not? 

Why not focus on AP?

**Comment by Liu0329** [comment]
My AP is also poor. Do you get a good result ?

**Comment by Cli98** [comment]
> My AP is also poor. Do you get a good result ?

I get a AP of around 24. Yet no better than my benchmark, fasterrcnn-fpn

**Comment by zylo117** [comment]
Loss is just loss, it's not accuracy. But evaluation takes time, so it's not worth doing that at every epoch.
