### ISSUE TITLE
What is the GPU memory used during training?

### ISSUE THREAD

**Issue by xuezu29** [zylo117/Yet-Another-EfficientDet-Pytorch#162]
Hi! when I was training efficientDet-D5 on 2080Ti, a GPU could only run one image, and the input size must be less than 1024. What is your GPU device during training?  and Thank you for your sharing.

**Comment by zylo117** [comment]
Yes, 2080Ti can only fit in one image. I transferred the weights and finetune its head only. Training such large network is not possible on 2080Ti. With such small batchsize, the training will be very unstable. I recommend you switch to a smaller network or train with `--head_only True`

**Comment by xuezu29** [comment]
> Yes, 2080Ti can only fit in one image. I transferred the weights and finetune its head only. Training such large network is not possible on 2080Ti. With such small batchsize, the training will be very unstable. I recommend you switch to a smaller network or train with `--head_only True`

Thanks a lot.
