### ISSUE TITLE
anchor box

### ISSUE THREAD

**Issue by phucnhs** [zylo117/Yet-Another-EfficientDet-Pytorch#17]
Hi! 
How to use custom anchor box as same in yolo ?
Thanks

**Comment by zylo117** [comment]
custom anchor scale/ratio is supported.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/e56e81dad320ea1a35854fa4cfb31a2580903dff

Pull the latest code, and follow the intstruction of readme.

Change this part of your project.yml to specify the ratios and the scales

```
# this is coco anchors, change it if necessary
anchors_scales: [2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]
anchors_ratios: [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]
```

**Comment by phucnhs** [comment]
thanks !
If I use the kmean calculation anchor box like yolov3. How to use that anchor box !

**Comment by zylo117** [comment]
> thanks !
> If I use the kmean calculation anchor box like yolov3. How to use that anchor box !

I assume you have 9 ratios? Try to transform it to anchors_scales X anchors_ratios.

This repo use anchors_scales X anchors_ratios to represent 9 anchors.

Pull the latest code, and follow the intstruction of readme.

Change this part of your project.yml to specify the ratios and the scales

anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

**Comment by ancorasir** [comment]
@zylo117 , Could you please advise how to do that exactly?
I have compute the following 9 anchors using kmeans, the first column is box_width/image_width and the second column is box_height/image_heigh. Thank you

0.15576000000000007 0.3497215 
0.29400899999999996 0.458848 
0.607373 0.283461 
0.4442390000000001 0.555453 
0.34009199999999995 0.783205 
0.6202759999999999 0.586585 
0.514286 0.770098 
0.818894 0.6422939999999999 
0.690972 0.8236969999999999

**Comment by zylo117** [comment]
> @zylo117 , Could you please advise how to do that exactly?
> I have compute the following 9 anchors using kmeans, the first column is box_width/image_width and the second column is box_height/image_heigh.
> 
> By the way, is it ok if I just use the coco anchors for training my custom dataset? Thank you
> 
> 0.15576000000000007 0.3497215
> 0.29400899999999996 0.458848
> 0.607373 0.283461
> 0.4442390000000001 0.555453
> 0.34009199999999995 0.783205
> 0.6202759999999999 0.586585
> 0.514286 0.770098
> 0.818894 0.6422939999999999
> 0.690972 0.8236969999999999

It depends on your dataset, if it looks close enough to coco, then it's ok to leave it like it is.
Your result is not the one we need, it should be 9 rows of box_w/box_h

check this out,

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/27#issuecomment-612550889

I am not kidding, it's a little bit complicated if you are not familiar about how the anchors are generated.
