### ISSUE TITLE
请问，为什么我用下载的模型测试，效果没有仓库里面的效果好？

### ISSUE THREAD

**Issue by wangning7149** [zylo117/Yet-Another-EfficientDet-Pytorch#174]

**Comment by zylo117** [comment]
what is the command line?

**Comment by Jilliansea** [comment]
![image](https://user-images.githubusercontent.com/19787975/79941166-348f7880-8496-11ea-8fd1-ac90ea3e9ab4.png)
python  efficientdet_test.py
is it normal?

**Comment by Jilliansea** [comment]
![img_inferred_d0_this_repo_0](https://user-images.githubusercontent.com/19787975/79941293-918b2e80-8496-11ea-9b54-5d057e33baf7.jpg)
python efficientdet_test.py
is it normal?

**Comment by cometyang** [comment]
同问，我是在Mac的CPU上运行模型。

**Comment by zylo117** [comment]
This is totally normal, you need to set `force_input_size = 1920`.
But this is for demo propose, you should not use this in production

**Comment by wangning7149** [comment]
> what is the command line?

python efficientdet_test.py
