### ISSUE TITLE
What is the 'scales' used for?

### ISSUE THREAD

**Issue by vraivon** [zylo117/Yet-Another-EfficientDet-Pytorch#186]
Why do you set a complicated list, but only use its length? 

such as https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/8bf89aaabee44527ceb564a720152c18643f627a/efficientdet_test.py#L24 and https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/8bf89aaabee44527ceb564a720152c18643f627a/backbone.py#L24

**Comment by zylo117** [comment]
It will pass down to here.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/8bf89aaabee44527ceb564a720152c18643f627a/backbone.py#L53

**Comment by vraivon** [comment]
thank you for your fast reply, i ignored it
