### ISSUE TITLE
自己数据集训练结果map为0

### ISSUE THREAD

**Issue by kiddliao** [zylo117/Yet-Another-EfficientDet-Pytorch#187]
我已经跑过您的tutuorial得到了不错的map 但是我己经跑自己的数据集跑了两周了 依旧没有得到任何改善 map还是0 我能确保自己的数据集没有问题 它在我写的yolov3上可以有不错的结果
mean和std也用自己的数据集重新计算过

**Comment by kiddliao** [comment]
我的数据集与作者的shape数据集大小相当 但是是灰度图 这是不是意味着我不能使用预训练 我将dataset.py读取图片的相关函数做了修改使得读入图片是单通道

**Comment by kiddliao** [comment]
![image](https://user-images.githubusercontent.com/57079702/80076503-dc807100-857e-11ea-8854-9bb0b781ce68.png)
![image](https://user-images.githubusercontent.com/57079702/80076535-ebffba00-857e-11ea-8400-121b54691bc6.png)
这是刚刚训练的 学习率是1e-3

**Comment by zylo117** [comment]
1. did you update the latest code? If you didn't, you should manually remove val_xxx.json before evaluation, or the result will be the last result.
2. how did you load gray images? By stacking the three of them into a three-channel gray image? If so, it should work.
3. It's a little bit overfitting, but it is not the main issue here.

**Comment by kiddliao** [comment]
> 1. did you update the latest code? If you didn't, you should manually remove val_xxx.json before evaluation, or the result will be the last result.
> 2. how did you load gray images? By stacking the three of them into a three-channel gray image? If so, it should work.
> 3. It's a little bit overfitting, but it is not the main issue here.

我读取灰度图片用的是cv2.imread(path,0) 请问这样有影响吗

**Comment by kiddliao** [comment]
> 1. did you update the latest code? If you didn't, you should manually remove val_xxx.json before evaluation, or the result will be the last result.
> 2. how did you load gray images? By stacking the three of them into a three-channel gray image? If so, it should work.
> 3. It's a little bit overfitting, but it is not the main issue here.

我之前训练是把灰度图读取为三通道图片 每个通道的矩阵都是一样的 不过这样map还是接近为0

**Comment by zylo117** [comment]
Did you manually remove val_xxx.json?

**Comment by zylo117** [comment]
cv2.imread(xxx, 0) means loading image in greyscale, right?
But how can you train without exception? The input channel should be 3. What and where did you modify to adapt greyscale image?
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientnet/model.py#L139

**Comment by kiddliao** [comment]
> cv2.imread(xxx, 0) means loading image in greyscale, right?
> But how can you train without exception? The input channel should be 3. What and where did you modify to adapt greyscale image?
> https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientnet/model.py#L139

在dataset.py里的load_image和class Resizer进行了相应修改
在model.py有一处 inchannel=3#rgb 我改成了1
能正常训练和检测 每次检测前都删除了上次检测结果

**Comment by kiddliao** [comment]
> cv2.imread(xxx, 0) means loading image in greyscale, right?
> But how can you train without exception? The input channel should be 3. What and where did you modify to adapt greyscale image?
> https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientnet/model.py#L139

您好 更新了源码后我发现问题解决了 上一次下的源码大概八天前下载的
同样的所有参数训练的d1 新代码work 旧代码还是map=0

**Comment by zylo117** [comment]
great

**Comment by houlei123123** [comment]
> 
> 
> > cv2.imread(xxx, 0) means loading image in greyscale, right?
> > But how can you train without exception? The input channel should be 3. What and where did you modify to adapt greyscale image?
> > https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientnet/model.py#L139
> 
> 您好 更新了源码后我发现问题解决了 上一次下的源码大概八天前下载的
> 同样的所有参数训练的d1 新代码work 旧代码还是map=0

你好，我同样训练的gray图像，并且修改了normalize和model的input channel，可是训练不出结果。能不能请教下，您是怎么改的bug
