### ISSUE TITLE
这个 anchors = self.anchors(inputs, inputs.dtype)是不是放到init里比较好，放在这里每次inference都要计算一下，多多少少会影响inference speed

### ISSUE THREAD

**Issue by ysp568** [zylo117/Yet-Another-EfficientDet-Pytorch#189]
`def forward(self, inputs):
        max_size = inputs.shape[-1]

        _, p3, p4, p5 = self.backbone_net(inputs)

        features = (p3, p4, p5)
        features = self.bifpn(features)

        regression = self.regressor(features)
        classification = self.classifier(features)
  

>       anchors = self.anchors(inputs, inputs.dtype)
这个 anchors = self.anchors(inputs, inputs.dtype)是不是放到init里比较好，放在这里每次inference都要计算一下，多多少少会影响inference speed

        return features, regression, classification, anchors
`

**Comment by ysp568** [comment]
with torch.no_grad():
        anchors = self.anchors(inputs, inputs.dtype)

**Comment by ysp568** [comment]
>for example  

> class EfficientDetBackbone(nn.Module):

    def` __init__(self, num_classes=80, compound_coef=0, load_weights=False, **kwargs):
        super(EfficientDetBackbone, self).__init__()
        with torch.no_grad():
                 self.anchor = self.anchors(inputs, inputs.dtype)

**Comment by zylo117** [comment]
No.
Check out here.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientdet/utils.py#L95

It will store the last anchor and return it immediately as long as it's the same size, same device, same dtype
