### ISSUE TITLE
Results are not identical to what is shown

### ISSUE THREAD

**Issue by M-S-KHAN** [zylo117/Yet-Another-EfficientDet-Pytorch#190]
Hi there, so I ran the inference using D2 and even D3 weights. As you can see in the image attached, the output from the inference from D3 isn't even close to what they're showing on D0. Why is that?
![img_inferred_d3_this_repo_0](https://user-images.githubusercontent.com/51326962/80099386-cb882d80-8587-11ea-806f-64adf786d147.jpg)

**Comment by zylo117** [comment]
set `force_input_size=1920`

**Comment by M-S-KHAN** [comment]
Works! Thanks.
