### ISSUE TITLE
image preprocess

### ISSUE THREAD

**Issue by markgao-916** [zylo117/Yet-Another-EfficientDet-Pytorch#196]
@zylo117 Hi, thanks for your great work. I have a question about image padding for the same ratio of origin in this code ,you put the image not at center but left and top, i wonder the influence for result.
   canvas[:new_h, :new_w] = image

**Comment by zylo117** [comment]
duplicated. https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/181#issuecomment-618162232
