### ISSUE TITLE
Question about preprocess

### ISSUE THREAD

**Issue by zdaiot** [zylo117/Yet-Another-EfficientDet-Pytorch#197]
Thank you for your great work~

Your preprocessing is normalized in numpy form and then turned into tensor. Why not direct use torchvision totensor and Normalize to do this?

I tried to change to torchvision to do this. And in the reasoning phase, the preprocessing speed can be reduced from over 100 ms to 2.7ms. But the accuracy is a little bit down. It is not yet known why.

You version
![img_inferred_d0_this_repo_0](https://user-images.githubusercontent.com/40540467/80174033-19527380-8624-11ea-81b6-65c3448e017e.jpg)

Torchvison version
![img_inferred_d0_this_repo_01](https://user-images.githubusercontent.com/40540467/80174054-2707f900-8624-11ea-93f0-48e284aaf401.jpg)

**Comment by zylo117** [comment]
I did it intentionally. I don't want the preprocess and postprocess to rely on torch.
Can you share your code? It either RGB BGR issue or data precision issue.

**Comment by zdaiot** [comment]
I found the reason. Because the mean and the variance are in the wrong order. Thanks a lot

**Comment by shaheryar1** [comment]
Hey @zdaiot I am getting 140 ms on preprocessing for 1 frame. Can you share the method you used to lower the inference time ?

**Comment by zdaiot** [comment]
```
def aspectaware_resize_padding(image, width, height, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
    old_h, old_w, c = image.shape

    # 保证new_w:new_h=old_w:new_w
    if old_w > old_h:
        new_w = width
        new_h = int(width / old_w * old_h)
    else:
        new_w = int(height / old_h * old_w)
        new_h = height

    padding_h = height - new_h
    padding_w = width - new_w

    image = cv2.resize(image, (new_w, new_h))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    transform_val_list = [
        T.ToTensor(),
        T.Normalize(mean, std)
    ]
    transform_compose = T.Compose(transform_val_list)
    image = transform_compose(image)
    image = F.pad(image, (0, padding_w, 0, padding_h), "constant", 0)

    # image：[3, 512, 512]
    return image, new_w, new_h, old_w, old_h, padding_w, padding_h


def preprocess(*samples, width, height, mean, std, use_video=False):
    if use_video:
        images = samples
        image_origin = [img.copy() for img in samples]
    else:
        images = [cv2.imread(img_path) for img_path in samples]
        image_origin = [image.copy() for image in images]
    t0 = time.time()
    imgs_meta = [aspectaware_resize_padding(image, width, height, mean, std) for image in images]
    framed_imgs = [img_meta[0] for img_meta in imgs_meta]
    framed_metas = [img_meta[1:] for img_meta in imgs_meta]
    return image_origin, framed_imgs, framed_metas, t0
```
