### ISSUE TITLE
train.py save_checkpoint maybe error

### ISSUE THREAD

**Issue by liulangxing** [zylo117/Yet-Another-EfficientDet-Pytorch#198]
使用两块显卡，训练pytorch模型
在测试时，导入模型会报如下类似错误：
using weights logs/bdd100kcoco/efficientdet-d0_21_334992.pth
Traceback (most recent call last):
  File "efficientdet_test_images.py", line 59, in <module>
    model.load_state_dict(torch.load(weights_path))
  File "/home/omnisky/anaconda3/envs/efficientdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone:
	size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([81, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([810, 64, 1, 1]).
	size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([810]).

https://blog.csdn.net/yangzhengzheng95/article/details/88574200
训练模型使用多个gpu，然后在测试时候不需要用单个gpu，因此在保存模型时应该吧module层去掉
if use_single_gpu:
    t.save(net.module.state_dict(), "model.pth")
else:
    t.save(net.state_dict(), "model.pth")

train.py
if params.num_gpus > 1:
    model = CustomDataParallel(model, params.num_gpus)
def save_checkpoint(model, name):
    if isinstance(model, CustomDataParallel):
        torch.save(model.module.model.state_dict(), os.path.join(opt.saved_path, name))
    else:
        torch.save(model.model.state_dict(), os.path.join(opt.saved_path, name))

so I modify save_checkpoint function:

def save_checkpoint(models, name):
    #gpus>1
    if isinstance(models, CustomDataParallel):
        #torch.save(model.module.model.state_dict(), os.path.join(opt.saved_path, name))
        torch.save(models.state_dict(), os.path.join(opt.saved_path, name))
    else:
        #torch.save(model.model.state_dict(), os.path.join(opt.saved_path, name))
        torch.save(models.module.state_dict(), os.path.join(opt.saved_path, name))

**Comment by zylo117** [comment]
1. you need to modify obj list and everything else from your project.

2. you do not need to modify save_checkpoint like that. it's already been dealt with.
