### ISSUE TITLE
 No such operator torchvision::nms

### ISSUE THREAD

**Issue by gooodfan** [zylo117/Yet-Another-EfficientDet-Pytorch#2]
when I run the python efficientdet_test.py
there is an error that perhaps due to the version of torchvison？
but I have reinstalled the required version of every tools，pycocotools、torch==1.4.0 and torchvision==0.5.0.
I dont know why the error still appears.

mess up now...

**Comment by zylo117** [comment]
i am guessing you are using anaconda? or u installed a different kind of platform of torchvision?

there are lots of platforms like cu90, cu92, cu100, cpu, or so on. torch's platform must matches torchvision's. u should check it with pip list or conda list.

BTW, the anchor is buggy, the result might be bad, working on a fix soon.

**Comment by zylo117** [comment]
I fixed the anchor issue, you should pull the latest code and try again.

**Comment by gooodfan** [comment]
> i am guessing you are using anaconda? or u installed a different kind of platform of torchvision?
> 
> there are lots of platforms like cu90, cu92, cu100, cpu, or so on. torch's platform must matches torchvision's. u really should check on it.
> 
> BTW, the anchor is buggy, the result might be bad, working on a fix soon.

thank u sooo much

**Comment by keshawnhsieh** [comment]
Downgrade Python version from 3.7 to 3.6.10 solves this problem.

**Comment by Mankvis** [comment]
If the CPU is used, use_cuda=False, then cuda will not be used, and why will it report an error? RuntimeError: No such operator torchvision::nms
torch 1.4.0+cu92
torchvision 0.5.0
