### ISSUE TITLE
Did you upload the right efficientdet-d7.pth?

### ISSUE THREAD

**Issue by sphcn** [zylo117/Yet-Another-EfficientDet-Pytorch#20]
The efficientdet-d6.pth and efficientdet-d7.pth are the same size. Just wanna make sure. Thanks.

**Comment by zylo117** [comment]
Yes, like I mentioned on my update log, D7 is exact D6 weights with different input size and different anchor scale.

**Comment by sphcn** [comment]
Thanks again.
