### ISSUE TITLE
How to create a custom dataset like Shape dataset?

### ISSUE THREAD

**Issue by winter2897** [zylo117/Yet-Another-EfficientDet-Pytorch#207]
I have a dataset with 1 class that has been labeled with the LabelImg tool in Pascal/Voc format. How can I convert them to COCO 2017 (instances_train.json)? 
I tried using [roboflow](https://app.roboflow.ai/), a tool to convert the .xml files to COCO format, but when training on Google Colab I encountered an error as shown below.
![demodataset](https://user-images.githubusercontent.com/22476495/80300203-cc59d300-87c4-11ea-8a04-7d26253a673e.png)
![error](https://user-images.githubusercontent.com/22476495/80300204-cd8b0000-87c4-11ea-9ee9-2755c5a485e2.png)
![json](https://user-images.githubusercontent.com/22476495/80300205-ce239680-87c4-11ea-936a-73a47e2bba71.png)

@zylo117  Could you help me?

**Comment by zylo117** [comment]
There should be a lot of VOC2COCO tools in github.
