### ISSUE TITLE
Broken Pipe Error when attempting to train on coco

### ISSUE THREAD

**Issue by JacobCassarEllis** [zylo117/Yet-Another-EfficientDet-Pytorch#213]
I am attempting to train an efficientdet D7 model on the coco dataset as I simply need to evaluate it for thesis purposes. However, whenever I attempt to run the train.py with any efficientdet model I encounter a Broken Pipe error after being stuck at 0% training for around 4/5 minutes.  I set up the coco dataset correctly, inference script works for efficientdet d0 but training doesnt work on either.
![1](https://user-images.githubusercontent.com/49341570/80393041-3dc28000-88b0-11ea-9726-e0d6394586da.jpg)

I also attempted running the efficientdet D7 weights provided within the inference script, but failed due to several size mismatch errors. Would you happen to have an script that can run a pre-trained efficientdet d7 model on custom images?

**Comment by zylo117** [comment]
Training on windows? Set `-n 0`.
If it is possible, dont't train on windows, it's slow in any way.
