### ISSUE TITLE
Why it seems d0 is even better than d7 in same input size

### ISSUE THREAD

**Issue by xuwanqi** [zylo117/Yet-Another-EfficientDet-Pytorch#220]
![img_inferred_d0_this_repo](https://user-images.githubusercontent.com/43168511/80444395-419fe200-8944-11ea-8fa1-45300ce6b43e.jpg)
![img_inferred_d7_this_repo_0](https://user-images.githubusercontent.com/43168511/80444171-9d1da000-8943-11ea-875f-9b4ebb661136.jpg)
above is the result in d0 with input size 1920,below is result in d7.so ,d0 get more correct box and higher confidence,althought d0 get more wrong answer,it still seems better than d7,so why?

**Comment by zylo117** [comment]
actually both of them is cheating.

when you objectively evaluate the accuracy, you should set input size to default value.

Then you will see d7 is better than d0.

**Comment by xuwanqi** [comment]
but i find d0 with large input is still quicker than d7.so,do you test the real mAP which use model d0 with large input?

**Comment by zylo117** [comment]
yes, and it's bad
