### ISSUE TITLE
Focal Loss

### ISSUE THREAD

**Issue by rvandeghen** [zylo117/Yet-Another-EfficientDet-Pytorch#233]
Hi,

I'm a bit confused with the loss because when there is no annotation, you should still compute a log loss where the target vector are just full of zeros ?

I know your focal loss comes from https://github.com/yhenon/pytorch-retinanet but I'm no more sure this is a good implementation.

**Comment by zylo117** [comment]
Can you specify the line number?

**Comment by rvandeghen** [comment]
Line 54 in efficientdet/loss you append a loss of 0 if there are no annotations. I can understand that we can't compute the smothL1 but still we can compute the BCE.

**Comment by rvandeghen** [comment]
I made a PR at yhenon/pytorch-retinanet#145

**Comment by zylo117** [comment]
That's a good point. In this case, it's able to learn from background samples with no annotation.

**Comment by dkoguciuk** [comment]
That's interesting @rvandeghen! I wonder, how many images in COCO don't have annotations? How much this affects the learning?

**Comment by dkoguciuk** [comment]
[Here's](https://github.com/cocodataset/cocoapi/issues/76#issuecomment-331633983) a claim that there are 1k images without annotation compared to the whole dataset of 118K images. That change can indeed bring some value (at least according to my potato intuition).

**Comment by zylo117** [comment]
merged. https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/54c5345d2bd90919ee50b25ce4d1fa8a6a64faea
