### ISSUE TITLE
High Preprocessing time 

### ISSUE THREAD

**Issue by shaheryar1** [zylo117/Yet-Another-EfficientDet-Pytorch#235]
I am getting **150 ms** on image **preprocessing** step for a single frame.

`now =time.time()
ori_imgs, framed_imgs, framed_metas = preprocess(img_path, max_size=input_size)
print(time.time()-now)`

In your efficientdet_test.py script you are not considering the preprocessing time . Should,nt it be included while testing the model performance ? 

PS : If I consider preprocessing time while inference on videos the fps drops from 30 to 7 for d0 at default resolutions.

GPU used : gtx 1070
OS : Ubuntu 18.04
CPU : i5 4590

**Comment by zylo117** [comment]
It shouldn't take that long. Did you run this line once or many times? The first time is always slower.
It is only image reading and resizing, it's fast.

**Comment by shaheryar1** [comment]
For videos I am doing it for each frame and on each frame its taking upto 150 ms

**Comment by zylo117** [comment]
I see. imread and normalizing takes a lot of time on CPU.
But still, I don't think preprocessing should be included in speed test.
Though there is hardly a better way to make this process faster, you can try prefetch and batch loading to reduce its impact.

**Comment by shaheryar1** [comment]
But in case of live camera feed the preprocessing time needs to be done on each of the latest frame and this impacts the performance  of the model on a live video feed where data is coming in a stream instead of batch 
Ps : if you have any way to minimize the impact in case of live feed please share

**Comment by zylo117** [comment]
Just implement a buffer to load images while inferring.
