### ISSUE TITLE
typo in speed test

### ISSUE THREAD

**Issue by Bohrhh** [zylo117/Yet-Another-EfficientDet-Pytorch#24]
### Thanks for the excellent repository.
Pytorch speed ratio may be wrong. It should be 0.713/0.028=25.5

![Screenshot from 2020-04-12 02-10-27](https://user-images.githubusercontent.com/32504696/79051436-d4613100-7c62-11ea-85d6-61d97363507e.png)

**Comment by zylo117** [comment]
oh, You're right, I'll fix it now.

**Comment by zylo117** [comment]
Hi, I fixed it and tested again.  Thanks for telling me.

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/3341d4f17e58a8cb1ea029d6a3c0e9d906b9283d
