### ISSUE TITLE
How should I deal with my gray scale images?

### ISSUE THREAD

**Issue by hazy-wu** [zylo117/Yet-Another-EfficientDet-Pytorch#240]
Dear author:
I wanna use custom data to train the network so I rewrite the 'dataset' code to suit my data format. But at this time I confuse that why should the images' array subtract the 'mean'? 
My data is a series of gray-scale images, so should I do normalization such as make image-array divide 255, decrease 'mean' and divide 'std'?  What's these steps mean?
I m sorry that I don't know about 'coco dataset' totally.
If need, how do I set the 'mean' and 'std'?
       Can you help me?  THANKS!

**Comment by zylo117** [comment]
can't load gray scale image.
but you can vstack them into a 3-channel gray scale image.

**Comment by hazy-wu** [comment]
> can't load gray scale image.
> but you can vstack them into a 3-channel gray scale image.

thanks! so how do I set the 'mean' and 'std'?

**Comment by zylo117** [comment]
that should be the mean and std of your images, in [0, 1], not [0, 255].

**Comment by hazy-wu** [comment]
ohh！I get it! thanks! so appreciate you !
