### ISSUE TITLE
Any idea on why using different p4_0 to p4_1 and p4_2?

### ISSUE THREAD

**Issue by c1aris** [zylo117/Yet-Another-EfficientDet-Pytorch#246]
In the bottom_up phase, the authors re-downchannelled p4 and p5, but not p6 and p7.

Seems it's a little bit tricky to do that :)

Also, p5_to_p6 and p6_to_p7 looked weird as well.

**Comment by zylo117** [comment]
Because P6 and P7 are generated by p5_to_p6 and p6_to_p7, and their num_channels are already the same as BiFPN inputs'. Hence no downchannel on  P6 and P7.

**Comment by c1aris** [comment]
Got it, thank you so much!
