### ISSUE TITLE
completely out of range mAP 

### ISSUE THREAD

**Issue by eduardohem** [zylo117/Yet-Another-EfficientDet-Pytorch#247]
After 45 epochs, dataset 2404 images, 1 class:
command> python3 train.py -c 0 --batch_size 2 -p mestrado --lr 1e-7  --num_epochs 100 --load_weights ./weights/efficientdet-d0.pth

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

**Comment by qtw1998** [comment]
It's your training and val sets' problem

**Comment by qtw1998** [comment]
> After 45 epochs, dataset 2404 images, 1 class:
> command> python3 train.py -c 0 --batch_size 2 -p mestrado --lr 1e-7 --num_epochs 100 --load_weights ./weights/efficientdet-d0.pth
> 
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.000
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

![image](https://user-images.githubusercontent.com/34357479/80905913-ad6bbb80-8d45-11ea-8f08-0e3a15342899.png)
I met the same problem dude

**Comment by zylo117** [comment]
how about the tutorial? does it work?

**Comment by singlautsav** [comment]
I am having a exactly same Eval Output as above two. I am training on 200 classes

> !python coco_eval.py -p productDataset -c 1 -w '/content/drive/My Drive/Yet-Another-EfficientDet-Pytorch/logs/productDataset/efficientdet-d1_18_31500.pth'

`Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000`

**Comment by eduardohem** [comment]
> how about the tutorial? does it work?

![Captura de Tela (69)](https://user-images.githubusercontent.com/34003174/80943470-abddda00-8dbd-11ea-9076-b1dc34c5309a.png)

**Comment by zylo117** [comment]
then there is something wrong with your environmet or your code.
did you modify the code?
If you run this tutorial on colab, it will provide the correct result

**Comment by eduardohem** [comment]
> then there is something wrong with your environmet or your code.
> did you modify the code?
> If you run this tutorial on colab, it will provide the correct result

![image](https://user-images.githubusercontent.com/34003174/80999457-1d984100-8e1b-11ea-9e6b-1c4dfc528a75.png)

It works!
I clone the colab notebook and did the same process with my customdataset.

I think it was outdated code.
Thanks.
