### ISSUE TITLE
Error：Corrupt JPEG data: premature end of data segment

### ISSUE THREAD

**Issue by wangziyan1234** [zylo117/Yet-Another-EfficientDet-Pytorch#250]
![image](https://user-images.githubusercontent.com/48083793/80935371-d7cd7f80-8dfe-11ea-96ff-da9c4bd4d0bc.png)    Hello~   Do you know where the problem is？ my  data set is 2048*4096 with one channel

**Comment by zylo117** [comment]
your image is corrupt/ not complete.
It's a risk though.
opencv will try to recover the image but it could fail to do that sliently.
you should manually visualize your images first.

**Comment by wangziyan1234** [comment]
@zylo117 Thank you so much~    emmm , I just trained the  images in another model(retinanet), it works normally, so i think  the images are complete  ,do you know other reasons else? Will it have something to do with the image's channel or size?  Thank you again (*￣︶￣)

**Comment by zylo117** [comment]
I don't think so
