### ISSUE TITLE
can’t get the desired output

### ISSUE THREAD

**Issue by missbook520** [zylo117/Yet-Another-EfficientDet-Pytorch#253]
Thank you for your great work!
But when I try to test ./test/img.png  use  d2.pth,I can't get the disired output
can you give me some advices?
![img_inferred_d2_this_repo_0](https://user-images.githubusercontent.com/48777650/81026918-63521980-8eae-11ea-9a8b-e18992fc6add.jpg)
![Uploading img_inferred_d2_this_repo_0.jpg…]()
![Uploading img_inferred_d2_this_repo_0.jpg…]()

**Comment by zylo117** [comment]
set `force_input_size=1920`

**Comment by missbook520** [comment]
> set `force_input_size=1920`

thanks!

**Comment by sourabhyadav** [comment]
> set `force_input_size=1920`

@zylo117 How does this will affect mAP? As I see more bounding boxes when I change ```force_input_size=None``` to ```force_input_size=1920```. 

What is the correct way to conferencing on our custom dataset? Please explain.

Thanks

**Comment by zylo117** [comment]
1. Larger image makes small target bigger while network receptive field remains unchanged.
2. mAP of larger objects are much higher than smaller objects.

So, by enlarging image, the mAP of smaller objects will be better, theoretically. But mAP of larger objects may be worse.

You can run coco_eval with different resolution to see if it's true.
