### ISSUE TITLE
WORSE THAN TENSORFLOW OFFICIAL RESULTS INFERRING CUSTOM DATASETS

### ISSUE THREAD

**Issue by qtw1998** [zylo117/Yet-Another-EfficientDet-Pytorch#258]
It's tensorflow official version infer:
![](https://site-pictures.oss-eu-west-1.aliyuncs.com/lmap3.jpg)
below is the converged of YET version:
![](https://site-pictures.oss-eu-west-1.aliyuncs.com/jcv1e.png)

**Comment by zylo117** [comment]
tensorflow uses original image size while I use network's default.
You can set `force_input_size` to whatever you want.

**Comment by qtw1998** [comment]
> tensorflow uses original image size while I use network's default.
> You can set `force_input_size` to whatever you want.

Still worse than original tf codes
![output](https://user-images.githubusercontent.com/34357479/81162113-3b9ea680-8fbf-11ea-985f-bcc6b21a60c6.jpg)
