### ISSUE TITLE
Some questions about input image size

### ISSUE THREAD

**Issue by LittleBoy7** [zylo117/Yet-Another-EfficientDet-Pytorch#26]
Sorry, if I want to use efficientdet-d7.pth  models to train my own datasets. Do I need to change the size of the images into the corresponding size in the paper?

**Comment by zylo117** [comment]
No, you don't need to resize manually, The program will do it by itself.

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/train.py#L112

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/train.py#L116

**Comment by LittleBoy7** [comment]
thanks!!!
