### ISSUE TITLE
WORSE THAN TENSORFLOW OFFICIAL RESULTS INFERRING CUSTOM DATASETS 

### ISSUE THREAD

**Issue by qtw1998** [zylo117/Yet-Another-EfficientDet-Pytorch#262]
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/258#issue-612721607
It's the truth 'YET' version is much worse than tf official version... with the same output settings..

**Comment by qtw1998** [comment]
Even I set the settings as iou_threshold=0.9, threshould=0.1, --force_input_size=20000(huhu) 
the areas have been detected be much much worse than official 
YET VERSION -- iou_threshold=0.9, --threshould=0.1, --force_input_size=20000
![output](https://user-images.githubusercontent.com/34357479/81163298-1c087d80-8fc1-11ea-9ea6-03c9a67b2292.jpg)
TF OFFICIAL VERSION --iou_threshold=0.5, --threshould=0.5, --force_input_size=1920(origin input size)
![68747470733a2f2f736974652d70696374757265732e6f73732d65752d776573742d312e616c6979756e63732e636f6d2f6c6d6170332e6a7067](https://user-images.githubusercontent.com/34357479/81163421-4a865880-8fc1-11ea-8f7e-1b2854ac8973.jpg)

**Comment by qtw1998** [comment]
Actually the tf version has so so so so many tricks for data augmentation..... 
Yet version has nothing..
![image](https://user-images.githubusercontent.com/34357479/81164610-35aac480-8fc3-11ea-89f6-c9de779b18be.png)
It's like playing with axes at the door of Luban home..

**Comment by ibrahimsoliman97** [comment]
is data augmentation the only difference between this repo and tensorflow repo ?
