### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by rvandeghen** [zylo117/Yet-Another-EfficientDet-Pytorch#263]
Hello,

Does your memory usage in the README come from `nvidia-smi` because my GPU memory is way higher than yours ?

Thank you

**Comment by zylo117** [comment]
inference or training? That's just inference

**Comment by rvandeghen** [comment]
Yeah obviously. 

But still during training I sometimes have OOM error when training on EffDetB > 4 even with a small batch size

**Comment by zylo117** [comment]
training consumes 3 times memory usage at least.
yes, training D4 or larger network is painful.
