### ISSUE TITLE
[Customer Small Object Dataset ] If you have not modified your anchor, do give it a try

### ISSUE THREAD

**Issue by Cli98** [zylo117/Yet-Another-EfficientDet-Pytorch#265]
Hi guys,

I explored how anchor works in past three weeks. And actually it is much more important than I expected.

Just give you guys some examples.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/19630616/81251586-9e109a80-8ff1-11ea-89a1-4bf66411c00f.png">

<img width="851" alt="image" src="https://user-images.githubusercontent.com/19630616/81250911-1f672d80-8ff0-11ea-8157-b09d30f7145b.png">

If you see green boxes, then it is a match. Else you get **A BIG ISSUE**. For small object detection dataset or aerial image dataset, I guess that you all need to recompute anchor parameters.

Give me some comments on my work if you can, thank you! Free feel to email me (lcltopismine3@gmail.com) for personal/professional discussion.

**Comment by FancyFai** [comment]
> Hi guys,
> 
> I explored how anchor works in past three weeks. And actually it is much more important than I expected.
> 
> Just give you guys some examples.
> 
> <img alt="image" width="888" src="https://user-images.githubusercontent.com/19630616/81251586-9e109a80-8ff1-11ea-89a1-4bf66411c00f.png">
> 
> <img alt="image" width="851" src="https://user-images.githubusercontent.com/19630616/81250911-1f672d80-8ff0-11ea-8157-b09d30f7145b.png">
> 
> If you see green boxes, then it is a match. Else you get **A BIG ISSUE**. For small object detection dataset or aerial image dataset, I guess that you all need to recompute anchor parameters.
> 
> Give me some comments on my work if you can, thank you! Free feel to email me ([lcltopismine3@gmail.com](mailto:lcltopismine3@gmail.com)) for personal/professional discussion.

Hello, I would like to ask whether you have modified anchors_ratios and anchor_scale. If I get the height and width of anchor through kmeans（like [[358 ,144] [405, 414] [550, 637]]）, how to convert them to the corresponding anchors_ratios and anchor_scale? Can you give me some Suggestions. Looking forward to your reply

**Comment by Cli98** [comment]
> > Hi guys,
> > I explored how anchor works in past three weeks. And actually it is much more important than I expected.
> > Just give you guys some examples.
> > <img alt="image" width="888" src="https://user-images.githubusercontent.com/19630616/81251586-9e109a80-8ff1-11ea-89a1-4bf66411c00f.png">
> > <img alt="image" width="851" src="https://user-images.githubusercontent.com/19630616/81250911-1f672d80-8ff0-11ea-8157-b09d30f7145b.png">
> > If you see green boxes, then it is a match. Else you get **A BIG ISSUE**. For small object detection dataset or aerial image dataset, I guess that you all need to recompute anchor parameters.
> > Give me some comments on my work if you can, thank you! Free feel to email me ([lcltopismine3@gmail.com](mailto:lcltopismine3@gmail.com)) for personal/professional discussion.
> 
> Hello, I would like to ask whether you have modified anchors_ratios and anchor_scale. If I get the height and width of anchor through kmeans（like [[358 ,144] [405, 414] [550, 637]]）, how to convert them to the corresponding anchors_ratios and anchor_scale? Can you give me some Suggestions. Looking forward to your reply

There are already lots of discussion on this topic in current repo. In short, you need a two-factor decomposition. To summarize, 1). Use kmean to find suitable anchors. 2). Compute scale and ratio from kmean result. Make sure scale*ratio -> kmean result.

I will post my code for anchor computations after I pass necessary tests. Stay tuned.

**Comment by jinfagang** [comment]
@Cli98  Can u post your kmeans and scale/ratio calculation code?

**Comment by Cli98** [comment]
> @Cli98 Can u post your kmeans and scale/ratio calculation code?

I'm testing my code now. If I am able to see Improvements in AP then I will modify it and post here.

**Comment by jinfagang** [comment]
@Cli98 Why closing issue?

**Comment by Cli98** [comment]
> @Cli98 Why closing issue?

@jinfagang Just get notified. As there are already lots of issues in this repo. I do not want to take other's slot. I will PR when I'm ready to share the code.

**Comment by Cli98** [comment]
> > @Cli98 Why closing issue?
> 
> @jinfagang Just get notified. As there are already lots of issues in this repo. I do not want to take other's slot. I will PR when I'm ready to share the code.

Give it a try if you need. https://github.com/Cli98/anchor_computation_tool
Good luck!
