### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by Cli98** [zylo117/Yet-Another-EfficientDet-Pytorch#266]
Hi @zylo117 ,

I want to ask one question for training.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/19630616/81255831-bcc85e80-8ffc-11ea-8d44-b6e770222933.png">

I actually changed my anchors to new setup. Then I get this issue. The issue comes from conv layer. What's the meaning for this error? Can you tell me how to debug? 

The new conf for anchors:
anchors_scales: '[54/32,61/32,76/32,153/32,210/32,100/32]'
anchors_ratios: '[(1,2),(1,1),(1,1.05),(1,1.34)]'

Thank you,

**Comment by zylo117** [comment]
GPU OOM?

**Comment by Cli98** [comment]
> GPU OOM?

@zylo117  I figured out what happened. I assigned batch_size as 2. But I set gpu_num as 4. So some gpu get 0 samples and it breaks.

Is that possible for you to add some code to compare whether batch_size>Gpu_num? This could help beginners(I'm one of them) and save them sometime to debug.

**Comment by zylo117** [comment]
sure. https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/269b3561f0ebec2ba672d6c903521dddff797cd8.

**Comment by Cli98** [comment]
> sure. [269b356](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/269b3561f0ebec2ba672d6c903521dddff797cd8).

Well done!
