### ISSUE TITLE
i consider that nms should be used to each class in each image when detecting image, but i see the nms do all classes in each image. i wonder know how it works. 

### ISSUE THREAD

**Issue by Laughing-q** [zylo117/Yet-Another-EfficientDet-Pytorch#270]

**Comment by Laughing-q** [comment]
i change the nms to each class in each image, i test it on 'test/img.png' by efficientdet-d4, the boxes increased 13(67 to 80), and some classes (like motorcycle) which highly overlaps with other classes (like people) before was found.

**Comment by zylo117** [comment]
torchvision.ops.nms performs class-agnostic nms, it doesn't care whether the boxes are in the same class or not.

**Comment by Laughing-q** [comment]
> torchvision.ops.nms performs class-agnostic nms, it doesn't care whether the boxes are in the same class or not.

yes, i know ,i just think the nms in code should care each class which it doesn't, or boxes of some other classes will miss.

**Comment by Laughing-q** [comment]
> torchvision.ops.nms performs class-agnostic nms, it doesn't care whether the boxes are in the same class or not.

and i notice that your coco_eval.py include this wrong nms，i guess maybe this will affect your coco results？

**Comment by zylo117** [comment]
I don't think this is a wrong nms impl, it's just another style. 
Have you considered this situation?
If there are 10 boxes of 5 classes around a single object, and only one class is correct, which boxes should be kept?
With class-aware nms, there will be 5 boxes around a single object, then ap is 0.2.

Let's say they both have their pros and cons.

**Comment by Laughing-q** [comment]
> I don't think this is a wrong nms impl, it's just another style.
> Have you considered this situation?
> If there are 10 boxes of 5 classes around a single object, and only one class is correct, which boxes should be kept?
> With class-aware nms, there will be 5 boxes around a single object, then ap is 0.2.
> 
> Let's say they both have their pros and cons.

i see, but class-agnostic nms may miss some boxes of other classes when detecting

**Comment by zylo117** [comment]
try batched_nms

**Comment by Laughing-q** [comment]
> try batched_nms

i have already tried this, and proved that there is missing some boxes which model should detect with class-aware nms.

**Comment by Laughing-q** [comment]
> I don't think this is a wrong nms impl, it's just another style.
> Have you considered this situation?
> If there are 10 boxes of 5 classes around a single object, and only one class is correct, which boxes should be kept?
> With class-aware nms, there will be 5 boxes around a single object, then ap is 0.2.
> 
> Let's say they both have their pros and cons.

i considered it, but i think this situation is to make a model which have a bad performance look like a good model by using class-agnostic nms to improve ap. sorry, no offense， i truely want to discuss which nms should we used in multi class object situation by my bad English....

**Comment by zylo117** [comment]
'If you can't tell, does it matter?' : WestWorld.
Post-process is still a part of a model. It's no shame choosing a tricky post-processing method to hide the model's defects. As long as the AP is satisfying, why would one care?

**Comment by Laughing-q** [comment]
> 'If you can't tell, does it matter?' : WestWorld.
> Post-process is still a part of a model. It's no shame choosing a tricky post-processing method to hide the model's defects. As long as the AP is satisfying, why would one care?

my point is not this.....,  as a student, i just want to know which is suitable, or just use different one in different situation

**Comment by zylo117** [comment]
So try batched_nms, it is class-aware nms, while nms is class-agnostic nms.
Or try to implement a nms you want and run the evalutaion, see which one provides higher mAP.

**Comment by Laughing-q** [comment]
> So try batched_nms, it is class-aware nms, while nms is class-agnostic nms.
> Or try to implement a nms you want and run the evalutaion, see which one provides higher mAP.

i am actually going to do this， To ensure consistency, are you using val2017 to get your results? i see it in coco.yml

**Comment by zylo117** [comment]
yes

**Comment by Laughing-q** [comment]
> yes

my result on val2017 is 51.2(efficientdet-D7), i think it is worth to try other models by using  class-aware nms if you have time.

**Comment by Laughing-q** [comment]
> yes

and i find that 51.8 on efficientdet-d7 is actually val2017's map in Original paper， 52.2 is test-dev's map.

**Comment by zylo117** [comment]
well done!

**Comment by Cli98** [comment]
> > yes
> 
> and i find that 51.8 on efficientdet-d7 is actually val2017's map in Original paper， 52.2 is test-dev's map.

@Laughing-q You should be aware of what you are doing... clearly this is not a bug as far as I consider.

**Comment by Laughing-q** [comment]
> > > yes
> > 
> > 
> > and i find that 51.8 on efficientdet-d7 is actually val2017's map in Original paper， 52.2 is test-dev's map.
> 
> @Laughing-q You should be aware of what you are doing... clearly this is not a bug as far as I consider.

actually i just remind the author, the author's result is tested on coco-val2017, but compared the results which is on coco-test-dev in original paper.

**Comment by zylo117** [comment]
Yes, @Laughing-q  is right. I updated nms with batched_nms, the mAP does improve. And I'll push the code soon. Thanks so much.

**Comment by Cli98** [comment]
> > > > yes
> > > 
> > > 
> > > and i find that 51.8 on efficientdet-d7 is actually val2017's map in Original paper， 52.2 is test-dev's map.
> > 
> > 
> > @Laughing-q You should be aware of what you are doing... clearly this is not a bug as far as I consider.
> 
> actually i just remind the author, the author's result is tested on coco-val2017, but compared the results which is on coco-test-dev in original paper.

@Laughing-q lol we are not on the same page... But yes I agree with you.
@zylo117 What's batch-nms? Any difference with class-wise nms?

**Comment by zylo117** [comment]
batched_nms is class-aware nms, while nms is class-agnostic nms.

**Comment by Laughing-q** [comment]
> > > > > yes
> > > > 
> > > > 
> > > > and i find that 51.8 on efficientdet-d7 is actually val2017's map in Original paper， 52.2 is test-dev's map.
> > > 
> > > 
> > > @Laughing-q You should be aware of what you are doing... clearly this is not a bug as far as I consider.
> > 
> > 
> > actually i just remind the author, the author's result is tested on coco-val2017, but compared the results which is on coco-test-dev in original paper.
> 
> @Laughing-q lol we are not on the same page... But yes I agree with you.
> @zylo117 What's batch-nms? Any difference with class-wise nms?

**Comment by Cli98** [comment]
Emmm I see. Good to hear that.
