### ISSUE TITLE
Attribute error of matplotlib projections

### ISSUE THREAD

**Issue by ChuyiZhong** [zylo117/Yet-Another-EfficientDet-Pytorch#275]
Hi all
First, thank the author for the great work.
I have been suffering from training my own dataset. When I rung the train.py, I got an error: 
AttributeError: module 'matplotlib' has no attribute 'projections'
I have re-installed the matplotlib but this error still exists. 
All help are appreciated. Thanks in advance.

**Comment by zylo117** [comment]
Please provide more info. I don't remember using matplotlib on this repo except the tutorial.
It could caused by implicitly import. I think updating matplotlib could help.

**Comment by ChuyiZhong** [comment]
> Please provide more info. I don't remember using matplotlib on this repo except for the tutorial.
> It could caused by implicitly import. I think updating matplotlib could help.

Hi, Thank you for your quick reply.
I am trying to use this network to train my own dataset. I followed all the steps but when I run the train.py, this error shows up.
![屏幕快照 2020-05-11 上午9 41 23](https://user-images.githubusercontent.com/37033044/81516820-d7d3ff00-936b-11ea-989f-9e33276881c3.jpg)
 All help are appreciated. Best regards.

**Comment by zylo117** [comment]
try updating matplotlib
`pip3 install matplotlib -U`

**Comment by ChuyiZhong** [comment]
> try updating matplotlib
> `pip3 install matplotlib -U`
Still exists. I have changed a new environment. Best regards.
