### ISSUE TITLE
should I retrain the model?

### ISSUE THREAD

**Issue by qtw1998** [zylo117/Yet-Another-EfficientDet-Pytorch#276]
as to `replace nms with batched_nms to further improve mAP by 0.5~0.7, thanks @Laughing-q.`?
is it necessary for me to train from scratch?
or just use the above when eval the model? thx !!

**Comment by zylo117** [comment]
no,  it's just post process

**Comment by qtw1998** [comment]
> no, it's just post process

THX !!
