### ISSUE TITLE
A question about your Conv2dStaticSamePadding

### ISSUE THREAD

**Issue by workingcoder** [zylo117/Yet-Another-EfficientDet-Pytorch#280]
In ‘Yet-Another-EfficientDet-Pytorch-master/efficientnet/utils_extra.py’, your Conv2dStaticSamePadding function doesn't consider the dilation parameter at all.

**Comment by zylo117** [comment]
yes, it doesn't. Because I'm lazy.
But considering this repo doesn't apply any dilated conv, so it doesn't matter.

**Comment by workingcoder** [comment]
OK. Maybe I'll write that by myself. Thank you.
