### ISSUE TITLE
anchor_scale anchor_ration

### ISSUE THREAD

**Issue by lijiaying-cell** [zylo117/Yet-Another-EfficientDet-Pytorch#290]
Hello,I want to konw how to produce anchor_scale and anchor_ration

**Comment by zylo117** [comment]
https://github.com/Cli98/anchor_computation_tool
But I haven't tried it yet.

**Comment by lijiaying-cell** [comment]
thank,you
anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
I want to know about whether the anchor_scale is based on the original image or the scaled image and anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]among it whether (1,1),(1.4,0.7),(0.7,1.4) represent 1:1,2:1,1:2

**Comment by lijiaying-cell** [comment]
@zylo117 
thank,you
anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
I want to know about whether the anchor_scale is based on the original image or the scaled image and anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]among it whether (1,1),(1.4,0.7),(0.7,1.4) represent 1:1,2:1,1:2

**Comment by zylo117** [comment]
1. it's relative scale, so it doesn't matter on original or scaled.
2. no, it's not equal.

**Comment by lijiaying-cell** [comment]
@zylo117
1.So，does that mean that the original image or proportion of my anchor is ok？
2.what do they[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)] represent

**Comment by zylo117** [comment]
1. yes
2. [*(w_scale, h_scale)]

**Comment by lijiaying-cell** [comment]
@zylo117
ok，thank you
