### ISSUE TITLE
HTTPerror for pretrained weights

### ISSUE THREAD

**Issue by Firdes** [zylo117/Yet-Another-EfficientDet-Pytorch#292]
I cannot download the pretrained weights for EfficientNET:
"....\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: The specified account is disabled."

**Comment by zylo117** [comment]
the original author changed their download urls

**Comment by Firdes** [comment]
Thank you very much for your quick reply. I used the pretrained weights by lukemelas/EfficientNet in your code but the results are completely wrong with the top 5 classification results being between 0.5 and 2%. Is the reason the tensorflow padding that you implemented?

**Comment by zylo117** [comment]
Do you mean you replace backbone' weights of my pretrained weights with the original effnet's weights?
If so, of course it won't work. The backbone is also been trained. What you did is basically to initialize the backbone weights randomly.
