### ISSUE TITLE
How to solve this evaluation problem

### ISSUE THREAD

**Issue by Aiz-wallenstein** [zylo117/Yet-Another-EfficientDet-Pytorch#299]
running coco-style evaluation on project coco, weights weights/efficientdet-d2.pth...
loading annotations into memory...
Done (t=11.92s)
creating index...
index created!
Traceback (most recent call last):
  File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 156, in <module>
    model.requires_grad_(False)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'EfficientDetBackbone' object has no attribute 'requires_grad_'

**Comment by zylo117** [comment]
Update torch to 1.4?

**Comment by Aiz-wallenstein** [comment]
thanks. I have solved this problem. but there has another new problem, 
just like this:
Traceback (most recent call last):
  File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 165, in <module>
    image_ids = evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
  File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 65, in evaluate_coco
    ori_imgs, framed_imgs, framed_metas = preprocess(image_path, max_size=input_sizes[compound_coef])
  File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in preprocess
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
  File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in <listcomp>
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by zylo117** [comment]
img path not valid or corrupt img

**Comment by wumy27** [comment]
> thanks. I have solved this problem. but there has another new problem,
> just like this:
> Traceback (most recent call last):
> File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 165, in
> image_ids = evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
> File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 65, in evaluate_coco
> ori_imgs, framed_imgs, framed_metas = preprocess(image_path, max_size=input_sizes[compound_coef])
> File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in preprocess
> normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
> File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in
> normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
> TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

How do you solve it? Could you tell me?

**Comment by Aiz-wallenstein** [comment]
> > thanks. I have solved this problem. but there has another new problem,
> > just like this:
> > Traceback (most recent call last):
> > File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 165, in
> > image_ids = evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
> > File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 65, in evaluate_coco
> > ori_imgs, framed_imgs, framed_metas = preprocess(image_path, max_size=input_sizes[compound_coef])
> > File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in preprocess
> > normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
> > File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in
> > normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
> > TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
> 
> How do you solve it? Could you tell me?

img path not valid

**Comment by wumy27** [comment]
thx！I have solved it.&nbsp;

--------------原始邮件--------------
发件人："Aiz-wallenstein "<notifications@github.com&gt;;
发送时间：2020年6月10日(星期三) 晚上6:52
收件人："zylo117/Yet-Another-EfficientDet-Pytorch" <Yet-Another-EfficientDet-Pytorch@noreply.github.com&gt;;
抄送："wumy27 "<wumy27@mail2.sysu.edu.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [zylo117/Yet-Another-EfficientDet-Pytorch] How to solve this evaluation problem (#299)
-----------------------------------

 

   
thanks. I have solved this problem. but there has another new problem,
 just like this:
 Traceback (most recent call last):
 File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 165, in
 image_ids = evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
 File "D:/PytorchCodeProject/Object detection project/Yet-Another-EfficientDet-Pytorch-master/coco_eval.py", line 65, in evaluate_coco
 ori_imgs, framed_imgs, framed_metas = preprocess(image_path, max_size=input_sizes[compound_coef])
 File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in preprocess
 normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
 File "D:\PytorchCodeProject\Object detection project\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 67, in
 normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
 TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
  
How do you solve it? Could you tell me?
  
img path not valid
