### ISSUE TITLE
how much epochs?

### ISSUE THREAD

**Issue by mjanddy** [zylo117/Yet-Another-EfficientDet-Pytorch#3]
Hi,I want to konw  how much epochs you train that can get a good result?

**Comment by zylo117** [comment]
lost count already, I have tried countless combinations. How about I tell you my training and tuning time?

3 months.

**Comment by Ernie1** [comment]
> But don't be afraid, this is try-error time, if you really need to train coco from scratch, 80 epochs will be enough

Does 'train coco from scratch' you mentioned need ImageNet pretrained weights for backbone or just random initialization?

**Comment by zylo117** [comment]
> > But don't be afraid, this is try-error time, if you really need to train coco from scratch, 80 epochs will be enough
> 
> Does 'train coco from scratch' you mentioned need ImageNet pretrained weights for backbone or just random initialization?

Training on a pretrained backbone. 

But even if you have a imagenet-pretrained efficientnet, you still need weeks to train a efficientdet, on multiple gpus of course. If you try to a train a bigger net like D5/D6, it takes more time.

So training on coco from scratch just not worth it, considering there are already pretrained weights. Also training on other custom dataset works just fine.

Guys, stop doing that, you are wasting electricity and your life.

**Comment by ryusaeba** [comment]
@Ernie1 and  Are you able to train from scratch for COCO dataset? I have this question since I would like to do some pruning study on it. The hyper-parameter is important to me. 
Or @zylo117 could you please share the command for D0 to D2 with me?
