### ISSUE TITLE
Centering the image in Resizer

### ISSUE THREAD

**Issue by mnslarcher** [zylo117/Yet-Another-EfficientDet-Pytorch#306]
Hi @zylo117,

in https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/0b16c7c2194970ccdee843099322024bff8a9636/efficientdet/dataset.py#L110

Wouldn't it be better to center the image or it's indifferent?

instead of:
```
new_image = np.zeros((self.img_size, self.img_size, 3))
new_image[0:resized_height, 0:resized_width] = image

annots[:, :4] *= scale
```
something like:
```
height_margin = (self.img_size - resized_height) // 2
width_margin = (self.img_size - resized_width) // 2
new_image = np.zeros((self.img_size, self.img_size, 3))
new_image[height_margin :height_margin + resized_height, width_margin : + width_margin resized_width] = image
annots[:, :4] *= scale
annots[:, -4] += width_margin
annots[:, -3] += height_margin 
```

Thanks,
M

**Comment by zylo117** [comment]
That's my original resizing method actually. But since the weights are at first transferred from the official repo, which applies upper-left corner alignment instead of centering resizing, it'd be better to keep it the original resizing way.

**Comment by mnslarcher** [comment]
Thanks, make sense!
