### ISSUE TITLE
RuntimeError: Source tensor must be contiguou

### ISSUE THREAD

**Issue by Hesene** [zylo117/Yet-Another-EfficientDet-Pytorch#31]
`Source tensor must be contiguous.
[Error] Traceback (most recent call last):
  File "/home/effdet/train.py", line 221, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/home/anaconda3/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/python3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/effdet/utils/utils.py", line 183, in scatter
    for device_idx in range(len(devices))], \
  File "/home/effdet/utils/utils.py", line 183, in <listcomp>
    for device_idx in range(len(devices))], \
RuntimeError: Source tensor must be contiguous.`
Hi, Thanks for your code, when I train on single GPU, it runs well, but when I run on two GPU, the error happen, Could you give me some advice, thank you

**Comment by Hesene** [comment]
I solve it to change 'model = CustomDataParallel(model, params.num_gpus)' as 'model = torch.nn.DataParallel(model)',

**Comment by zylo117** [comment]
It's weird, I ran on 4 gpus and 1 gpu, and everything is ok.

**Comment by Hesene** [comment]
> It's weird, I ran on 4 gpus and 1 gpu, and everything is ok.

Maybe because my torch version is 1.1, if I change 'model = CustomDataParallel(model, params.num_gpus)' to 'model = torch.nn.DataParallel(model)', does this cause any problems?

**Comment by zylo117** [comment]
....come on, update it to 1.4
DP is slow and will cause data loading inbalance, so the process will be slow, but customdp won't

**Comment by Hesene** [comment]
> ....come on, update it to 1.4
> DP is slow and will cause data loading inbalance, so the process will be slow, but customdp won't

OK, Thank you very much
