### ISSUE TITLE
anchor ratio number

### ISSUE THREAD

**Issue by wenjun90** [zylo117/Yet-Another-EfficientDet-Pytorch#310]
Hi @zylo117 ,

I would like to ask you the number of achor_ratio influence to the precision of prediction of object bbox?

For example: ratio_number = 9 can be more accuracy ratio_number = 3. If number = 9, time of prediction is more long?

Thank you

**Comment by zylo117** [comment]
1. I am not sure adding more ratios will inprove performance, at least it's not certain.
2. yes, it will be slower

**Comment by Cli98** [comment]
> * I am not sure adding more ratios will inprove performance, at least it's not certain.
> * yes, it will be slower

It's not. I have tested it.
