### ISSUE TITLE
insufficient shared memory

### ISSUE THREAD

**Issue by HaolyShiit** [zylo117/Yet-Another-EfficientDet-Pytorch#317]
**Hello, thanks for your great work!**
**Whatever I change the 'num_workers' or  'batch_size',  error occurs as follows:**
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
RuntimeError: DataLoader worker (pid 6230) is killed by signal: Bus error.

**I add a line to the code to specify the GPU number:**
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

How to solve the problem? Thank you.

**Comment by zylo117** [comment]
You can't solve it without adding more RAM to your server or reducing num_workers or batchsize

**Comment by HaolyShiit** [comment]
> You can't solve it without adding more RAM to your server or reducing num_workers or batchsize

Thans for your advice. 
I tried to set 'batchsize = 4' and 'num_workers = 1', and it worked. 
The GPU  memory is about 12G, and it only takes 1157 M for training. When I add 'batchsize ',  same error occurs.
Is that normal?

**Comment by HaolyShiit** [comment]
> You can't solve it without adding more RAM to your server or reducing num_workers or batchsize

Hello, maybe I solved the problem. I reduce 'num_workers' to 0, and 'batchsize' can be added to 32 or more. 
Thans for your great work again!

**Comment by merisgong208** [comment]
I think there maybe a bug here. For a 6GB gpu can only load one  num_workers and batchsize 4 ?  It eats too much.

**Comment by zylo117** [comment]
num workers have nothing to do with gpu mem, batchsize does. But using larger batchsize or num_workers, it consumes more system memory, which in my experience, lots of servers are lack of.
