### ISSUE TITLE
Image channel order dismatch between training and testing.

### ISSUE THREAD

**Issue by HaolyShiit** [zylo117/Yet-Another-EfficientDet-Pytorch#325]
Hello, thanks for your great works.

I find channel order is RGB during training phase， while it becomes BGR when testing.
Is it normal? or I miss something？ 

When training, load image using cv2 and covert BGR to RGB:
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/6105867855d4df5d8085bbcadc37cc0f0fcca1e8/efficientdet/dataset.py#L49

When tesing, load image but without converting:
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/6105867855d4df5d8085bbcadc37cc0f0fcca1e8/utils/utils.py#L69

**Comment by zylo117** [comment]
img[..., ::-1] is the convertion

**Comment by HaolyShiit** [comment]
I got it! thanks!
