### ISSUE TITLE
size mismatch for classifier.header.pointwise_conv.conv.weight

### ISSUE THREAD

**Issue by backkon** [zylo117/Yet-Another-EfficientDet-Pytorch#329]
i got this warning:
size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([810, 160, 1, 1]) from checkpoint, the shape in current model is torch.Size([396, 160, 1, 1]).

why? i downloaded d3.path and i set the running config like this: 
-c 3 -p garbage --batch_size 4 --lr 1e-5 --num_epochs 10 -w path/efficientdet-d3.pth

**Comment by backkon** [comment]
i know it is because my num_classes is 44, so i wander is this warning matter? look forward to your reply!

**Comment by zylo117** [comment]
Training or inference?
there should be a heads-up tells you not to panic right after this warning in training.

**Comment by backkon** [comment]
Training. OK, i got it. Thank you very much!

**Comment by ProBuro** [comment]
I got this error during detection. what to do with it?
size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([810, 112, 1, 1]) from checkpoint, the shape in current model is torch.Size([126, 112, 1, 1]).
	size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([810]) from checkpoint, the shape in current model is torch.Size([126]).
