### ISSUE TITLE
很夸张的问题

### ISSUE THREAD

**Issue by syg1996419** [zylo117/Yet-Another-EfficientDet-Pytorch#336]
我租了8块Gpu 88g 为什么跑d5还跑不起来啊,有人指点一下吗？

**Comment by pierrelzw** [comment]
> 我租了8块Gpu 88g 为什么跑d5还跑不起来啊,有人指点一下吗？

Finetuning d5 cost almost 19G when batch=1. The number of GPU is not crucial but RAM of each GPU is, since the code is run in DataParalle mode. Using GPU with RAM>19G, it'll be fine, like P40 or V100.

**Comment by syg1996419** [comment]
非常感谢你的回答！
