### ISSUE TITLE
datesets中的label计算？

### ISSUE THREAD

**Issue by shenjun1994** [zylo117/Yet-Another-EfficientDet-Pytorch#344]
好像在datasets中，annotation[0, 4] = a['category_id'] - 1并不能得到连续的从0-79的值，而是(1-90）-1，不知道这样对classfier训练是否有影响？

**Comment by zylo117** [comment]
isn't that from 0 to 89? There are 90 classes in this pretained weights.

**Comment by shenjun1994** [comment]
sorry，以为你会把coco中空类别给去了，只保留80类，没想到你是全部算成了类别，我代入了平常使用coco数据集的固有想法了
