### ISSUE TITLE
Some questions about weight initialize

### ISSUE THREAD

**Issue by LittleBoy7** [zylo117/Yet-Another-EfficientDet-Pytorch#35]
![image](https://user-images.githubusercontent.com/40973234/79068139-42efce80-7cf7-11ea-9e84-50744388aea6.png)
Sorry, my own dataset has more class numbers than COCO , so I want to initialize the last layer's weight and bias , but I can't find the initial codes in the project.Please tell me how to initialize the last weight and bias like scratch.Thank you！！！！！！

**Comment by zylo117** [comment]
You don't need to change anything. The program itself will load every weights except the last one if shape doesn't match

check out here.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/train.py#L143

I've told you guys don't panic...

**Comment by LittleBoy7** [comment]
Thanks ,I know. But I have some questions about your code. If we use the pretrained models, the last classifier is initialized as this way:
![image](https://user-images.githubusercontent.com/40973234/79070448-856dd700-7d08-11ea-99f0-ee894f2f80a1.png)
But if we train our models from scratch,we initialize our model in Kaiming_normal , why use Kaiming_normal rather than the first way ? Thank you !!!!!

**Comment by zylo117** [comment]
oh, this is just some old code, I shall remove this part later.
