### ISSUE TITLE
Total loss: 0.23068 means 23.068% or 0.23068%？

### ISSUE THREAD

**Issue by dapsjj** [zylo117/Yet-Another-EfficientDet-Pytorch#358]
My console outputs such information：
`Step: 39434. Epoch: 77/500. Iteration: 473/506. Cls loss: 0.22619. Reg loss: 0.00448. Total loss: 0.23068:  93%|████████████████████████████████████████████████`
Total loss: 0.23068 means loss 23.068% or  loss 0.23068%？

**Comment by zylo117** [comment]
loss is just loss, not a percentage
