### ISSUE TITLE
fps question

### ISSUE THREAD

**Issue by zuop-star** [zylo117/Yet-Another-EfficientDet-Pytorch#359]
thanks for your work.I run your efficientdet_test.py on colab,the gpu is
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    59W / 149W |   8395MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
but efficientdet d2 FPS is around 8-9,it is normal？the following is result：
running speed test...
test1: model inferring and postprocessing
inferring image for 10 times...
0.11743831634521484 seconds, 8.515108451150288 FPS, @batch_size 1

**Comment by zylo117** [comment]
K80 is a grandpa gpu with weak performance. And its cuda compute capability is too outdated that torch might not has optimizations for.

**Comment by zuop-star** [comment]
I also run efficientdet_test.py on my own computer，and my gpu is GTX 1650，the gpu memory is only 4 GB，the result is  similar to colab result，and why ？maybe K80 is simular to GTX 1650？and I have no idea about that@zylo117

**Comment by zylo117** [comment]
1650 is not as fast as k80, not even close, but colab runs on jupyter, which is basically on python debug, which slows down the processing.
however 1650 supports newer cuda compute capability, so it's hard to judge which is faster on different platform.
But one thing for sure, they are both slow.
