### ISSUE TITLE
您好我想请问一下这个mAP是在COCO2017还是coco2014上算出来的？

### ISSUE THREAD

**Issue by SpursLipu** [zylo117/Yet-Another-EfficientDet-Pytorch#36]
还有就是confidence用的是多少？

**Comment by zylo117** [comment]
coco2017 val.
there is no need to set confidence threshold, the cocoapi will deal with it.

**Comment by SpursLipu** [comment]
Do you konw how the cocoapi to deal with confidence threshold?
