### ISSUE TITLE
为什么感觉效果要差点

### ISSUE THREAD

**Issue by CCxiaoLL** [zylo117/Yet-Another-EfficientDet-Pytorch#362]
大佬你好，我下载的D7模型权重，为啥测试效果这么差，是我哪里没有弄对嘛
![img_inferred_d7_this_repo_0](https://user-images.githubusercontent.com/43843359/83475959-0a33d080-a4c2-11ea-8058-ca8e6dd97534.jpg)

**Comment by zylo117** [comment]
it seems good to me.
you should run coco_eval to get a standard result instead of inferring random images.
