### ISSUE TITLE
custom dataset train problem

### ISSUE THREAD

**Issue by Aiz-wallenstein** [zylo117/Yet-Another-EfficientDet-Pytorch#380]
I use my custom dataset and when run train.py I have met some problems, can you give me some advice. thanks！

loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
[Info] initializing weights...
Step: 5. Epoch: 0/2. Iteration: 6/6. Cls loss: 35.12099. Reg loss: 0.21101. Total loss: 35.33200: 100%|██████████| 6/6 [17:09<00:00, 171.54s/it]
D:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Val. Epoch: 0/2. Classification loss: nan. Regression loss: nan. Total loss: nan
D:\Anaconda3\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Step: 9. Epoch: 1/2. Iteration: 4/6. Cls loss: 43.92271. Reg loss: 0.07100. Total loss: 43.99371:  67%|██████▋   | 4/6 [10:28<05:16, 158.12s/it]checkpoint...
Step: 11. Epoch: 1/2. Iteration: 6/6. Cls loss: 50.72665. Reg loss: 0.00000. Total loss: 50.72665: 100%|██████████| 6/6 [15:37<00:00, 156.25s/it]
Val. Epoch: 1/2. Classification loss: nan. Regression loss: nan. Total loss: nan
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.

Process finished with exit code 0

**Comment by zylo117** [comment]
duplicated.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/357
