### ISSUE TITLE
Image size of custom dataset

### ISSUE THREAD

**Issue by SadiaAfrinPurba** [zylo117/Yet-Another-EfficientDet-Pytorch#381]
Hello, 

Thank you for the amazing codebase. I have a query regarding image size of the custom dataset. In **shape** dataset all images were 512x512.
Is it mandatory or can I have any size of images?

**Comment by zylo117** [comment]
Either switch to a larger network, or modify here.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/train.py#L121
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/train.py#L126

**Comment by SadiaAfrinPurba** [comment]
@zylo117 thank you.

**Comment by MosesBomera** [comment]
Hi, I know this is closed but I have images of size 400 x 400, can I modify the input_sizes and add 400 to it without breaking the code?

**Comment by zylo117** [comment]
> Hi, I know this is closed but I have images of size 400 x 400, can I modify the input_sizes and add 400 to it without breaking the code?

Modify these lines. There are several of them. Replace the image size of the corresponding coefficients.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/train.py#L117

**Comment by MosesBomera** [comment]
Thanks @zylo117 for the timely reply. I added 400 to input_sizes
` input_sizes = [400, 512, 640, 768, 896, 1024, 1280, 1280, 1536]` and I am using `-c 0`  but now I am getting a runtime error that says: **The size of tensor a (7) must match the size of tensor b (8) at non-singleton dimension 3**

**Comment by zylo117** [comment]
maybe there are more lines that needs to be modified
