### ISSUE TITLE
running under Win10 system

### ISSUE THREAD

**Issue by wusheng816** [zylo117/Yet-Another-EfficientDet-Pytorch#382]
I run the "efficientdet_test.py" file without any modification under Win10 system, and got a result named "img_inferred_d0_this_repo_0.jpg". However, it's a far cry from the result shown in "img_inferred_d0_this_repo.jpg". Can it runs effectively under Win10 systtem?

**Comment by wusheng816** [comment]
set "force_input_size = 1920"

**Comment by zylo117** [comment]
It'd be better if you can run it on linux.
Torch is much slower on win and num_workers must be 0 if training on win, which is way slower.

**Comment by wusheng816** [comment]
So it is, but win10 is more friendly to newers. Thank you!

> BTW. It'd be better if you can run it on linux.
> Torch is much slower on win and num_workers must be 0 if training on win, which is way slower.
