### ISSUE TITLE
Unable to import self-made COCO dataset

### ISSUE THREAD

**Issue by JiaLim98** [zylo117/Yet-Another-EfficientDet-Pytorch#384]
Hi zylo117,

First of all, I would like to thank you for the outstanding word you shared here.

I have succesfully trained the shape dataset provided in the tutorial. Now, I have my own dataset which has images of size 600x600. I just changed replaced all the images and annotation files with mine and did not rename the filenames. However, I am getting this error:
![image](https://user-images.githubusercontent.com/66768413/84352083-40bec900-abef-11ea-801b-2ade1e073868.png)
These are the changes I made to suit my dataset:
1. Added input size of 600 in the array (in any files that have the array)
2. Changed labels in the project file (shape.yml)
The difference between the datasets is that my filename is a string (e.g. spurious_copper.jpg) but the shape dataset is is numbers (e.g. 999.jpg). Does that affect the model to import the data?

I am suspecting the dataset is not imported, that's why it is divided by zero. Can you help with this issue? or can you list down the changes I have to make to the model to suit my dataset?
I am new to deep learning, please help. Thanks in advance!

Regards,
JiaLim98

**Comment by zylo117** [comment]
1. image_size is not a problem.
2. check dataset's image ids, I think it has to be int instead of str.

**Comment by JiaLim98** [comment]
Hi Zylo117,

I have changed all my filenames to int and the properties in the annotation files as well. However, I am still getting the same error. Are there any possibilities that can cause the num_iter_per_epoch to be zero?

I noticed another thing different about my json file and the shapes json file. My dataset don't have segmentation, is that a possible cause for this issue?

Regards,
JiaLim98

**Comment by JiaLim98** [comment]
Hi Zylo117,

I have managed to get the training started using my own dataset. It's a minor problem in the annotation file. I coded the 'id' wrongly. It had'nt finish training yet, but I think there won't be any problem after that.
Thank you so much for the help. Looking forward to better implementation of EfficientDet!

Regards,
JiaLim98
