### ISSUE TITLE
cocoeval.py出错

### ISSUE THREAD

**Issue by MichealZwen** [zylo117/Yet-Another-EfficientDet-Pytorch#394]
![IMG_5037](https://user-images.githubusercontent.com/37389563/84739130-a63efb00-afdd-11ea-9654-df94bee21693.JPG)

**Comment by MichealZwen** [comment]
请问一下应该怎么修改呀

**Comment by zylo117** [comment]
check FAQ Q5

**Comment by JiaLim98** [comment]
如果您不想要换numpy的版本的话。您可以跟着它给您的文件路径找到function_base.py之后修改：
第117和121行的’num‘加上’int()'就可以了。
比如（第117行）：
num = operator.index(num) 变成 num = operator.index(int(num))

不建议那么做如果其他地方有使用这个文件。如果您只有这个项目，可以这么做。
