### ISSUE TITLE
How to Make my datasets?

### ISSUE THREAD

**Issue by qingHX** [zylo117/Yet-Another-EfficientDet-Pytorch#402]
I   just know use labelimg to get xml，may i have some guide to get json and others

**Comment by Derekabc** [comment]
@qingHX  DO you get the tool to do this?

**Comment by qingHX** [comment]
@Derekabc No,I do not get the tool,just i am asked to  do another task.
But I reall want the tool to try the code on my datasets

**Comment by zylo117** [comment]
it xml voc style annotation? try voc2coco.
