### ISSUE TITLE
runtimeError: cuda out of memory.

### ISSUE THREAD

**Issue by Aiz-wallenstein** [zylo117/Yet-Another-EfficientDet-Pytorch#407]
when I run train.py I got this problem. And I set num_gpus to1 in the coco.yml , of course I have tried other number, and didn't work. And my gpu is absolute enough. I want to know whether there are something wrong with my setup? Thanks!

`RuntimeError: CUDA out of memory. Tried to allocate 204.00 MiB (GPU 0; 11.00 GiB total capacity; 8.26 GiB already allocated; 111.45 MiB free; 8.63 GiB reserved in total by PyTorch) (malloc at ..\c10\cuda\CUDACachingAllocator.cpp:289)
(no backtrace available)
`

**Comment by zylo117** [comment]
reduce batchsize or try smaller network like d0

**Comment by Aiz-wallenstein** [comment]
thanks!
