### ISSUE TITLE
Any plan of EfficientDet-lite

### ISSUE THREAD

**Issue by soyebn** [zylo117/Yet-Another-EfficientDet-Pytorch#41]
You might be aware that TPU  model repo has published lite versions of efficientnet w/o the following three features as they are not well supported for some mobile accelerators.
1. No Squeeze-and-excite (SE): 
2. Swish (replace with RELU6) 
3. Fix the stem and head while scaling models up: for keeping models small and fast. 
https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/lite

I think it will be quite a value if you modify your code to include EfficientDet-lite which uses EfficientNet-lIte.
So my humble question, do you have any plan for this?

**Comment by zylo117** [comment]
You know how google does, they always create something oneday and deny them the other day.

Only when they publish effdet-lite and prove its mAP is high enough with considerable speed, would I consider port effdet-lite to this repo.
