### ISSUE TITLE
Where to find the 'weights/efficientdet-d0.pth' ?

### ISSUE THREAD

**Issue by cccccccccy** [zylo117/Yet-Another-EfficientDet-Pytorch#418]
Sorry to disturb , just a simple problem. When I run the Demo python efficientdet_test.py , then there is a error:
FileNotFoundError: [Errno 2] No such file or directory: 'weights/efficientdet-d0.pth'
I look the library , but not find the weight.

**Comment by zylo117** [comment]
you can download the weights from release page of this repo.
