### ISSUE TITLE
要想训练D7的网络

### ISSUE THREAD

**Issue by zhuangxinfa** [zylo117/Yet-Another-EfficientDet-Pytorch#421]
要想训练D7的网络八个2080Ti也会报显存不足的错误

**Comment by zylo117** [comment]
there is only 11g each in rtx2080ti. In general, training takes at least 3 times memory usage larger than inference, so I don't think training D7 on 2080ti is possible without using model parallel.

**Comment by zhuangxinfa** [comment]
> there is only 11g each in rtx2080ti. In general, training takes at least 3 times memory usage larger than inference, so I don't think training D7 on 2080ti is possible without using model parallel.
