### ISSUE TITLE
Unable to convert pretrained models to TensorRT 

### ISSUE THREAD

**Issue by HtutLynn** [zylo117/Yet-Another-EfficientDet-Pytorch#425]
Hi. Thanks for the great work! Since EfficientDet is really efficient and has better accuracy compared to deployment networks like MobileNets, I've been trying to convert EfficientDet pretrained models to TensorRT model to quantize and deploy on edge devices like Jetson xavier nx, nano with Nvidia DeepStream.

**TensortRT conversion process**
Pytorch pretrained model => ONNX model => TensorRT

I was able to convert the efficientdet models to ONNX by modifying some of the source code.
**ONNX conversion method** : [method](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/111#issuecomment-657422226)

When I try to convert ONNX model obtained by aforementioned conversion method, this kind of error occurs.
```
Input filename: EfficientDet0_1.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:   pytorch
Producer version: 1.5
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
[07/16/2020-12:04:11] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/16/2020-12:04:11] [W] [TRT] onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
ERROR: builtin_op_importers.cpp:2179 In function importPad:
[8] Assertion failed: inputs.at(1).is_weights()

```
As far as I understand, when this kind of error occurs, we have to fix some part of the model, which is not supported by TensorRT. But I am totally clueless on how and where to modify it.

**environment info**:
OS version : Ubuntu 18.04
python        : 3.6.9
Pytorch      : 1.5
Cuda          : 10.2
Cudnn        : 8.0.1
TensorRT   : 7.1

Any clue on where to modify/fix?

**Comment by chaseliutb** [comment]
Mark, same question

**Comment by xizi** [comment]
step 1: set opset_version=10
step 2: modification Conv2dStaticSamePadding and MaxPool2dStaticSamePadding, add cast int, for examle: x = F.pad(x, [int(left), int(right), int(top), int(bottom)])
step3: replace Upsample op,  use size not shape

**Comment by HtutLynn** [comment]
@xizi Thanks for the reply. I tried the steps as you described but still can't convert to TensorRT model. 

> step3: replace Upsample op, use size not shape

As for step3, I implemented a static_upsample function and substituted the torch.nn.Upsample function in the original code. The implemented is as described here. [issue](https://github.com/onnx/onnx-tensorrt/issues/361#issuecomment-576004279) but still no luck. The error message changed a lil bit but this error still persists.
```
Input filename:   EfficientDet1_1.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.5
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
[09/16/2020-13:27:45] [W] [TRT] [TRT]/home/htut/Desktop/onnx-tensorrt/onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/16/2020-13:27:45] [W] [TRT] [TRT]/home/htut/Desktop/onnx-tensorrt/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
While parsing node number 19 [Pad]:
ERROR: /home/htut/Desktop/onnx-tensorrt/builtin_op_importers.cpp:2219 In function importPad:
[8] Assertion failed: inputs.at(1).is_weights()
[09/16/2020-13:27:45] [E] Failed to parse onnx file
[09/16/2020-13:27:45] [E] Parsing model failed
[09/16/2020-13:27:45] [E] Engine creation failed
[09/16/2020-13:27:45] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec --onnx=EfficientDet1_1.onnx --saveEngine=efficientdet-b1.trt --workspace=1024 --fp16
```
Can you please provide the complete solution?
Thanks in advance!

**Comment by xizi** [comment]
> @xizi Thanks for the reply. I tried the steps as you described but still can't convert to TensorRT model.
> 
> > step3: replace Upsample op, use size not shape
> 
> As for step3, I implemented a static_upsample function and substituted the torch.nn.Upsample function in the original code. The implemented is as described here. [issue](https://github.com/onnx/onnx-tensorrt/issues/361#issuecomment-576004279) but still no luck. The error message changed a lil bit but this error still persists.
> 
> ```
> Input filename:   EfficientDet1_1.onnx
> ONNX IR version:  0.0.6
> Opset version:    11
> Producer name:    pytorch
> Producer version: 1.5
> Domain:           
> Model version:    0
> Doc string:       
> ----------------------------------------------------------------
> [09/16/2020-13:27:45] [W] [TRT] [TRT]/home/htut/Desktop/onnx-tensorrt/onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> [09/16/2020-13:27:45] [W] [TRT] [TRT]/home/htut/Desktop/onnx-tensorrt/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
> While parsing node number 19 [Pad]:
> ERROR: /home/htut/Desktop/onnx-tensorrt/builtin_op_importers.cpp:2219 In function importPad:
> [8] Assertion failed: inputs.at(1).is_weights()
> [09/16/2020-13:27:45] [E] Failed to parse onnx file
> [09/16/2020-13:27:45] [E] Parsing model failed
> [09/16/2020-13:27:45] [E] Engine creation failed
> [09/16/2020-13:27:45] [E] Engine set up failed
> &&&& FAILED TensorRT.trtexec # trtexec --onnx=EfficientDet1_1.onnx --saveEngine=efficientdet-b1.trt --workspace=1024 --fp16
> ```
> 
> Can you please provide the complete solution?
> Thanks in advance!

use opset_version=10

**Comment by HtutLynn** [comment]
@xizi Sorry, I kinda copied the wrong output. Here is the error message that I got when I try to use the opset_version=10 onnx model. 

```
----------------------------------------------------------------
Input filename:   EfficientDet1_1.onnx
ONNX IR version:  0.0.6
Opset version:    10
Producer name:    pytorch
Producer version: 1.5
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
[09/16/2020-13:44:42] [W] [TRT] [TRT]/home/htut/Desktop/onnx-tensorrt/onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 1552 [Constant]:
ERROR: /home/htut/Desktop/onnx-tensorrt/ModelImporter.cpp:533 In function importModel:
[7] Assertion failed: _importer_ctx.tensors().at(output.name()).is_tensor()
[09/16/2020-13:44:42] [E] Failed to parse onnx file
[09/16/2020-13:44:42] [E] Parsing model failed
[09/16/2020-13:44:42] [E] Engine creation failed
[09/16/2020-13:44:42] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec --onnx=EfficientDet1_1.onnx --saveEngine=efficientdet-b1.trt --workspace=1024 --fp16
```

**Comment by xizi** [comment]
change forward funtion in backbone.py like this and do nms out of the convert model
def forward(self, inputs):
        #max_size = inputs.shape[-1]

        _, p3, p4, p5 = self.backbone_net(inputs)
        
        features = (p3, p4, p5)
        features = self.bifpn(features)

        regression = self.regressor(features)
        classification = self.classifier(features)
        anchors = self.anchors(inputs, inputs.dtype)
        transformed_anchors = self.regressBoxes(anchors, regression)

        scores = torch.max(classification, dim=2)[0]
        index = torch.topk(scores, 500, dim=1)[1]
        
       scores_topk = torch.index_select(classification, 1, index[0])
        boxes_topk = torch.index_select(transformed_anchors, 1, index[0])
        return scores_topk, boxes_topk

**Comment by HtutLynn** [comment]
> change forward funtion in backbone.py like this and do nms out of the convert model
> def forward(self, inputs):
> #max_size = inputs.shape[-1]
> 
> ```
>     _, p3, p4, p5 = self.backbone_net(inputs)
>     
>     features = (p3, p4, p5)
>     features = self.bifpn(features)
> 
>     regression = self.regressor(features)
>     classification = self.classifier(features)
>     anchors = self.anchors(inputs, inputs.dtype)
>     transformed_anchors = self.regressBoxes(anchors, regression)
> 
>     scores = torch.max(classification, dim=2)[0]
>     index = torch.topk(scores, 500, dim=1)[1]
>     
>    scores_topk = torch.index_select(classification, 1, index[0])
>     boxes_topk = torch.index_select(transformed_anchors, 1, index[0])
>     return scores_topk, boxes_topk
> ```

Thanks! It finally works. This's been bugging me for some months. Can you please shed some light on why that last error keeps happening? The reason why we typecast those values from `.shape` is to make it static in model conversion, not dynamic. But I am not really sure about the last error.

**Comment by xizi** [comment]
nms mismatch

**Comment by HtutLynn** [comment]
> nms mismatch

Thanks!

**Comment by HtutLynn** [comment]
@xizi , Hi, I was able to convert the model by using your steps and modifications and implemented a wrapper class to inference TensorRT model in python. But the bboxes and classification scores are kinda of a mess and the outputs are not similar at all to onnx's or original pytorch's outputs.

TensorRT conversion command
```
trtexec --onnx=EfficientDet1_1.onnx --saveEngine=efficientdet-b1.trt --workspace=1024  --fp16
```
Inferred outputs, from TensorRT model.
```
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[   0.         0.      -168.29146  639.     ]
[51.316734 59.37576  51.684196 61.268375] # really small boxes
[86.254005 12.537356 86.41398  13.171189] 
[33.763493 16.730536 34.9826   24.787699]
```
I also checked the inferred outputs of Onnx model and Pytorch model from modified codes to be extra sure but results are correct as expected. Only the results from TensorRT models are horribly wrong.
Am I still missing something or did you get the same issue?

**Comment by xizi** [comment]
> @xizi , Hi, I was able to convert the model by using your steps and modifications and implemented a wrapper class to inference TensorRT model in python. But the bboxes and classification scores are kinda of a mess and the outputs are not similar at all to onnx's or original pytorch's outputs.
> 
> TensorRT conversion command
> 
> ```
> trtexec --onnx=EfficientDet1_1.onnx --saveEngine=efficientdet-b1.trt --workspace=1024  --fp16
> ```
> 
> Inferred outputs, from TensorRT model.
> 
> ```
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [   0.         0.      -168.29146  639.     ]
> [51.316734 59.37576  51.684196 61.268375] # really small boxes
> [86.254005 12.537356 86.41398  13.171189] 
> [33.763493 16.730536 34.9826   24.787699]
> ```
> 
> I also checked the inferred outputs of Onnx model and Pytorch model from modified codes to be extra sure but results are correct as expected. Only the results from TensorRT models are horribly wrong.
> Am I still missing something or did you get the same issue?

you need do score filter and nms after model forward

**Comment by HtutLynn** [comment]
> > @xizi , Hi, I was able to convert the model by using your steps and modifications and implemented a wrapper class to inference TensorRT model in python. But the bboxes and classification scores are kinda of a mess and the outputs are not similar at all to onnx's or original pytorch's outputs.
> > TensorRT conversion command
> > ```
> > trtexec --onnx=EfficientDet1_1.onnx --saveEngine=efficientdet-b1.trt --workspace=1024  --fp16
> > ```
> > 
> > 
> > Inferred outputs, from TensorRT model.
> > ```
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [   0.         0.      -168.29146  639.     ]
> > [51.316734 59.37576  51.684196 61.268375] # really small boxes
> > [86.254005 12.537356 86.41398  13.171189] 
> > [33.763493 16.730536 34.9826   24.787699]
> > ```
> > 
> > 
> > I also checked the inferred outputs of Onnx model and Pytorch model from modified codes to be extra sure but results are correct as expected. Only the results from TensorRT models are horribly wrong.
> > Am I still missing something or did you get the same issue?
> 
> you need do score filter and nms after model forward

@xizi Thanks for the reply! The output numpy array, that I just posted is the result after score filtering and nms. It seems to be that output TensorRT model, converted from the working ONNX model is totally wrong. Here is an inferred example by using TensorRT model.

![Uploading truth.jpg…](inferred image)

If it is possible, can you please share the repo that you've modified and wrapper, used to inference for TensorRT? I've been trying to deploy this on Jetson Xavier NX and stuck at this state for quite some time. My email is : htutlynnaung.cs@gmail.com. Thanks in advance!

**Comment by HtutLynn** [comment]
> you need do score filter and nms after model forward
Hi,  @xizi, the output numpy array is the result after score filtering and nms but it seems to be the there was a bug in my tensorrt model wrapper implementation.

And I kinda found the bug.
```
normalized_img = (img / 255 - mean) / std
img_meta = _aspectaware_resize_padding(image=img, width=input_shape, height=input_shape,
                                                                      interpolation=None, means=None)
```
In `_preprocess` function of my wrapper, the input data wasn't normalized so that's the reason why model is outputting garbage values. `img` was passed to padding function instead of `normalized_img`. That was the main cause of the garbage values.

Thanks for the help!

**Comment by chuanhao01** [comment]
Hi, I am not sure if this issue still has activity but I followed what @HtutLynn did for the ONNX conversion, however some of the code did not match up already especially the one shown above:  

> change forward funtion in backbone.py like this and do nms out of the convert model
> def forward(self, inputs):
> #max_size = inputs.shape[-1]
> 
> ```
>     _, p3, p4, p5 = self.backbone_net(inputs)
>     
>     features = (p3, p4, p5)
>     features = self.bifpn(features)
> 
>     regression = self.regressor(features)
>     classification = self.classifier(features)
>     anchors = self.anchors(inputs, inputs.dtype)
>     transformed_anchors = self.regressBoxes(anchors, regression)
> 
>     scores = torch.max(classification, dim=2)[0]
>     index = torch.topk(scores, 500, dim=1)[1]
>     
>    scores_topk = torch.index_select(classification, 1, index[0])
>     boxes_topk = torch.index_select(transformed_anchors, 1, index[0])
>     return scores_topk, boxes_topk
> ```

For mine it looks like: (In `backbone.py`)
```python
    def forward(self, inputs):
        max_size = inputs.shape[-1]

        _, p3, p4, p5 = self.backbone_net(inputs)

        features = (p3, p4, p5)
        features = self.bifpn(features)

        regression = self.regressor(features)
        classification = self.classifier(features)
        anchors = self.anchors(inputs, inputs.dtype)

        return features, regression, classification, anchors
```
I managed to get the model to convert to ONNX but I had these warnings while doing so:
(I noticed that they were just ints, so I changed them to integers, I think this is where the error came from as wel)

```
./yaed/efficientnet/utils_extra.py:44: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h = ht.item()
./yaed/efficientnet/utils_extra.py:45: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w = wt.item()
./yaed/efficientnet/utils_extra.py:102: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h = ht.item()
./yaed/efficientnet/utils_extra.py:103: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w = wt.item()
./yaed/efficientdet/utils.py:111: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if image_shape[1] % stride != 0:
./yaed/efficientdet/utils.py:117: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x = np.arange(stride / 2, image_shape[1], stride)
./yaed/efficientdet/utils.py:117: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x = np.arange(stride / 2, image_shape[1], stride)
./yaed/efficientdet/utils.py:118: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  y = np.arange(stride / 2, image_shape[0], stride)
./yaed/efficientdet/utils.py:118: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  y = np.arange(stride / 2, image_shape[0], stride)
./yaed/efficientdet/utils.py:134: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  anchor_boxes = torch.from_numpy(anchor_boxes.astype(dtype)).to(image.device)
```
Lastly, when I tried using `trtexec --onnx=./efficientdet-d4.onnx --maxBatch=1 --saveEngine=./efficientdet-d4.trt --fp16 --verbose` to convert I got this error:  

```
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Slice_8 [Slice] inputs: [1487 -> (-1, 2)], [1489 -> (1)], [1490 -> (1)], [1488 -> (1)], [1491 -> (1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:141: Registering layer: Slice_8 for ONNX node: Slice_8
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:116: Registering tensor: 1492 for ONNX tensor: 1492
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: Slice_8 [Slice] outputs: [1492 -> (-1, -1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: Transpose_9 [Transpose]
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1492
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Transpose_9 [Transpose] inputs: [1492 -> (-1, -1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:141: Registering layer: Transpose_9 for ONNX node: Transpose_9
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:116: Registering tensor: 1493 for ONNX tensor: 1493
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: Transpose_9 [Transpose] outputs: [1493 -> (-1, -1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: Constant_10 [Constant]
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Constant_10 [Constant] inputs: 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: Constant_10 [Constant] outputs: [1494 -> (1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: Reshape_11 [Reshape]
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1493
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1494
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Reshape_11 [Reshape] inputs: [1493 -> (-1, -1)], [1494 -> (1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:141: Registering layer: Reshape_11 for ONNX node: Reshape_11
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:116: Registering tensor: 1495 for ONNX tensor: 1495
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: Reshape_11 [Reshape] outputs: [1495 -> (-1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: Cast_12 [Cast]
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1495
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Cast_12 [Cast] inputs: [1495 -> (-1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/builtin_op_importers.cpp:320: Casting to type: int32
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:141: Registering layer: Cast_12 for ONNX node: Cast_12
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:116: Registering tensor: 1496 for ONNX tensor: 1496
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: Cast_12 [Cast] outputs: [1496 -> (-1)], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: Constant_13 [Constant]
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Constant_13 [Constant] inputs: 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: Constant_13 [Constant] outputs: [1497 -> ()], 
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: Pad_14 [Pad]
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: data
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1496
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1497
[09/22/2020-10:02:40] [V] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: Pad_14 [Pad] inputs: [data -> (1, 3, 512, 512)], [1496 -> (-1)], [1497 -> ()], 
While parsing node number 14 [Pad -> "1498"]:
--- Begin node ---
input: "data"
input: "1496"
input: "1497"
output: "1498"
name: "Pad_14"
op_type: "Pad"
attribute {
  name: "mode"
  s: "constant"
  type: STRING
}

--- End node ---
ERROR: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/builtin_op_importers.cpp:2219 In function importPad:
[8] Assertion failed: inputs.at(1).is_weights()
[09/22/2020-10:02:40] [E] Failed to parse onnx file
[09/22/2020-10:02:40] [E] Parsing model failed
[09/22/2020-10:02:40] [E] Engine creation failed
```

Any help is appreciated :D

**Comment by wiekern** [comment]
Taking so many tries, finally, I convert the onnx model to tensorrt model successfully by using [to-onnx](https://github.com/murdockhou/Yet-Another-EfficientDet-Pytorch-Convert-ONNX-TVM.git) and [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt.git).
I modified the converting script of git repo `Yet-Another-EfficientDet-Pytorch-Convert-ONNX-TVM`, all you could see in the figure below. Be careful, the opset_version is 10, other parameters can be configured according to your need, e.g. the number of classes is 1 in my case.
![modified converting script](https://user-images.githubusercontent.com/3865455/131097303-4ca66950-01a2-44c2-9395-e1710871e125.png)

![successfully converting message](https://user-images.githubusercontent.com/3865455/131098000-0a700b38-ffea-4302-a660-bbc3ff72e287.png)
