### ISSUE TITLE
Train COCO2014 Dataset with noWeighted Feature Fusion

### ISSUE THREAD

**Issue by cccccccccy** [zylo117/Yet-Another-EfficientDet-Pytorch#446]
if I want to Train the Coco2014 Dataset with no  Weighted Feature Fusion to verify how the Weighted Feature Fusion works ， what should  I to input in CMD？

**Comment by zylo117** [comment]
set `attention` to False.
https://github.com/zylo117/Yet-Another-EfficientDet-
Pytorch/blob/c533bc2de65135a6fe1d25ca437765c630943afb/backbone.py#L43

**Comment by cccccccccy** [comment]
> set `attention` to False.
> https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/c533bc2de65135a6fe1d25ca437765c630943afb/backbone.py#L43

Thank you very much!
