### ISSUE TITLE
The results of d7 on the picture of  "img.png" is not better than d0 ?

### ISSUE THREAD

**Issue by xscjun** [zylo117/Yet-Another-EfficientDet-Pytorch#45]
Thanks for your great work .  
I run the model of d7 and d0 with the code efficientdet_test.py ,  the result of d7  is no better than d4, and the d4 is no better than d0 ?  Is this reasonable ？

**Comment by zylo117** [comment]
emmmmmmmm....

Result of one image doesn't mean anything. You need to run coco_eval to test mAP/mAR

**Comment by xscjun** [comment]
> emmmmmmmm....
> 
> Result of one image doesn't mean anything. You need to run coco_eval to test mAP/mAR

Ok，I ‘ll run it on coco dataset,thanks
