### ISSUE TITLE
RuntimeError: Trying to create tensor with negative dimension

### ISSUE THREAD

**Issue by JiaLim98** [zylo117/Yet-Another-EfficientDet-Pytorch#452]
Hi @zylo117 

I am training EfficientDet-D7 at the moment and below is the issue I faced. I am able to run from D0 to D4 but after that. The same problem (as below) occurred.
![image](https://user-images.githubusercontent.com/66768413/88507019-fb732100-d00d-11ea-9fb8-a2f6e287ec3e.png)
I have read through #225 and [this](https://github.com/pytorch/vision/issues/1705). You mentioned in #225 that there are two possible solutions.

I have tried to increase the threshold [here](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientdet/loss.py#L174) from 0.5 to 0.8 with increment of 0.1 but the same error occurred. 

What I want to ask is that how do I 'implement pytorch nms or numpy nms by manipulating tensor/array to do nms.' I am new to object detection and hope that you can tell me more about this.

PS: I am training with a batch size of 8 (CUDA will run out of memory more than that) on 2 NVIDA Tesla P-100.
 
Best regards,
JiaLim98

**Comment by zylo117** [comment]
oh I mean stricter nms threshold, like 0.1.
I think this is caused by too many boxes. Try running without debugging.
If you insist on debugging, try training with lighter model like d0, d1 and when you can handle it, switch to heavier models.

**Comment by JiaLim98** [comment]
@zylo117 What actually does --debug do? Just 'whether to visualize the predicted boxes of training' only or there are other effects on the model training? This is because I can run with --debug with model like d0, d1 to d4.

**Comment by zylo117** [comment]
just visualizing the training. It's not necessary and very slow.

**Comment by JiaLim98** [comment]
@zylo117 Now I am training without debugging. It works fine. Thank you so much.
One question though. Can I use the computed loss to determine the convergence of the model? If not, How do one know that the model has converged?
