### ISSUE TITLE
order of preprocessing

### ISSUE THREAD

**Issue by SeongwoongJo** [zylo117/Yet-Another-EfficientDet-Pytorch#453]
in your code, you set the order of the preprocessing as the following order; Normalize, Augment, Resize

is this an general way ? 
I know that generally normalization is the last step of preprocessing.
so, my question is, why don't you use the order of Resize -> Augment -> Normalize ??

**Comment by zylo117** [comment]
when resizing, the program will pad 0 to the make the images square. If the padding are being normalize, it will be non-zeros and I don't want that.

**Comment by SeongwoongJo** [comment]
@zylo117 SInce i am new to detection problem, I have one more question. Resize with conserving aspect ratio is general way in detection problem? 
In many cls problem, They don't consider aspect ratio, but fill entire space with image by interpolation

**Comment by zylo117** [comment]
It's just a style and it's hard to judge which one of these methods is more superior.

**Comment by SeongwoongJo** [comment]
@zylo117 i see. 
And i have a separate question from the above. where is the image' scale(in the Resizer class) used? is it just for the reference?

**Comment by zylo117** [comment]
It's deprecated for now.
