### ISSUE TITLE
efficientdet_test.py for test pictures are not good enough, see more detail for attachment

### ISSUE THREAD

**Issue by ald2004** [zylo117/Yet-Another-EfficientDet-Pytorch#455]
i used one machine for gpu, another not,
and i am not very good at efficientnet can you help me out, 
mean while i wish to have a look this repo performance and train a project.
thanks.
![img_inferred_d0_this_repo_0](https://user-images.githubusercontent.com/4443533/88633077-1a91b180-d0e7-11ea-90e6-b8e5c608bc19.jpg)
![img_inferred_d8_this_repo_0](https://user-images.githubusercontent.com/4443533/88633082-1cf40b80-d0e7-11ea-8717-5363310d00bb.jpg)

**Comment by ald2004** [comment]
the first picture is result for d0, and the second is for d8(d7x),
d8 is absoulety good than d0, but they have the same problem which 
is for a litter bit center left there is a crowd riding motor bike but d0 or d8
does not see them.
and right upper have the same problem, what did i miss?

**Comment by ald2004** [comment]
omg,
force_input_size = 1920 
worked for me after look several pages of issues ,
thanks, good job.
btw,fist i set force_input_size on 1060  got some error,
change to v100 it ok...
thanks again.

**Comment by ald2004** [comment]
File "/home/smoke_effici/efficientdet/model.py", line 293, in _forward
    p7_up = self.conv7_up(self.swish(p7_in + self.p7_upsample(p8_in)))
RuntimeError: The size of tensor a (15) must match the size of tensor b (16) at non-singleton dimension 3


no,got error again, must be a bug, i try to figure it out myself, 
have same problem like this try to change force_input_size and compound_coef to different value,
there must be a good match wait for me to find out.

**Comment by zylo117** [comment]
The width and height must be 32 dividable. For example, 1920/32=60, so it's ok, but 1920/32=60.03125, it's not.

**Comment by NoviceCrom** [comment]
> The width and height must be 32 divisible. For example, 1920/32=60, so it's ok, but 1921/32=60.03125, it's not.

I meet the same problem here using 256*256 pics processed from 1280*720 (RuntimeError: The size of tensor a (15) must match the size of tensor b (16) at non-singleton dimension 3), is there any solutions?
