### ISSUE TITLE
efficientdet backbone is different from efficientnet

### ISSUE THREAD

**Issue by SeongwoongJo** [zylo117/Yet-Another-EfficientDet-Pytorch#467]
In your code, you directly use efficientnet as backbone.
However, in the official paper, efficientdet's efficientnet reduces the resolution until 2^7 while the original efficientnet reduces the resolution until 2^5

I think this difference lead to the trade off between speedup and performance

**Comment by zylo117** [comment]
Can you share the references about that efficientnet reduces the resolution until 2^5?

**Comment by SeongwoongJo** [comment]
<img width="347" alt="스크린샷 2020-08-06 오후 4 39 52" src="https://user-images.githubusercontent.com/35558061/89504764-879df900-d803-11ea-87eb-09d1c8166e7e.png">

**Comment by SeongwoongJo** [comment]
224/2^5 = 7

**Comment by zylo117** [comment]
I see.
It's a misunderstanding.
EfficientDet's efficientnet reduces resolution to 1/2^5 as well. But then efficientdet continues reducing it to 1/2^7.

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/c533bc2de65135a6fe1d25ca437765c630943afb/efficientdet/model.py#L120

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/c533bc2de65135a6fe1d25ca437765c630943afb/efficientdet/model.py#L125

**Comment by SeongwoongJo** [comment]
@zylo117 I see. thanks
