### ISSUE TITLE
数据集图片的尺寸问题

### ISSUE THREAD

**Issue by SakuraMaxuetao** [zylo117/Yet-Another-EfficientDet-Pytorch#476]
请问我数据集里的图片都需要是正方形并且大小统一成[512, 640, 768, 896, 1024, 1280, 1280, 1536]里的某一项吗？

**Comment by zylo117** [comment]
No, the program will resize them to square and to the target size.

**Comment by SakuraMaxuetao** [comment]
如果程序自动调整图片大小，不会影响到标注框在图片上的位置吗？
