### ISSUE TITLE
Custom dataset reg loss big

### ISSUE THREAD

**Issue by WangBoying** [zylo117/Yet-Another-EfficientDet-Pytorch#481]
@zylo117 ,the tutorial can't work as expected! When I use my own data, the loss is particularly large.

**Comment by WangBoying** [comment]
![image](https://user-images.githubusercontent.com/15812564/90340858-8bb0ee80-e02d-11ea-89de-9fd051b2741a.png)

**Comment by WangBoying** [comment]
![image](https://user-images.githubusercontent.com/15812564/90340867-979cb080-e02d-11ea-88e7-e5aaf3b27ad9.png)

**Comment by zylo117** [comment]
Did you mean the tutorial can't work or the program can't work on your dataset?

**Comment by WangBoying** [comment]
I follow the steps of the tutorial, but loss is very large. Please look at the picture above.

**Comment by zylo117** [comment]
By the end of the tutorial, mAP should be 0.7, which is good enough.
