### ISSUE TITLE
efficientdet_test.py cpu 错误

### ISSUE THREAD

**Issue by x12901** [zylo117/Yet-Another-EfficientDet-Pytorch#485]
File "efficientdet_test.py", line 61
    model.load_state_dict(torch.load(f'weights/efficientdet-d{compound_coef}.pth', map_location='cpu'))
                                                                                ^
SyntaxError: invalid syntax
操作环境是ubuntu18    pytorch-cpu 1.6.0     torchvision 0.7.0

**Comment by freshn** [comment]
@x12901 Same here. Have you solved it?

**Comment by zylo117** [comment]
f-string is supported since python 3.6
