### ISSUE TITLE
运行coco_eval.py出错

### ISSUE THREAD

**Issue by xumeng19** [zylo117/Yet-Another-EfficientDet-Pytorch#52]
![image](https://user-images.githubusercontent.com/50445749/79113536-b7884300-7db3-11ea-9b94-46b893b45626.png)
作者你好，我在运行coco_eval.py报了这个错误，请问怎么解决？

**Comment by skylineJLU** [comment]
eval和train 的-c参数是一样的吗

**Comment by xumeng19** [comment]
感谢，我调成一样后可以了

**Comment by skylineJLU** [comment]
> 感谢，我调成一样后可以了

哈哈 没事

**Comment by zylo117** [comment]
how can you load d0's weights into d5's model?
