### ISSUE TITLE
having error with negative tensor dimension

### ISSUE THREAD

**Issue by kimalaacer** [zylo117/Yet-Another-EfficientDet-Pytorch#521]
I trained my own dataset on efficientdet D7, and saved my model in logs folder.
my folder structure is:
coco:
----train:
--------01.jpg
----val:
--------30.jpg
-----annotation:
-------instances_val.json

my cmd: !python coco_eval.py -c 7 -p rare_event_detection_COCOdataset -w logs/rare_event_detection_COCOdataset/{weight_file[-1]}

Error: 
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
  0%|                                                    | 0/11 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "coco_eval.py", line 159, in <module>
    evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
  File "coco_eval.py", line 83, in evaluate_coco
    threshold, nms_threshold)
  File "/home/jupyter/my-bucket/Yet-Another-EfficientDet-Pytorch/utils/utils.py", line 109, in postprocess
    anchors_nms_idx = batched_nms(transformed_anchors_per, scores_per[:, 0], classes_, iou_threshold=iou_threshold)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1600, in wrapper
    return compiled_fn(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 82, in batched_nms
        offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
        boxes_for_nms = boxes + offsets[:, None]
        keep = nms(boxes_for_nms, scores, iou_threshold)
               ~~~ <--- HERE
        return keep
  File "/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 40, in nms
        by NMS, sorted in decreasing order of scores
    """
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: Trying to create tensor with negative dimension -1242957280: [-1242957280]


do you have any suggestions on how to troubleshoot or fixit?

**Comment by zylo117** [comment]
I have seen these issue a couple of times, the number of boxes is too many so that the nms algorithm of pytorch fails. 
Try raising the threshold so that there are less boxes or train the model for a little bit longer, though I don't suggest training D7 because it's too heavy for most of the tasks.

raising the threshold (but it will lower the mAP):
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/acb2c691e1220448d41527b3e3b5c56206d8fd70/coco_eval.py#L159
add extra argument `threshold=0.1` or higher if you like.

**Comment by kimalaacer** [comment]
Thanks, 
I added the argument and used 0.2 and 0.1, still same error. 
I will retrain with high number of epochs, and see. 
I am trying to detect microscopic bacteria, i was hoping this will help.

**Comment by kimalaacer** [comment]
Thanks, 
I think the problem was that i was training with only 5 epoch and very low learning rate. 
Once i trained it with 50 epochs, i stopped receiving errors. 
also from your comment in coco_eval.py: 

"""
COCO-Style Evaluations
put images here datasets/your_project_name/annotations/val_set_name/*.jpg
put annotations here datasets/your_project_name/annotations/instances_{val_set_name}.json
put weights here /path/to/your/weights/*.pth
change compound_coef
"""

I think your second line comment should be changed:
FROM: put images here datasets/your_project_name/annotations/val_set_name/*.jpg
TO: put images here datasets/your_project_name/val_set_name/*.jpg
