### ISSUE TITLE
make prediction box size with fixed dimensions

### ISSUE THREAD

**Issue by kimalaacer** [zylo117/Yet-Another-EfficientDet-Pytorch#533]
I Was able to train a model based on D0 and D7. 
My object to be detected is very small, single class,  and will never exceed 40 * 10, 10 * 40, 7 * 7 pixels in size. 

Now, the prediction boxes are accurate in detecting the object, however, they cover 75% of the input image. 
is there a way to force a prediction box to a max size of 40 * 40 pixel? 

Thanks,

**Comment by zylo117** [comment]
I don't think such small objs like that can be detected easily with this method. By default, the smallest anchor is 32x32, across d0 to d7, which is way bigger that your objs. So it will be hard to regression.

**Comment by kimalaacer** [comment]
Thanks. 
much appreciate your help.
