### ISSUE TITLE
到freezed backbone就停了

### ISSUE THREAD

**Issue by fatandfat** [zylo117/Yet-Another-EfficientDet-Pytorch#534]
windows，单gpu，head only=true运行train.py每次到freezed backbone程序就停止了，也不报错，把num_gpus设成0就可以正常运行出step

**Comment by zylo117** [comment]
Cant train on windows with num worker greater than 0

**Comment by fatandfat** [comment]
> num

确实设的是0

**Comment by fatandfat** [comment]
> Cant train on windows with num worker greater than 0

确实设的是0

**Comment by zylo117** [comment]
train with `--num_worker 0` in windows

**Comment by fatandfat** [comment]
> train with `--num_worker 0` in windows

It worked, thanks! May I ask the difference between setting default value of num_workers to 0 in train.py and setting it by using --num_workers=0？

**Comment by zylo117** [comment]
same

**Comment by fatandfat** [comment]
With head_only=true and lr=1e-5, after 50 epochs, I got ap=-1, should I lower the lr or keep training？![20201028_184411.jpg](https://user-images.githubusercontent.com/59509491/97425892-aec11e00-194d-11eb-9490-7191c2f87856.jpg)![20201028_184435.jpg](https://user-images.githubusercontent.com/59509491/97425904-b1bc0e80-194d-11eb-986c-9c9e17fa83ec.jpg)![20201028_184451.jpg](https://user-images.githubusercontent.com/59509491/97425906-b2ed3b80-194d-11eb-8bdf-95fe16008cd5.jpg)
