### ISSUE TITLE
Empty predictions

### ISSUE THREAD

**Issue by mesguerraf** [zylo117/Yet-Another-EfficientDet-Pytorch#535]
Hello, I'm trying to train the model on a custom dataset and after running for over 100 epochs, I get empty predictions on the evaluation set. There does not seem to be any overfitting as both train and eval losses go down. I adapted the anchors, mean, and std to fit my dataset but still no predictions. I'm trying to detect 1 type of object which is only present in a small fraction of the data (450 out of 1500) and it is small (32x32p). Should I then train the model only on images with the object present? And if this is the case, is there a way to deal with the model predicting too many false positives?

**Comment by zylo117** [comment]
The smallest anchor is 32 by default, so it will be quite hard to train. And if you mean the objects are 32p before resizing to a standard resolution that your network requires, they are almost impossible to be detected.

**Comment by mesguerraf** [comment]
I see! Thanks for your answer. The objects are indeed 32p before resizing unfortunately.
