### ISSUE TITLE
Can I train my datasets without the part 'segmentation'

### ISSUE THREAD

**Issue by Surayuth** [zylo117/Yet-Another-EfficientDet-Pytorch#540]
My annotation format looks like this

{'id': 5, 'image_id': 0, 'category_id': 1, 'bbox': [155, 46, 26, 37], 'area': 962, 'segmentation': [], 'iscrowd': 0}

Is it possible to train this dataset without the 'segmentation' part?

**Comment by quangduyhcmut** [comment]
Yes. 'Segmentation' is for segmentation task. Coco format just is for many task such as detection and segmentation :)

**Comment by Surayuth** [comment]
> Yes. 'Segmentation' is for segmentation task. Coco format just is for many task such as detection and segmentation :)

Nice, thank you very much.
