### ISSUE TITLE
found a bug in the code

### ISSUE THREAD

**Issue by poirotZhu** [zylo117/Yet-Another-EfficientDet-Pytorch#544]
when the loss is zero or inf, you choose to skip the backward and continue;
`if loss == 0 or not torch.isfinite(loss):
                        continue`
it may cause out of memory. You need to delet the graph before you start the next batch.
`if loss == 0 or not torch.isfinite(loss):
   del loss,cls_loss,reg_loss
                        continue`

**Comment by zylo117** [comment]
You are right about the oom risks.
But I think what should be really deleted is the grad buffer of the whole model.
What about this?
```
if loss == 0 or not torch.isfinite(loss):
    loss.backward()
    optimizer.zero_grad()
    continue
```

**Comment by poirotZhu** [comment]
yes, that's more elegant
