### ISSUE TITLE
模型推理后的图片为什么颜色有差异？

### ISSUE THREAD

**Issue by HsLOL** [zylo117/Yet-Another-EfficientDet-Pytorch#552]
我使用的是efficientdet-d0.pth，在网上随便找一张图想看一下模型的效果，结果发现测试的图片和原图的色彩发生了变化，这是怎么回事呢？

这个是原图
![image](https://user-images.githubusercontent.com/53011009/100186184-7c8ce700-2f20-11eb-8388-781982fd55b3.png)

这个是运行后的图片
![image](https://user-images.githubusercontent.com/53011009/100186221-96c6c500-2f20-11eb-9272-2bf14593122c.png)

谢谢回复~

**Comment by zylo117** [comment]
use `display` function instead.
You've transformed original bgr image to rgb

**Comment by HsLOL** [comment]
@zylo117  感谢您的回复。

 我从网上下载的图片的格式应该是RGB的，下载下来的代码也没有进行更改，作者大大用邮件回复使用display将其进行转换，这个是在代码里呢？还是需要我将推理的图片自己用函数进行转换成RGB格式呢？

谢谢回复~

**Comment by SSJIACV** [comment]
> 
> 
> @zylo117 感谢您的回复。
> 
> 我从网上下载的图片的格式应该是RGB的，下载下来的代码也没有进行更改，作者大大用邮件回复使用display将其进行转换，这个是在代码里呢？还是需要我将推理的图片自己用函数进行转换成RGB格式呢？
> 
> 谢谢回复~

utils/utils.py 中的preprocess函数写的有点问题，把里面的代码稍改一下就行

**Comment by HsLOL** [comment]
@SSJIACV  感谢您的回复。

**Comment by zylo117** [comment]
@SSJIACV 请问是哪里有问题？

**Comment by SSJIACV** [comment]
> 
> 
> @SSJIACV 请问是哪里有问题？

ori_imgs的RGB顺序被转换了，所以display的时候，保存下来的图和原图有色彩差别

**Comment by zylo117** [comment]
@SSJIACV @HsLOL it's fixed. https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/47f6bf3ccc118fbc2057112c507f419ff3e6e275
