### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone

### ISSUE THREAD

**Issue by jerryWTMH** [zylo117/Yet-Another-EfficientDet-Pytorch#557]
Thanks for your amazing work of EfficientDet!

When I used my training weight (efficientdet-d0_299_105500.pth) to run the coco_eval.py, I got an error like the image below:
![Screenshot from 2020-12-07 15-42-54](https://user-images.githubusercontent.com/30337005/101323190-3b42f280-38a3-11eb-8400-f432837a79b5.png)
I've searched for the Issues in this repo(#121 #389 ), but I still cannot find the proper solution.
Does anybody has found the solution?

**Comment by jerryWTMH** [comment]
detail information:
num_classes: 2
I run the "visualization" in the tutorial: https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/tutorial/train_shape.ipynb, my weight file (efficientdet-d0_299_105500.pth) could be loaded properly and the result looks like this:
![Figure_1](https://user-images.githubusercontent.com/30337005/101324953-f2d90400-38a5-11eb-932a-303ce66e31e4.png)

**Comment by rvandeghen** [comment]
You have to remove the last layer of convolution in your classifier subnet as the number of classes is not the same.
This can be achieved by popping that layer from the state dict:
```
state_dict = ... # load your weights for example with torch.utils.model_zoo.load_url('your_url')
state_dict.pop('classifier.header.pointwise_conv.conv.weight')
state_dict.pop('classifier.header.pointwise_conv.conv.bias')
model.load_state_dict(state_dict, strict=False)
```
Another solution is to use a `try except` decorator https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/1b0fdfe65e366733639478766f2660ea853d13f0/train.py#L138

Hope it helps you

**Comment by zylo117** [comment]
just specify the arguments of your projects like this.
`-p
shape
-c
0
-w
logs/shape/xxx.pth`

**Comment by jerryWTMH** [comment]
Thanks for all of your replies, and I resolve my problem!
Here is the detailed process of debugging:
I tried to change my code like:
`model_test = torch.load(weights_path)
model_test.pop('classifier.header.pointwise_conv.conv.weight')
model_test.pop('classifier.header.pointwise_conv.conv.bias')
model.load_state_dict(model_test, strict=False)`
I ran the coco_eval.py, but it stopped at the `Loading and preparing results...`for a long time , and the vscode shut down.
I restarted the vscode and I found that my weight file wasn't loaded properly (I gave the wrong weights_path......)
I fix the wrong weights_path and ran the code again, it shows another problem like:
`  File "coco_eval.py", line 174, in <module>
    _eval(coco_gt, image_ids, f'{SET_NAME}_bbox_results.json')
  File "coco_eval.py", line 133, in _eval
    coco_eval.evaluate()
  File "/home/iis/anaconda3/envs/efficientdet/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 158, in evaluate
    for catId in catIds
  File "/home/iis/anaconda3/envs/efficientdet/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 160, in <listcomp>
    for imgId in p.imgIds
  File "/home/iis/anaconda3/envs/efficientdet/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 255, in evaluateImg
    if g['ignore'] or (g['area']<aRng[0] or g['area']>aRng[1]):
KeyError: 'area'`
And then I found that #311 was the same problem, and this error showed that **my json file didn't contain the 'area' part!**
Thus, I rebuild my json file by adding the **'area'** and ran the coco_eval.py again and I finally got the AP scores!
