### ISSUE TITLE
A question about the efficientdet_test.py.

### ISSUE THREAD

**Issue by HsLOL** [zylo117/Yet-Another-EfficientDet-Pytorch#561]
when I feed a pic into the network, everytime the program(efficientdet_test.py)  will run successfuly, and get the results like these.

> running speed test...
> test1: model inferring and postprocessing
> inferring image for 10 times...
> 0.10408556461334229 seconds, 9.607480189157895 FPS, @batch_size 1

**But, sometimes the program will generate the pic in the test folder, but sometimes it will not generate pic in the test folder.**

the premise of the efficientdet_test.py generating the pic is the program can detect the instance in the pic?
If the program can't detect the instances in the image which i feed into the net, it will not generate the pic?

Is my understanding right? or the efficientdet_test.py has some restriction to the size of the input image?

Thank you for your answer!

**Comment by HsLOL** [comment]
hi @zylo117 
我加载了efficientdet-d4的预训练权重，用于训练我自己的数据集。但是将模型训练好的权重用于efficientdet_test.py却无法生成预测图片。如果我直接用efficientdet-d4预训练权重直接用于efficientdet_test.py是可以生成预测图片的。

您知道问题出在哪里吗？
感谢您的回复！

**Comment by zylo117** [comment]
It's possibly that your model is underfitting so no object was found and the picture will not be generated. AFAIK, d4 is probably not the best choice for production, because large networks like that always need more data to be trained.

**Comment by HsLOL** [comment]
> It's possibly that your model is underfitting so no object was found and the picture will not be generated. AFAIK, d4 is probably not the best choice for production, because large networks like that always need more data to be trained.

感谢您的回复~
那就是在efficientdet_test.py中，如果模型没有在输入图片中检测到目标的话，就不会产生图片了，是吗？

**Comment by zylo117** [comment]
是的。刚刚的公告更新，如果你愿意公开数据集，或者本来就是公开的，可以放上来，我有空可以帮你们训练。不过训练后的权值和评估成绩也会公开下载。如果你一直搞不定，我也许可以帮忙

**Comment by HsLOL** [comment]
感谢您的回复，我明白了!

刚入门目标检测（遥感图像的目标检测），如果过段时间还是没有效果的话，希望您可以帮我训练一下~
