### ISSUE TITLE
用efficientDet做wideface人脸检测 效果很差

### ISSUE THREAD

**Issue by sunbin1993** [zylo117/Yet-Another-EfficientDet-Pytorch#563]
用 D2 经过29000次迭代 sgd， 初始lr 1e-4 ，stride 8 16 32 64 128
Easy   Val AP: 0.919529110264566
Medium Val AP: 0.7974280848442119
Hard   Val AP: 0.3444215387400028

除了Easy勉强 其他两个指标明显不行

**Comment by zylo117** [comment]
确定收敛了？

**Comment by sunbin1993** [comment]
> 确定收敛了？

**Comment by sunbin1993** [comment]
> 确定收敛了？

嗯嗯 val loss最后在1.5左右

**Comment by zylo117** [comment]
1.5还挺高的。有空我试试

**Comment by sunbin1993** [comment]
> 1.5还挺高的。有空我试试

嗯嗯 多谢

**Comment by zylo117** [comment]
[widerfaces.zip](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/files/5732901/widerfaces.zip)
确实。我用的D0，用标准分辨率512，训练出来的也不好。
Easy   Val AP: 0.8668152398355771
Medium Val AP: 0.6695957079264405
Hard   Val AP: 0.3650382034197165

然后我把分辨率改成1024，然后就去到了
Easy   Val AP: 0.932285793420262
Medium Val AP: 0.9033339328736978
Hard   Val AP: 0.6267558365409147

考虑到不少widerfaces的数据的分辨率很高，甚至有去到了2500的，
所以提高分辨率的帮助很大，但是EfficientDet并不是特别轻的模型，加分辨率会不够显存的。
方向就是在足够轻型的网络上，提高分辨率，才能提高人脸检测效果

**Comment by zylo117** [comment]
改分辨率到了2048，现在去到了
Hard   Val AP: 0.7834877216417041

**Comment by sunbin1993** [comment]
好的，多谢提醒
