### ISSUE TITLE
为什么你比官方的运行速度快

### ISSUE THREAD

**Issue by 09876qwert** [zylo117/Yet-Another-EfficientDet-Pytorch#57]
你好，感谢你的工作，有一个问题想问一你，和官方版本相比较，为什么你的模型会快那么多呢，谢谢

**Comment by lintian06** [comment]
同疑惑。官方TF版本的EfficientDet-D0 (512) 是 _16ms_ [1]，Titan V GPU。你报告的数字0.713s = 713ms，2080Ti，比官方整整慢了一个数量级。

[1]: EfficientDet: Scalable and Efficient Object Detection. https://arxiv.org/pdf/1911.09070.pdf

**Comment by zylo117** [comment]
Yes, it's 16ms on the paper, but run at 200-300ms, 700 if it's complex image. It's not just me, The community also found out tf version is much slower

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/4#issuecomment-611337716

**Comment by ganchunsheng** [comment]
Thanks for you work, however, my test resut is "0.04858908653259277 seconds, 20.58075323826506 FPS, @batch_size 1", input_size 640 on nvidia p40, meanwhile, tf version result is "efficientdet-d0 16runs 0threads: mean 0.0173 std 0.0001 min 0.0172 max 0.0176"

**Comment by zylo117** [comment]
1. I use default image size, which is 512 if you are testing D0
2. My gpu is 2080Ti, which may explain why the result is different.
3. I ran this test a few days ago, tf effdet may have already modified its implement.
4. and it's not just me, the comunity also found out tf version is slower.

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/4#issuecomment-611337716
