### ISSUE TITLE
Scale Jittering

### ISSUE THREAD

**Issue by sandylaker** [zylo117/Yet-Another-EfficientDet-Pytorch#580]
Thanks for your great implementation. I have a question regarding the transforms in the dataset class. 

In the [paper](https://arxiv.org/pdf/1911.09070.pdf) (updated version), the authors applied scale jittering in range (0.1, 2.0) while training the detector, and showed that large scale jittering brought huge gain in mAP. However, in your implementation, there seems to be only resize and flip transforms. But you implementation acturally achieved very decent results on COCO dataset. 

Do you think the scale jittering is necessary? (P.S., [this implementation](https://github.com/rwightman/efficientdet-pytorch/blob/645d84a6f0cd837703f98f48179a06c354902515/effdet/data/transforms.py#L110) applied the large scale jittering too).

**Comment by zylo117** [comment]
Not really. Last time I checked, they didn't apply any augmentation but h-flipping until they trained D6/7.

**Comment by sandylaker** [comment]
> Not really. Last time I checked, they didn't apply any augmentation but h-flipping until they trained D6/7.

They updated the paper on arxiv, and in Appendix they illustrated the augmentation. D1 of the new version reached 40.2 mAP.

**Comment by zylo117** [comment]
Good to know. They really did a good job on it.
