### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 1224) exited unexpectedly

### ISSUE THREAD

**Issue by AshinWang** [zylo117/Yet-Another-EfficientDet-Pytorch#586]
[Info] freezed backbone
  0% 0/4227 [00:00<?, ?it/s]tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xda2ca000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
tcmalloc: large alloc 1179648000 bytes == 0xf1612000 @  0x7f1d6db481e7 0x7f1d6b654ca1 0x7f1d6b6b8be8 0x7f1d6b6b8d03 0x7f1d6b76d4ad 0x7f1d6b76de0e 0x7f1d6b770788 0x7f1d6b8b2a26 0x7f1d6b8b2f94 0x7f1d6b8b6f7a 0x7f1d6b8b7bbe 0x5a48ec 0x5a4fb8 0x7f1d6b7786ab 0x59c922 0x50cb2f 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01 0x59fd0e
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1224) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 326, in <module>
    train(opt)
  File "train.py", line 211, in train
    for iter, data in enumerate(progress_bar):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1224) exited unexpectedly
  0% 0/4227 [00:12<?, ?it/s]

**Comment by tnpan** [comment]
RuntimeError: DataLoader worker (pid 1224) is killed by signal: Killed.
-- I think you could try to down number of worker in train.py
like that: python train.py -n 0

**Comment by enchen22** [comment]
I am a newbie, so I dont sure exactly what I know, but you could try to down the number of workers to avoid this issue.
like that: python train.py -n 0 (and set other parameters)

**Comment by AshinWang** [comment]
Thanks! It turns out that the memory on Colab is limited.
