### ISSUE TITLE
detection   size mismatch for classifier.header.pointwise_conv.conv.weight

### ISSUE THREAD

**Issue by ProBuro** [zylo117/Yet-Another-EfficientDet-Pytorch#590]
I got this error during detection. what to do with it?
size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([810, 112, 1, 1]) from checkpoint, the shape in current model is torch.Size([126, 112, 1, 1]).
size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([810]) from checkpoint, the shape in current model is torch.Size([126]).

**Comment by zylo117** [comment]
just ignore it :)

**Comment by ProBuro** [comment]
colab is disabled. I am trying after learning to find objects on jpg of different sizes. An error pops up and no search occurs

**Comment by zylo117** [comment]
Then you passed the wrong obj list to the model. Can you share your modified code?

**Comment by ProBuro** [comment]
I trained on my dataset. i changed only .yml and file paths, weights

**Comment by ProBuro** [comment]
project_name: coc  # also the folder name of the dataset that under data_path folder
train_set: train_img
val_set: val_img
num_gpus: 1

# mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# this is coco anchors, change it if necessary
#anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
#anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(0.7, 1.4), (1.0, 1.0), (1.5, 0.7)]'

# must match your dataset's category_id.
# category_id is one_indexed,
# for example, index of 'car' here is 2, while category_id of is 3
obj_list: ['Aortic_enlargement',
            'Atelectasis',
            'Calcification',
            'Cardiomegaly',
            'Consolidation',
            'ILD',
            'Infiltration',
            'Lung_Opacity',
            'Nodule/Mass',
            'Other_lesion',
            'Pleural_effusion',
            'Pleural_thickening',
            'Pneumothorax',
            'Pulmonary_fibrosis']

**Comment by zylo117** [comment]
Then you loaded the wrong weights. You should load your weights instead of the coco weights.

**Comment by ProBuro** [comment]
I downloaded the weights from your repository. trained them and downloaded them
using your code to coco_ eval.py

**Comment by ProBuro** [comment]
Thank you. registered the path to the weights in coco_eval.py
