### ISSUE TITLE
Tensorboard issue

### ISSUE THREAD

**Issue by EricXuziang** [zylo117/Yet-Another-EfficientDet-Pytorch#595]
Thanks a lot for your work!
When I was trying to visualize loss using tensorboard, I entered the following command line.
tensorboard --logdir=logs/birdview_vehicles/tensorboard/
However, I can not open the https://localhost:6006/ on my browser. Do you know what's the problem?

Thx again!

**Comment by zylo117** [comment]
try 127.0.0.1 instead of localhost. And it's http, not htttps

**Comment by tuyendb** [comment]
> Thanks a lot for your work! When I was trying to visualize loss using tensorboard, I entered the following command line. tensorboard --logdir=logs/birdview_vehicles/tensorboard/ However, I can not open the https://localhost:6006/ on my browser. Do you know what's the problem?
> 
> Thx again!

Did u solve this issue. I have the same problem with you @@
