### ISSUE TITLE
how to create custom json?

### ISSUE THREAD

**Issue by kimtaehyeong** [zylo117/Yet-Another-EfficientDet-Pytorch#597]
Hello
I want to learn from my data.
The label format I have is as follows.

<pre>
<code>
{
    "1.png": [
        {
            "class": 41,
            "coord": [
                770,
                680,
                1013,
                1024
            ]
        },
        {
            "class": 42,
            "coord": [
                606,
                222,
                1044,
                578
            ]
        }
    ]
}
</pre>
</code>

I want to change the json file to fit the coco format.
What should I do ?

Thank you for your help.

**Comment by auniquesun** [comment]
Can you give some tips to custom coco format in a simple way?

Appreciate!
