### ISSUE TITLE
Anchors and scaling

### ISSUE THREAD

**Issue by Chrisguagliano** [zylo117/Yet-Another-EfficientDet-Pytorch#598]
Hi,

Thanks for your Pytorch implementation of EfficientDet!

I'm unsure if I'm using the anchors/scales correctly, but I tried to alter them and got awful performance compared to the anchors/scales you used on the birdview dataset.  I ran my custom dataset on an anchor/scale generation tool that utilizes kmeans.

I set the anchors/scales to the following:
anchors_scales: '[0.38362378, 0.08100172, 0.16681824]'
anchors_ratios: '[(1.28901734, 1), (1.075, 1), (1.23039773, 1)]'

Do you have any suggestions on how to optimize anchor scales/ratios?  None of the tools output the ratios in the same format as your implementation is expecting.

Thank you for your help!

**Comment by zylo117** [comment]
You shouldn't change anchor scale. 
And the performance depends on your dataset.

**Comment by Chrisguagliano** [comment]
Thank you for your quick response!

I tested my dataset using the default (birdview) anchors/scales and it gave reasonable performance.  The desire was to optimize these anchors (as it says in the yml) to increase performance.  If the scales are not changed, how would you suggest altering the ratios?

**Comment by zylo117** [comment]
I don't know what kind of tool you used to generate anchors. Do you have any link?

But if that tool does it right, take 0.08 as an example, the smallest anchor size is 4 * 8 * 0.08 = 2.56. So you have about one third small objects in 3 pixels? I have only a little confidence that this dataset can be trained well.

Secondly, you should understand how anchors are arranged. They are sliding windows  
that stick together. With no anchor scale closing to 1, meaning that there will be a lot of empty space without any anchor, then the targets will be missed.

**Comment by Chrisguagliano** [comment]
I found a couple repos for kmeans anchor analysis:

1. [https://github.com/joydeepmedhi/Anchor-Boxes-with-KMeans](https://github.com/joydeepmedhi/Anchor-Boxes-with-KMeans)
2. [https://github.com/siddharthgawas/iou-kmeans](https://github.com/siddharthgawas/iou-kmeans)
3. [https://github.com/mnslarcher/kmeans-anchors-ratios](https://github.com/mnslarcher/kmeans-anchors-ratios)
 
The first link is the repo I used to produce the anchors from my initial post.  I can use link 3 to get better ratios I believe.

The scales that I used are definitely wrong so I'm going to start with the birdview scales.  Do you have any suggestions on tuning the scaling?  Perhaps I could use the birdview scales and add a 4th scale for smaller objects?

**Comment by zylo117** [comment]
Just go with the default ones
