### ISSUE TITLE
KeyError: '2'

### ISSUE THREAD

**Issue by cendelian** [zylo117/Yet-Another-EfficientDet-Pytorch#60]
你好，我在训练自己的数据集的时候，报错如下：
    image_info = self.coco.loadImgs(self.image_ids[image_index])[0]
  File "/home/cendelian/anaconda3/envs/tf/lib/python3.6/site-packages/pycocotools/coco.py", line 229, in loadImgs
    return [self.imgs[id] for id in ids]
  File "/home/cendelian/anaconda3/envs/tf/lib/python3.6/site-packages/pycocotools/coco.py", line 229, in <listcomp>
    return [self.imgs[id] for id in ids]
**KeyError: '2'**

could you help me?

**Comment by zylo117** [comment]
dataset is corrupted

**Comment by cendelian** [comment]
> dataset is corrupted

你好，corrupted具体指什么呢？我按照您给的readme里面的步骤操作的，检查了几遍应该都OK。

谢谢！

**Comment by zylo117** [comment]
can you train on coco dataset? if so, then your dataset must be corrupted

**Comment by cendelian** [comment]
> can you train on coco dataset? if so, then your dataset must be corrupted

thanks. I have solved the problem.

the issue occur because the imagid of json is 'str' but not 'int'.
I changed the type of imageid to 'int' and i can train normally.
