### ISSUE TITLE
如何对efficientdet_test.py中anchor_ratios参数进行设置？

### ISSUE THREAD

**Issue by HsLOL** [zylo117/Yet-Another-EfficientDet-Pytorch#613]
hi @zylo117 感谢您的代码和tutorial！

在您repo中**efficientdet_test.py**中设置的anchor_ratios=[(1.0, 1.0), (1.5, 0.6), (0.7, 1.4)]。

而在repo/tutorial/**train_birdview_vehicles.ipynb**中设置的anchor_ratios=[(1.0, 1.0), (1.5, 0.6), (0.7, 1.4)]。

想请问一下，是如何针对遥感数据集的物体对anchor_ratios进行设置的呢？
我在issues中看到好像是通过kmeans聚类得到的。
如果是的话，不知道您能否将当时计算的代码发我一下？

谢谢！

**Comment by zylo117** [comment]
我都把人家大神的kmeans讨论置顶了啊
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/308

**Comment by HsLOL** [comment]
> 我都把人家大神的kmeans讨论置顶了啊
> #308

好嘞，感谢~
