### ISSUE TITLE
Number of feature levels from backbone to BiFPN

### ISSUE THREAD

**Issue by ilya-SX** [zylo117/Yet-Another-EfficientDet-Pytorch#617]
Hello.
I have a question regarding the number of feature elvels used in BiFPN. Am I missing something?

The original paper uses 5 feature levels from backbone as input to BiFPN (P3 - P7):
![image](https://user-images.githubusercontent.com/78141177/113509654-76a6b280-955f-11eb-8274-8068239f6a7c.png)

It is also clearly shown in the architecture figure:
![image](https://user-images.githubusercontent.com/78141177/113509673-9a69f880-955f-11eb-88c3-564b833ca996.png)

This implementation uses 3 levels (P3 - P5):

(forward of EfficientDetBackbone in backbone.py)
```
def forward(self, inputs):

        _, p3, p4, p5 = self.backbone_net(inputs)

        features = (p3, p4, p5)
        features = self.bifpn(features)

        regression = self.regressor(features)
        classification = self.classifier(features)
        anchors = self.anchors(inputs, inputs.dtype)

        return features, regression, classification, anchors
```

Is there a reason for that? What am I missing?
Thank you.

**Comment by ilya-SX** [comment]
I see now that the creation of P6 and P7 is made inside the first BiFPN.
Why isn't it a part of the backbone?
I would like to load a pretrained backbone only. In this case the last two feature layers will be calculated within the first BiFPN (which is not pretrained).
Thanks!

**Comment by zylo117** [comment]
Because the backbone doesn't have feature outputs like P6 and P7, so you have to make your own, with either conv or pooling

**Comment by ilya-SX** [comment]
> Because the backbone doesn't have feature outputs like P6 and P7, so you have to make your own, with either conv or pooling

Thanks!
