### ISSUE TITLE
Do I able to change input size of efficientDet D5 or something? 

### ISSUE THREAD

**Issue by ducnguyent** [zylo117/Yet-Another-EfficientDet-Pytorch#624]
I would like to know if I can change the parameter input size = 512 instead of 1280 for effDet D5?. Thanks

**Comment by zylo117** [comment]
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/fb9cd2466685d530a0860119fe980def35ff33e2/train.py#L112
change the resolution here

**Comment by zylo117** [comment]
But you might as well use d0 instead.
