### ISSUE TITLE
是否有百度云链接的预训练权重

### ISSUE THREAD

**Issue by noprohuangqi** [zylo117/Yet-Another-EfficientDet-Pytorch#63]
如题，麻烦了

**Comment by mad-fogs** [comment]
please add google drive link as well.

**Comment by HUHARED** [comment]
https://github.com/lukemelas/EfficientNet-PyTorch/releases

这个链接内的预训练权重和utils.py中的url_map_advprop是不是一样的？

**Comment by bzzonly** [comment]
链接：https://pan.baidu.com/s/1gUPTFqK3rA7dCUxKR_rEPg 密码：hrio

> 如题，麻烦了
