### ISSUE TITLE
Runtime Error: CUDA Memory issue for EfficientD0

### ISSUE THREAD

**Issue by Ashutosh1995** [zylo117/Yet-Another-EfficientDet-Pytorch#637]
I am trying to train to finetune the custom dataset using pretrained weights. I have Tesla P100 with 16 GB GPU memory. 

I am not able to train even the based D0 model and it breaks in between with the following error 

![image](https://user-images.githubusercontent.com/11408850/116433971-a0ee4600-a867-11eb-993f-990f558a51f1.png)

I am running the base command only 

python train.py -c 2 -p roadnet --batch_size 8 --lr 1e-3 --num_epochs 10 --load_weights weights/efficientdet-d0.pth

Could you please help?

**Comment by laplaceson** [comment]
I think you should use -c 0 , not sure if this is related.

**Comment by Ashutosh1995** [comment]
@laplaceson I used -c 0 also, but I am seeing the code fails with the following error at random locations during training.

![image](https://user-images.githubusercontent.com/11408850/116520853-e4d95d80-a8f0-11eb-83f6-9d5b47438003.png)


I am not able to debug this since the image when I load using python shell using cv2.imread is present there.

**Comment by zylo117** [comment]
the image path is not correct, so it can't read the image

**Comment by Ashutosh1995** [comment]
Actually, I checked the image on that path and it exists.

This error of file not found is occurring at random positions and also with random image files.

Is it anything to do with how the annotation files are created since I initially had VOC annotations and I used the following code to convert them to COCO annotations?

https://github.com/Tony607/voc2coco

**Comment by zylo117** [comment]
It's hard to tell.
It should be solved easily if you can debug it with IDE

**Comment by Ashutosh1995** [comment]
Thanks for your response @zylo117! Any particular one you would recommend for this ?

**Comment by Ashutosh1995** [comment]
I was able to rectify this error! Thanks
