### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Ashutosh1995** [zylo117/Yet-Another-EfficientDet-Pytorch#641]
@zylo117 I am training Efficient D0 with my custom dataset after resolving the issue earlier I had.

I am running the following command

python train.py -c 0 -p indian_road --batch_size 4 --lr 1e-3 --num_epochs 15 --load_weights weights/efficientdet-d0.pth

During the final stage of training, I am getting the following error

![image](https://user-images.githubusercontent.com/11408850/116872575-bc749a80-ac33-11eb-9f9d-2360fdf29a1e.png)

Kindly help!

**Comment by nTnZone** [comment]
same question @zylo117 , operator(): block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed. How to fix it?
error :
File "/home/jayce/PycharmProjects/UnderTheWater/EfficientDet_github/train.py", line 226, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/home/jayce/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jayce/PycharmProjects/UnderTheWater/EfficientDet_github/train.py", line 80, in forward
    cls_loss, reg_loss = self.criterion(classification, regression, anchors, annotations)
  File "/home/jayce/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jayce/PycharmProjects/UnderTheWater/EfficientDet_github/efficientdet/loss.py", line 127, in forward
    if positive_indices.sum() > 0:
RuntimeError: CUDA error: device-side assert triggered

**Comment by nTnZone** [comment]
I used my own custom dataset

**Comment by nTnZone** [comment]
> I used my own custom dataset

I figure it it out by check out category items.

**Comment by Ashutosh1995** [comment]
@nTnZone were you able to solve it ?

**Comment by Ashutosh1995** [comment]
@zylo117 in the collater function, you append the annotation matrix with an extended version having -1's. 

This means the labels are also getting -1's right ? Can that lead to this issue of cuda device triggering ?

Please suggest!

**Comment by zylo117** [comment]
category id starts from 1

**Comment by Ashutosh1995** [comment]
@zylo117 in my voc to coco conversion file I passed my objects starting from index 1 as below:

PRE_DEFINE_CATEGORIES = {"auto": 1, "bicycle": 2, "bus": 3, "biker": 4,
        "car":5, "cow": 6, "cyclist": 7, "dog": 8, "motorbike": 9,
        "minitruck": 10, "person": 11, "truck": 12, "van": 13,
        "tractor": 14, "trolley": 15}


Also in the project.yml file, I defined the obj_list as ["auto","bicycle","bus","biker","car","cow","cyclist","dog","motorbike", "minitruck","person","truck","van","tractor","trolley"] i.e same order as above

Is there something else which I should do since the training code always stops during validation when images are tansfered on cuda printing the same error:  CUDA error: device-side assert triggered

**Comment by zylo117** [comment]
It's hard to tell without any details

**Comment by Ashutosh1995** [comment]
@zylo117 Could you please tell me what details you want so that the issue can be fixed?

**Comment by zylo117** [comment]
what's the error? logs?

**Comment by Ashutosh1995** [comment]
In the training loop, I get the following error:

![image](https://user-images.githubusercontent.com/11408850/117629965-54283a80-b198-11eb-8a8c-da10a0d859b0.png)


and when the val loop begins, the code breaks giving the following error
![image](https://user-images.githubusercontent.com/11408850/117630360-be40df80-b198-11eb-9632-f05adf67cd36.png)

**Comment by zylo117** [comment]
![image](https://user-images.githubusercontent.com/5842006/117633471-a412fb80-b1b0-11eb-9eb1-547c03fdcaed.png)
So you can still manage to train for a few steps? Could it be OOM? You should monitor vram in nvidia-smi.

**Comment by Ashutosh1995** [comment]
![image](https://user-images.githubusercontent.com/11408850/117860675-2f25eb80-b2ae-11eb-9b62-d414f2dc687e.png)

In the same epoch, when the validation stage enters, it triggers the warning and then quits. 

Is the value showing in nvidia-smi is what vram is ?

If no, could you please give a pointer on how to calculate vram ?

**Comment by zylo117** [comment]
validation？But there's a few thousand steps remaining.
![image](https://user-images.githubusercontent.com/5842006/117633471-a412fb80-b1b0-11eb-9eb1-547c03fdcaed.png)

Did you modify the code?
Can you run the tutorials?

**Comment by Ashutosh1995** [comment]
Actually, training gets completed triggering the error shot as a warning I pasted earlier.

It's when the validation phase starts, the code breaks and outputs RUNTime error: CUDA device asserted

I did not modify the code

I will run the tutorials also. I ran the test code and it ran perfectly.

**Comment by Ashutosh1995** [comment]
It got resolved. Thanks!
