### ISSUE TITLE
finetune on custom dataset exdark  get worse MAP

### ISSUE THREAD

**Issue by gdy2021** [zylo117/Yet-Another-EfficientDet-Pytorch#651]
finetune efficientdet-d0 on exdark dataset use default setting.
the finetuned model's map is around 0.25, much lower than unfinetuned model, which is 0.33.
anybody knows why?

**Comment by zylo117** [comment]
what do you mean by unfinetuned and finetuned models?

**Comment by gdy2021** [comment]
> what do you mean by unfinetuned and finetuned models?

finetuned means finetune efficientdet-d0 pretrained on COCO in exdark.
unfinetuned means efficientdet-d0 pretrained on COCO .

after long time training, now the finetuned one is better than the unfinetuned.
