### ISSUE TITLE
Output bounding box looks strange with Pretrained D0 model

### ISSUE THREAD

**Issue by ChanningPing** [zylo117/Yet-Another-EfficientDet-Pytorch#653]
I'm using the `efficientdet_test.py` to predict bounding boxes for 1 image with the provided pretrained ckpt D0, below is the result. You can see that the bounding box of the "refrigerator" looks a bit strange, as well as the 3 bottles next to the fridge.
![pytorch_kitchen](https://user-images.githubusercontent.com/13294020/119747978-b6e02e00-be48-11eb-88fb-3263a25902e3.jpg)

Below is the exact same image processed by the Google implementation and its provided ckpt D0: https://github.com/google/automl/tree/master/efficientdet
![0](https://user-images.githubusercontent.com/13294020/119748775-84cfcb80-be4a-11eb-952b-b781ed6dbb27.jpg)

You can see that the bounding boxes seem normal.

What is the difference here between this implementation and Google implementation? Are there any parameters I could tune to make it similar to the Google result?

**Comment by zylo117** [comment]
obviously they use a higher resolution to boost the mAP but it takes longer to forward.
You can set input_size to 1920 and try again

**Comment by ChanningPing** [comment]
Thanks so much for the advice! I changed `force_input_size = 1920` and now the result is normal:
![img_inferred_d0_this_repo_0](https://user-images.githubusercontent.com/13294020/119751251-a7b0ae80-be4f-11eb-8326-6c74e0a3cbbe.jpg)
Thanks again for the super quick help!
