### ISSUE TITLE
Evaluating provided D4 model

### ISSUE THREAD

**Issue by SiBensberg** [zylo117/Yet-Another-EfficientDet-Pytorch#671]
Did somebody try evaluating the provided weights for D4? 
For some reason the model performs very bad for me while the other models meet the expected performance.
```
MAP[0.5:0.95] D4: 0.160
MAP[0.5:0.95] D6: 0.505
```

**Comment by Ronald-Kray** [comment]
@SiBensberg 
Hi I have the same issues.
I have got decent results on D0, D1, D2. Also good results for --head_only True on D3, D4.
However, when I'm using --head_only False on D3, D4. performance is getting worse:) of course I've done second step training as  I did.
I don't know why....

**Comment by SiBensberg** [comment]
Ok so probably it is not me. 
Strange behavior, maybe somebody can throw some light on this.

**Comment by Ronald-Kray** [comment]
@SiBensberg 
um do you know how much do I have to have GPU's memory for training D3, D4, D5?
I couldn't find the exact required memory for that.

**Comment by SiBensberg** [comment]
I suggest you to try out. I can not train anything above D2 on my RTX2060 6GB

**Comment by SiBensberg** [comment]
I could see the following for the batchsize of 1:
D3 5,5gb
D4 8,7gb
D5 11,1GB
Could not do D6 because my 1080 can not handle it anymore.

**Comment by Ronald-Kray** [comment]
@SiBensberg 
I'm measuring the required memory!
Thanks!
I will also check it out and let you know about it!

**Comment by Ronald-Kray** [comment]
@SiBensberg 
Hey, I guess I got the answer to the question.
The author said the With such a small batch size, the training will be very unstable.
Maybe batch 1 or 2 produces a bad result. Please refer to the below issues
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/162

**Comment by SiBensberg** [comment]
I already made that experience. My issue is that I can not reproduce the MAP for the **provided** D4 model.

**Comment by zylo117** [comment]
@SiBensberg did you mean the original coco pretrained weights provided by me?

**Comment by SiBensberg** [comment]
> @SiBensberg did you mean the original coco pretrained weights provided by me?

Yes. I have bad results with the provided D4 weights. I also tested D0 D1 and D6 they provide good results.

my question is if somebody can reproduce it or if it is an error from on my side.

**Comment by zylo117** [comment]
@SiBensberg update to latest code?
I can't reproduce.
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.485
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.679
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.524
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.323
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.533
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.633
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.364
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.576
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.614
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.446
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.664
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.745
```
