### ISSUE TITLE
About training custom data

### ISSUE THREAD

**Issue by cnr0724** [zylo117/Yet-Another-EfficientDet-Pytorch#678]
Hello. First of all, thank you for the great work!

When I try to train on my own dataset, the process stops after loading annotations into memory like this.
```
loading annotations into memory...
Done (t=1.27s)
creating index...
index created!
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
[Info] initializing weights...
  0%|                                                   | 0/808 [00:00<?, ?it/s]
```

My dataset has one label, and I've checked everything to fit the dataset. Any help would be appreciated!T_T

**Comment by zylo117** [comment]
can you run it on colab? if so, then it's your env.
are you running on winodws?

**Comment by cnr0724** [comment]
I'm running it on Jetson Nano TX2, linux.

**Comment by zylo117** [comment]
I ran into this situation today... it was oom.
check your gpu and system memory usage

**Comment by zylo117** [comment]
btw, training on nano is hopeless

**Comment by cnr0724** [comment]
I guess it's just nano's problem because gpu/memory usage was just fine. Hehe T_T
Thank you for your help. Guess I should give up on training efficientdet......Thanks!!
