### ISSUE TITLE
训练启动时间问题

### ISSUE THREAD

**Issue by majx1997** [zylo117/Yet-Another-EfficientDet-Pytorch#679]
您好，我在训练自己的数据集的时候发现，加载pretrain的模型非常的缓慢。虽然整体显存占用不大，但是训练速度非常缓慢。不知道是不是正常的现象？
![image](https://user-images.githubusercontent.com/38154161/128147139-73819a5e-c486-493c-b20d-e5f2910418b4.png)

**Comment by zylo117** [comment]
载入到cpu是一瞬间的，载入到gpu就看cuda了，确实是慢。训练慢也是你设备性能不够啊。

**Comment by majx1997** [comment]
嗯呐。排查过了，是服务器CPU占用率太高导致的。谢谢您~
