### ISSUE TITLE
problem on resuming with "-w last" option (not loading latest checkpoint)

### ISSUE THREAD

**Issue by Hayoung93** [zylo117/Yet-Another-EfficientDet-Pytorch#686]
I'm trying to train the Effdet model on my own from scratch.

My training session stopped several times because of a server problem, so I need to use checkpoint files and resume training.

When loading weights with `-w last` option, it doesn't consider epochs, but only depends on the iteration number. However, there are more recent save files than the file with the highest iter number. So eventually I specified the latest checkpoint file manually.

It seems it could be fixed by considering an epoch number before checking an iteration number, or, there is a small problem in assigning a checkpoint name in my opinion.

Thank you for your great work.

**Comment by zylo117** [comment]
epoch is meaningless, only steps matter

**Comment by Hayoung93** [comment]
Thank you for the reply. For checking one more time, can a smaller step's epoch can be greater than a bigger step's epoch?
![image](https://user-images.githubusercontent.com/69784766/130378290-1e445a94-a72e-47c0-8c1e-f4db9b729c5f.png)

**Comment by zylo117** [comment]
epoch is calculated by the number of images and batchsize, so it may vary. only step will grow larger.

**Comment by Hayoung93** [comment]
Thank you for your polite explanation.

Maybe I changed batchsize.
