### ISSUE TITLE
Anchors calculation in each iteration

### ISSUE THREAD

**Issue by ilya-SX** [zylo117/Yet-Another-EfficientDet-Pytorch#689]
Hi, thank you for your work.

Can you please explain why should anchors be [calculated](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/15403b5371a64defb2a7c74e162c6e880a7f462c/backbone.py#L77) in each iteration (forward pass) instead of a single calculation (moving it to [`__init__`](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/15403b5371a64defb2a7c74e162c6e880a7f462c/backbone.py#L11))? The result depends on 3 properties of the input image:

- Shape (constant)
- Data type (constant)
- Device (constant, changes in parallel computing?)

What are the implications of moving this calculation to [`__init__`](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/15403b5371a64defb2a7c74e162c6e880a7f462c/backbone.py#L11) function of EfficientDetBackbone (with some default values) when using parallel computing?

Thank you.

**Comment by zylo117** [comment]
no, it will only calculate once as long as those 3 conditions remain unchanged.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/c533bc2de65135a6fe1d25ca437765c630943afb/efficientdet/utils.py#L96-L97

**Comment by ilya-SX** [comment]
So
