### ISSUE TITLE
An error in the dataset.py 

### ISSUE THREAD

**Issue by lockeregg** [zylo117/Yet-Another-EfficientDet-Pytorch#69]
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/71b36825c5c6d10a0fe15e31a352427392f3c69e/efficientdet/dataset.py#L55

should be 

path = os.path.join(self.root_dir, 'images', self.set_name, image_info['file_name'])

**Comment by zylo117** [comment]
no, it's not.
your dataset folder structure is not the same as requested

**Comment by lockeregg** [comment]
Ok I see, I am using the original  coco folder structure.
