### ISSUE TITLE
Label map classes differs across train-valid-test

### ISSUE THREAD

**Issue by niko047** [zylo117/Yet-Another-EfficientDet-Pytorch#694]
Does the algorithm allow for noise injection in the train part (many COCO format classes in training) which differs from validation and test COCO format (which only contain the relevant classes to be further carried on, without any noise)?
(Validation and test would be the same subset taken from the Train classes)

Or should I instead include my noise classes in the last two sets as well? Thank you.

**Comment by zylo117** [comment]
What kind of noise?

**Comment by niko047** [comment]
My bad, the question came from my personal misunderstanding of the model mechanics. It was just nonsense
