### ISSUE TITLE
No such operator torchvision::nms

### ISSUE THREAD

**Issue by Mankvis** [zylo117/Yet-Another-EfficientDet-Pytorch#696]
If the CPU is used, use_cuda=False, then cuda will not be used, and why will it report an error? RuntimeError: No such operator torchvision::nms
torch 1.4.0+cu92
torchvision 0.5.0

**Comment by zylo117** [comment]
can you confirm that torchvision version matches torch version? AFAIK, they have strong version binding relationship. Also, maybe some cuda versions just can't work with cpu

**Comment by Mankvis** [comment]
> can you confirm that torchvision version matches torch version? AFAIK, they have strong version binding relationship. Also, maybe some cuda versions just can't work with cpu

I haven't changed the pytorch version or cuda version
I just changed the python version from 3.6 to 3.7 and it worked

**Comment by zylo117** [comment]
actually, when you switch python version, the python deps will be different. For example, torch 1.4 for python3.6 != torch 1.4 for python3.7

**Comment by Mankvis** [comment]
> actually, when you switch python version, the python deps will be different. For example, torch 1.4 for python3.6 != torch 1.4 for python3.7

That's it, thank you
