### ISSUE TITLE
求助@w@

### ISSUE THREAD

**Issue by re-burn** [zylo117/Yet-Another-EfficientDet-Pytorch#699]
我用从coco中提取出来的全部含有"cell phone", "laptop", "tv"这三类物品的图片作为数据进行训练，调参调了挺久的但AP一直卡在20%左右上不去，有没有大佬训练过这几类物品的检测给个参考AP大概能达到多少啊

**Comment by zylo117** [comment]
这类小物品的ap就是比较低的，靠其他大物品的ap拉上去的
