### ISSUE TITLE
training time really long

### ISSUE THREAD

**Issue by LiangTinting** [zylo117/Yet-Another-EfficientDet-Pytorch#71]
Hi there, excellent work and thanks for sharing it!

I tried the recommended script, 3.a. Train on coco from scratch with default setting. It will take about 20 days. Did you train all theses models from scratch or from imagenet pre-trained models?

Thanks a lot!

**Comment by zylo117** [comment]
no, it's transferred and finetuned

**Comment by LiangTinting** [comment]
Finetuned from tensorflow efficientdet model?

**Comment by zylo117** [comment]
yes

**Comment by LiangTinting** [comment]
Then why finetune is necessary? Shouldn’t the test result same as tensorflow Efficient det report?

**Comment by zylo117** [comment]
the low level implement of TF and pytorch is slight different. So the output of pytorch's is about 1e-3 deviating from the official one, hence the finetune

**Comment by Li505358678** [comment]
@LiangTinting  I'm curious about Finetuned from tensorflow efficientdet model. What's the meaning of this?load tensorflow model?How to do it?
