### ISSUE TITLE
question about drop_connect

### ISSUE THREAD

**Issue by hanguniverse** [zylo117/Yet-Another-EfficientDet-Pytorch#76]
Hello
I saw the drop connect ratio in official tensorflow codes in set 0 in 'efficientnet-B0'.
if 'b0' in backbone_name:
      override_params['survival_prob'] = 0.0   in efficientdet_arch.py 321#

But your implementation doesn't seem to notice this detail，or I didn't notice?

**Comment by zylo117** [comment]
I noticed that, but survival_prob is always None, so it's optional.
