### ISSUE TITLE
error load pretrain weights

### ISSUE THREAD

**Issue by phucnhs** [zylo117/Yet-Another-EfficientDet-Pytorch#8]
File "train.py", line 113, in train
    model.load_state_dict(torch.load(weights_path))
  File "/home/phucnhs/miniconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone:
	size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([810, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 64, 1, 1]).
	size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([810]) from checkpoint, the shape in current model is torch.Size([45]).
Hi !
I use custom dataset with 5 class and when training i have use pretrain coco download in repo .
How do I solve it !
thanks

**Comment by zylo117** [comment]
I see, I wil fix it soon

**Comment by zylo117** [comment]
fixed it.please pull the latest code and try again

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/737cc18af667b519126e8e965fd156a69705e9ed

**Comment by phucnhs** [comment]
- I just got an error when after 1 epoch it start eval and got a cuda error : 
Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
- i add  imgs = imgs.cuda() to if params.num_gpus > 0 in file train.py line 235 , it worker
- you can check it

**Comment by zylo117** [comment]
done, it's fixed, thanks for providing info

**Comment by phucnhs** [comment]
thanks ! 
- In repo author (tensorflow)  have use autoaugment (policy) , I find it pretty good ,Do you have to add

**Comment by zylo117** [comment]
Have they?

I checked for a few times, the official repo has auto aug, yes, but is disabled by default. Only horizontal flip is applied.
