### ISSUE TITLE
An error in drop_connnect setting

### ISSUE THREAD

**Issue by hanguniverse** [zylo117/Yet-Another-EfficientDet-Pytorch#80]
I don't know why you closed my comment yesterday

the drop_connect rate in official implements is set in 0 in efficientdet D0 but 0.2 in D1~D7，but in your 
implement I observed your implement this ratio is always 0.2, no matter D0 or oher.

**Comment by zylo117** [comment]
And I did answered you... I thought you came around.

And no, survival prob is not drop_connect_rate, it equals 1 - drop_connect_rate. It's not for dropout layers, but the convs.

And the official impl didn't apply survival prob, it's always None. Just check out the hparam config, or debug it yourself.
