### ISSUE TITLE
why  model efficientdet-d2 test time so long?

### ISSUE THREAD

**Issue by zheng-2019** [zylo117/Yet-Another-EfficientDet-Pytorch#83]

**Comment by zheng-2019** [comment]
1.1615002870559692 seconds, 0.8609554480048208 FPS, @batch_size 1

**Comment by zylo117** [comment]
set force_input_size to None.
if it doesn't work, then it is slow on your machine.
I tested on 2080ti

**Comment by prfans** [comment]
The first time to run the program is slow, and then it's very fast.My time on the 1080TI is 350 ms per image.

**Comment by zheng-2019** [comment]
> The first time to run the program is slow, and then it's very fast.My time on the 1080TI is 350 ms per image.

official EfficientDet  speed/FPS is 26.50，in fact it is 3.222

**Comment by zheng-2019** [comment]
> set force_input_size to None.
> if it doesn't work, then it is slow on your machine.
> I tested on 2080ti

i know ,ths, why this coad test time is longer so much than the official EfficientDet speed?

**Comment by prfans** [comment]
It could be the difference between 1080ti and 2080ti...

**Comment by zylo117** [comment]
2080Ti is about 60% faster than 1080Ti in extreme tests.
But it would be negligible in such small model.
Check your environment, is it pytorch 1.4? is it on linux? Every model runs slower on windows.

**Comment by prfans** [comment]
Yes, I ran it on Windows, and I guess it was Windows.

**Comment by zheng-2019** [comment]
> negligible

my pytorch is 1.1,cadu10.0 ,on linux

**Comment by zylo117** [comment]
update to 1.4, as I said so in readme..................
