### ISSUE TITLE
coco_eval结果异常，ap=0

### ISSUE THREAD

**Issue by lexiqi** [zylo117/Yet-Another-EfficientDet-Pytorch#86]
完全按照tutorial的流程执行下来的，为什么结果ap都为0

**Comment by zylo117** [comment]
please share all of the training log

**Comment by lexiqi** [comment]
![image](https://user-images.githubusercontent.com/25817952/79315947-43c27380-7f36-11ea-83c3-6c72ea9a1689.png)

**Comment by gtgtgt1117** [comment]
> ![image](https://user-images.githubusercontent.com/25817952/79315947-43c27380-7f36-11ea-83c3-6c72ea9a1689.png)
请问一下,你训练的时候一开始的loss大吗?

**Comment by lexiqi** [comment]
> > ![image](https://user-images.githubusercontent.com/25817952/79315947-43c27380-7f36-11ea-83c3-6c72ea9a1689.png)
> > 请问一下,你训练的时候一开始的loss大吗?

**Comment by lexiqi** [comment]
![1586939346(1)](https://user-images.githubusercontent.com/25817952/79316383-d400b880-7f36-11ea-9e1d-6fd9e4e21b04.png)
截取了最后的一部分，感觉loss是正常的，一直在下降

**Comment by lexiqi** [comment]
> > ![image](https://user-images.githubusercontent.com/25817952/79315947-43c27380-7f36-11ea-83c3-6c72ea9a1689.png)
> > 请问一下,你训练的时候一开始的loss大吗?

就第一轮大，之后就降下来了

**Comment by gtgtgt1117** [comment]
> ![1586939346(1)](https://user-images.githubusercontent.com/25817952/79316383-d400b880-7f36-11ea-9e1d-6fd9e4e21b04.png)
> 截取了最后的一部分，感觉loss是正常的，一直在下降



我一开始的loss很大,ap也是0.请问您解决这个问题了吗

**Comment by lexiqi** [comment]
> > ![1586939346(1)](https://user-images.githubusercontent.com/25817952/79316383-d400b880-7f36-11ea-9e1d-6fd9e4e21b04.png)
> > 截取了最后的一部分，感觉loss是正常的，一直在下降
> 
> 我一开始的loss很大,ap也是0.请问您解决这个问题了吗

还木有呐

**Comment by gtgtgt1117** [comment]
> > > ![1586939346(1)](https://user-images.githubusercontent.com/25817952/79316383-d400b880-7f36-11ea-9e1d-6fd9e4e21b04.png)
> > > 截取了最后的一部分，感觉loss是正常的，一直在下降
> > 
> > 
> > 我一开始的loss很大,ap也是0.请问您解决这个问题了吗
> 
> 还木有呐



Step: 201. Epoch: 0/10. Iteration: 202/202. Cls loss: 467392.84375. Reg loss: 1.64562. Total loss: 467394.
libpng warning: iCCP: known incorrect sRGB profile
Val. Epoch: 0/10. Classification loss: 225579.01164. Regression loss: 1.63974. Total loss: 225580.65138
Step: 343. Epoch: 1/10. Iteration: 142/202. Cls loss: 317644.15625. Reg loss: 1.13660. Total loss: 317645.libpng warning: iCCP: known incorrect sRGB profile
Step: 403. Epoch: 1/10. Iteration: 202/202. Cls loss: 49397.32812. Reg loss: 1.61851. Total loss: 49398.94
libpng warning: iCCP: known incorrect sRGB profile
Val. Epoch: 1/10. Classification loss: 126970.32506. Regression loss: 1.53418. Total loss: 126971.85924
  0%|                                                                             | 0/202 [00:00<?, ?it/s]libpng warning: iCCP: known incorrect sRGB profile
Step: 499. Epoch: 2/10. Iteration: 96/202. Cls loss: 361069.93750. Reg loss: 0.84303. Total loss: 361070.7checkpoint...
Step: 605. Epoch: 2/10. Iteration: 202/202. Cls loss: 67041.67188. Reg loss: 0.99701. Total loss: 67042.67
libpng warning: iCCP: known incorrect sRGB profile
Val. Epoch: 2/10. Classification loss: 77189.68104. Regression loss: 1.50445. Total loss: 77191.18549
Step: 650. Epoch: 3/10. Iteration: 45/202. Cls loss: 26456.12305. Reg loss: 2.14886. Total loss: 26458.271libpng warning: iCCP: known incorrect sRGB profile
Step: 807. Epoch: 3/10. Iteration: 202/202. Cls loss: 29214.00391. Reg loss: 1.29512. Total loss: 29215.29

你看一下我的.是不是哪里有什么问题?

**Comment by prfans** [comment]
降低学习率，多训练一会可能有改善。

**Comment by gtgtgt1117** [comment]
> 降低学习率，多训练一会可能有改善。



是否应该增大学习率,我lr是1e-5

**Comment by SDGLBL** [comment]
修改如下代码可能可以帮到你
[https://github.com/SDGLBL/Yet-Another-EfficientDet-Pytorch/blob/4cc20a327a0f43ec964f6a9b388e5b6d9ff394ce/coco_eval.py#L111](url)

**Comment by gtgtgt1117** [comment]
> 修改如下代码可能可以帮到你
> [https://github.com/SDGLBL/Yet-Another-EfficientDet-Pytorch/blob/4cc20a327a0f43ec964f6a9b388e5b6d9ff394ce/coco_eval.py#L111](url)



链接不存在呀

**Comment by SDGLBL** [comment]
> > 修改如下代码可能可以帮到你
> > [https://github.com/SDGLBL/Yet-Another-EfficientDet-Pytorch/blob/4cc20a327a0f43ec964f6a9b388e5b6d9ff394ce/coco_eval.py#L111](url)
> 
> 链接不存在呀

复制到浏览器中打开

**Comment by lexiqi** [comment]
> > > 修改如下代码可能可以帮到你
> > > [https://github.com/SDGLBL/Yet-Another-EfficientDet-Pytorch/blob/4cc20a327a0f43ec964f6a9b388e5b6d9ff394ce/coco_eval.py#L111](url)
> > 
> > 
> > 链接不存在呀
> 
>

> > > 修改如下代码可能可以帮到你
> > > [https://github.com/SDGLBL/Yet-Another-EfficientDet-Pytorch/blob/4cc20a327a0f43ec964f6a9b388e5b6d9ff394ce/coco_eval.py#L111](url)
> > 
> > 
> > 链接不存在呀
> 
> 复制到浏览器中打开

修改的地方是'category_id': label+1,==》'category_id': label,？  按照这个改了后我的结果还是0

**Comment by zylo117** [comment]
don't change it the code if you are not sure what you are doing....

please read and run the tutorial, it should work, and try to find out the different between your code and the tutorial.

**Comment by lexiqi** [comment]
> don't change it the code if you are not sure what you are doing....
> 
> please read and run the tutorial, it should work, and try to find out the different between your code and the tutorial.

OK，get√，3Q

**Comment by nothingws** [comment]
> > > > ![1586939346(1)](https://user-images.githubusercontent.com/25817952/79316383-d400b880-7f36-11ea-9e1d-6fd9e4e21b04.png)
> > > > 截取了最后的一部分，感觉loss是正常的，一直在下降
> > > 
> > > 
> > > 我一开始的loss很大,ap也是0.请问您解决这个问题了吗
> > 
> > 
> > 还木有呐
> 
> Step: 201. Epoch: 0/10. Iteration: 202/202. Cls loss: 467392.84375. Reg loss: 1.64562. Total loss: 467394.
> libpng warning: iCCP: known incorrect sRGB profile
> Val. Epoch: 0/10. Classification loss: 225579.01164. Regression loss: 1.63974. Total loss: 225580.65138
> Step: 343. Epoch: 1/10. Iteration: 142/202. Cls loss: 317644.15625. Reg loss: 1.13660. Total loss: 317645.libpng warning: iCCP: known incorrect sRGB profile
> Step: 403. Epoch: 1/10. Iteration: 202/202. Cls loss: 49397.32812. Reg loss: 1.61851. Total loss: 49398.94
> libpng warning: iCCP: known incorrect sRGB profile
> Val. Epoch: 1/10. Classification loss: 126970.32506. Regression loss: 1.53418. Total loss: 126971.85924
> 0%| | 0/202 [00:00<?, ?it/s]libpng warning: iCCP: known incorrect sRGB profile
> Step: 499. Epoch: 2/10. Iteration: 96/202. Cls loss: 361069.93750. Reg loss: 0.84303. Total loss: 361070.7checkpoint...
> Step: 605. Epoch: 2/10. Iteration: 202/202. Cls loss: 67041.67188. Reg loss: 0.99701. Total loss: 67042.67
> libpng warning: iCCP: known incorrect sRGB profile
> Val. Epoch: 2/10. Classification loss: 77189.68104. Regression loss: 1.50445. Total loss: 77191.18549
> Step: 650. Epoch: 3/10. Iteration: 45/202. Cls loss: 26456.12305. Reg loss: 2.14886. Total loss: 26458.271libpng warning: iCCP: known incorrect sRGB profile
> Step: 807. Epoch: 3/10. Iteration: 202/202. Cls loss: 29214.00391. Reg loss: 1.29512. Total loss: 29215.29
> 
> 你看一下我的.是不是哪里有什么问题?

I have the same problem as you
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

**Comment by firefox1031** [comment]
@lexiqi , I have the same problem. Do you find the solution?

**Comment by lexiqi** [comment]
> @lexiqi , I have the same problem. Do you find the solution?

The "val_set_bbox_results.json"  what I used is wrong

**Comment by xingyueye** [comment]
> The "val_set_bbox_results.json" what I used is wrong

@lexiqi is your val_set_bbox_results.json created at the first time to run coco_evla.py? I was considered weather I have countered the same problem
