### ISSUE TITLE
The performance of the test is not as good as the results you gave

### ISSUE THREAD

**Issue by opentld** [zylo117/Yet-Another-EfficientDet-Pytorch#87]
the result of d0 you gave:
![image](https://user-images.githubusercontent.com/21096515/79321246-9d7a6c00-7f3d-11ea-89b5-0caa39031cda.png)

Use the trained model you provided, the result of d0:
![image](https://user-images.githubusercontent.com/21096515/79321302-b71bb380-7f3d-11ea-9807-e2617e98ea2d.png)

the result of d7:
![image](https://user-images.githubusercontent.com/21096515/79321337-c3077580-7f3d-11ea-83eb-9dd7f006b59c.png)

Why is it not as good as the results you gave? Do I need to set some parameters? 
@zylo117

**Comment by zylo117** [comment]
set force_input_size to 1920, that's all I did

**Comment by opentld** [comment]
perfect! thank you！
