### ISSUE TITLE
How to finetune only the last layers of EfficientNet and BiFPN instead of the whole net or head only?

### ISSUE THREAD

**Issue by Kongsea** [zylo117/Yet-Another-EfficientDet-Pytorch#88]
I want to finetune only the last layers of EfficientNet and BiFPN, instead of the current whole net or head only, could you give some advice?
Thank you for your excellent work.

**Comment by r2ufuk** [comment]
You can choose which layers to freeze from [here](https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/85ac208de6253b1b578817550e0db03e4708d787/train.py#L151)

**Comment by Kongsea** [comment]
Thank you.
