### ISSUE TITLE
The speed is still slow than yolo3.

### ISSUE THREAD

**Issue by GlassyWing** [zylo117/Yet-Another-EfficientDet-Pytorch#90]
I test the FPS by video detecting on my computer (NVIDIA 1070ti), 1st is the yolo3+deepsort (detecting and tracking full implemented by pytorch), 2nd is efficientdet(0). However, FPS shows that EfficientDet is still slower than yolo3, even though it only does detection. The inference time for yolo3 on my computer is 20ms，but 80ms for efficientdet0, Maybe there are still some areas that need to be optimized.

1. FPS for yolo3+deepsort (about 15)

![Snipaste_2020-04-15_17-37-07](https://user-images.githubusercontent.com/17000429/79324695-94d86480-7f42-11ea-805c-eaf125260125.png)

2. FPS for EfficientDet0 (about 12)

![Snipaste_2020-04-15_17-30-13](https://user-images.githubusercontent.com/17000429/79324707-986beb80-7f42-11ea-8135-2b621883c00c.png)

**Comment by zylo117** [comment]
what's the batch size and input size?

And yes, i think yolo v3 is faster than effdet but effdet consumes less memory and has less parameters. So when running with bigger batch size, i.e. 32, effdet should be faster.

**Comment by GlassyWing** [comment]
> what's the batch size and input size?
> 
> And yes, i think yolo v3 is faster than effdet but effdet consumes less memory and has less parameters. So when running with bigger batch size, i.e. 32, effdet should be faster.

origin video size is 720p, then resize to 512 x 512, the batch size is 1. Yes,  in an offline environment effdet is  better perhaps.

**Comment by zylo117** [comment]
> > what's the batch size and input size?
> > And yes, i think yolo v3 is faster than effdet but effdet consumes less memory and has less parameters. So when running with bigger batch size, i.e. 32, effdet should be faster.
> 
> origin video size is 720p, then resize to 512 x 512, the batch size is 1. Yes, in an offline environment effdet is better perhaps.

btw, you should run it on linux. pytorch is super slow on Windows. There is a community member who claimed 30+ FPS on 1070ti

**Comment by GlassyWing** [comment]
ok,l'll try it

**Comment by lanybass** [comment]
一样，慢。
ubuntu 16.04 2080TI 跑预训练的d0，只有24FPS，而且识别出来的人还会漏掉，达不到img_inferred_d0_official.jpg的效果
```
Linux yunwagai-PR4764GW 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
******@yunwagai-PR4764GW:~/workspace/Yet-Another-EfficientDet-Pytorch$ nvidia-smi
Thu Apr 16 08:39:35 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 27%   32C    P0    47W / 280W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 31%   32C    P0    27W / 280W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
******@yunwagai-PR4764GW:~/workspace/Yet-Another-EfficientDet-Pytorch$ conda list|grep torch
torch                     1.3.1                    pypi_0    pypi
torchvision               0.4.2                    pypi_0    pypi
******@yunwagai-PR4764GW:~/workspace/Yet-Another-EfficientDet-Pytorch$ python efficientdet_test.py
running speed test...
test1: model inferring and postprocessing
inferring image for 10 times...
0.04154320001602173 seconds, 24.071328150319083 FPS, @batch_size 1
```

**Comment by zylo117** [comment]
mine is torch 1.4, Python3.7, Ubuntu 19.04

**Comment by zylo117** [comment]
if you want to replicate the same effects as the demo, you will have to set `force_input_size=1920`

**Comment by monoloxo** [comment]
> I test the FPS by video

Is there someway test by video or camera?

**Comment by zheng-2019** [comment]
> I test the FPS by video detecting on my computer (NVIDIA 1070ti), 1st is the yolo3+deepsort (detecting and tracking full implemented by pytorch), 2nd is efficientdet(0). However, FPS shows that EfficientDet is still slower than yolo3, even though it only does detection. The inference time for yolo3 on my computer is 20ms，but 80ms for efficientdet0, Maybe there are still some areas that need to be optimized.
> 
> 1. FPS for yolo3+deepsort (about 15)
> 
> ![Snipaste_2020-04-15_17-37-07](https://user-images.githubusercontent.com/17000429/79324695-94d86480-7f42-11ea-805c-eaf125260125.png)
> 
> 1. FPS for EfficientDet0 (about 12)
> 
> ![Snipaste_2020-04-15_17-30-13](https://user-images.githubusercontent.com/17000429/79324707-986beb80-7f42-11ea-8135-2b621883c00c.png)

the result looks good,how many epoch do you train? and hao to set the train parameter?

**Comment by GlassyWing** [comment]
> > I test the FPS by video
> 
> Is there someway test by video or camera?

just use cv2, it can read local video or camera, there are some key code:
```

# open video
video_path = "E:/python/data/car.flv" # or camera id
vid = cv2.VideoCapture(video_path)

while vid.grab():
    ret, frame = vid.retrieve()
    if not ret:
        break

    # BGR 2 RGB
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # preprocss for single image
    ori_img, framed_img, framed_meta = preprocess_single_image(frame, max_size=input_size)

    #  detection
    inference_start_time = time.time()
    with torch.no_grad():

        # convert to tensor
        x = torch.tensor(framed_img, device="cuda:0").unsqueeze(0)
        x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3, 1, 2)

        features, regression, classification, anchors = model(x)

        regressBoxes = BBoxTransform()
        clipBoxes = ClipBoxes()

        out = postprocess(x,
                          anchors, regression, classification,
                          regressBoxes, clipBoxes,
                          threshold, iou_threshold)
    inference_end_time = time.time()
    logging.info("\t Inference time: %s ", datetime.timedelta(seconds=inference_end_time - inference_start_time))

    # detection over

    # log FPS on frame
    ...


    # get detection bbox
    out = invert_affine([framed_meta], out)

    # reverse to BGR
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

    # draw bbox on frame and display
    display(out[0], frame, imwrite=False)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

**Comment by GlassyWing** [comment]
> > I test the FPS by video detecting on my computer (NVIDIA 1070ti), 1st is the yolo3+deepsort (detecting and tracking full implemented by pytorch), 2nd is efficientdet(0). However, FPS shows that EfficientDet is still slower than yolo3, even though it only does detection. The inference time for yolo3 on my computer is 20ms，but 80ms for efficientdet0, Maybe there are still some areas that need to be optimized.
> > 
> > 1. FPS for yolo3+deepsort (about 15)
> > 
> > ![Snipaste_2020-04-15_17-37-07](https://user-images.githubusercontent.com/17000429/79324695-94d86480-7f42-11ea-805c-eaf125260125.png)
> > 
> > 1. FPS for EfficientDet0 (about 12)
> > 
> > ![Snipaste_2020-04-15_17-30-13](https://user-images.githubusercontent.com/17000429/79324707-986beb80-7f42-11ea-8135-2b621883c00c.png)
> 
> the result looks good,how many epoch do you train? and hao to set the train parameter?

I don’t actually have any training, just use the efficientdet-d0.pth in readme.

**Comment by zylo117** [comment]
I see, there are some places that can be optimized.

use `torch.from_numpy` instead. `torch.tensor` is much slower
`x = torch.tensor(framed_img, device="cuda:0").unsqueeze(0)`

don't initialize modules every time
```
regressBoxes = BBoxTransform()
clipBoxes = ClipBoxes()
```

**Comment by GlassyWing** [comment]
> I see, there are some places that can be optimized.
> 
> use `torch.from_numpy` instead. `torch.tensor` is much slower
> `x = torch.tensor(framed_img, device="cuda:0").unsqueeze(0)`
> 
> don't initialize modules every time
> 
> ```
> regressBoxes = BBoxTransform()
> clipBoxes = ClipBoxes()
> ```

looks like there is no significant change
![Snipaste_2020-04-16_10-46-16](https://user-images.githubusercontent.com/17000429/79409068-8a17e100-7fcf-11ea-8cb8-c29cad9ca600.png)

**Comment by zylo117** [comment]
alright, then I guess the real impact really is windows

**Comment by lanybass** [comment]
I've followed your instruction, installed the right version now. the same result,[d0 22FPS]
```
******@yunwagai-PR4764GW:~/workspace/Yet-Another-EfficientDet-Pytorch$ conda list
# packages in environment at /usr/opt/anaconda3/envs/effdet:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
absl-py                   0.9.0                    pypi_0    pypi
ca-certificates           2020.1.1                      0    defaults
cachetools                4.1.0                    pypi_0    pypi
certifi                   2020.4.5.1               py37_0    defaults
chardet                   3.0.4                    pypi_0    pypi
cython                    0.29.16                  pypi_0    pypi
google-auth               1.14.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.28.1                   pypi_0    pypi
idna                      2.9                      pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
markdown                  3.2.1                    pypi_0    pypi
ncurses                   6.2                  he6710b0_0    defaults
numpy                     1.18.2                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1f               h7b6447c_0    defaults
pillow                    7.1.1                    pypi_0    pypi
pip                       20.0.2                   py37_1    defaults
protobuf                  3.11.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.0                    pypi_0    pypi
python                    3.7.7           hcf32534_0_cpython    defaults
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0    defaults
requests                  2.23.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
setuptools                46.1.3                   py37_0    defaults
six                       1.14.0                   pypi_0    pypi
sqlite                    3.31.1               h7b6447c_0    defaults
tensorboard               2.2.1                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0.post3              pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tk                        8.6.8                hbc83047_0    defaults
torch                     1.4.0                    pypi_0    pypi
torchvision               0.5.0                    pypi_0    pypi
tqdm                      4.45.0                   pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
======================================
******@yunwagai-PR4764GW:~/workspace/Yet-Another-EfficientDet-Pytorch$ python efficientdet_test.py
running speed test...
test1: model inferring and postprocessing
inferring image for 10 times...
0.04407162427902222 seconds, 22.690336840523322 FPS, @batch_size 1
```

**Comment by zylo117** [comment]
Maybe you can try official python3.7 instead of anaconda.
Also my cpu is i5 8400, whose freq is up to 4.00 GHz. I guess you are using a server cpu which has more cores but lower freq. That may be slower.

Did you set `force_input_size = None`?

**Comment by lanybass** [comment]
> Maybe you can try official python3.7 instead of anaconda.
> Also my cpu is i5 8400, whose freq is up to 4.00 GHz. I guess you are using a server cpu which has more cores but lower freq. That may be slower.
> 
> Did you set `force_input_size = None`?

是的，双CPU， E5 2.50GHz  
我就是运行的EfficientDet_Test.py什么都没改
force_input_size默认就是None
用的conda Python 3.7.7，有空我再试试官方python吧，我猜测不会应为这个问题吧

**Comment by zylo117** [comment]
> > Maybe you can try official python3.7 instead of anaconda.
> > Also my cpu is i5 8400, whose freq is up to 4.00 GHz. I guess you are using a server cpu which has more cores but lower freq. That may be slower.
> > Did you set `force_input_size = None`?
> 
> 是的，双CPU， E5 2.50GHz
> 我就是运行的EfficientDet_Test.py什么都没改
> force_input_size默认就是None
> 用的conda Python 3.7.7，有空我再试试官方python吧，我猜测不会应为这个问题吧

you can monitor the cpu usage using htop, if there is a cpu core 100% all the way during inference, then it could be the bottlelneck. For i5 8400 4GHz, the highest usage is less than 40%.

**Comment by GlassyWing** [comment]
I have done it agin on linux. 

THE ENV:
OS: Ubuntu 18.04
GPU: NVIDIA TiTAN V
CPU: Intel i9-7980XE

And this is the test result:

1. yolo3 + deepsort (with 1G Video memory)

![Snipaste_2020-04-17_15-08-04](https://user-images.githubusercontent.com/17000429/79541920-47cccd80-80bd-11ea-9d38-5dd43924df0b.png)

2. effdet0 (with 0.68G Video memory)

![Snipaste_2020-04-17_15-08-09](https://user-images.githubusercontent.com/17000429/79541916-46030a00-80bd-11ea-9f14-4c0e3508e066.png)

result  for single image without video processing  (efficientdet_test.py):
![Snipaste_2020-04-17_15-16-16](https://user-images.githubusercontent.com/17000429/79542535-6a131b00-80be-11ea-9693-3d74fe25c542.png)

The reason why inference speed in video detecting slower than single image is that, for every frame in video it has to be convert to tensor, while in efficientdet_test.py, the image is converted only once. And if we draw bbox for every frame, the FPS should be more small. So the FPS in video detection is completely below 30. But anyway, the speed is indeed a big difference from yolo3.

**Comment by zylo117** [comment]
yes, converting numpyarray to GPU tensor does takes time.

do you use torch.tensor or torch.from_numpy? the first one is slow. It may be negligible in Windows, but in Linux, I find from_numpy is much faster.

or a better question, how does yolo3 convert numpy array to tensor?

**Comment by GlassyWing** [comment]
> yes, converting numpy array to GPU tensor does take time.
> 
> do you use torch.tensor or torch.from_numpy? the first one is slow. It may be negligible in Windows, but in Linux, I find that from_numpy is much faster.
> 
> or a better question, how does yolo3 convert numpy array to tensor?

They do same thing: 
```
torch.from_numpy(img).to("cuda:0")
```

There is a key difference, yolo3 preprocess/postprocess  images after send images to GPU, while in there, Preprocessing occurs before sending image to the GPU.

**Comment by zylo117** [comment]
> > yes, converting numpy array to GPU tensor does take time.
> > do you use torch.tensor or torch.from_numpy? the first one is slow. It may be negligible in Windows, but in Linux, I find that from_numpy is much faster.
> > or a better question, how does yolo3 convert numpy array to tensor?
> 
> They do same thing:
> 
> ```
> torch.from_numpy(img).to("cuda:0")
> ```
> 
> There is a key difference, yolo3 preprocess/postprocess images after send images to GPU, while in there, Preprocessing occurs before sending image to the GPU.

I see.

**Comment by MustafaUysal160207077** [comment]
> > > I test the FPS by video
> > 
> > 
> > Is there someway test by video or camera?
> 
> just use cv2, it can read local video or camera, there are some key code:
> 
> ```
> 
> # open video
> video_path = "E:/python/data/car.flv" # or camera id
> vid = cv2.VideoCapture(video_path)
> 
> while vid.grab():
>     ret, frame = vid.retrieve()
>     if not ret:
>         break
> 
>     # BGR 2 RGB
>     frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
> 
>     # preprocss for single image
>     ori_img, framed_img, framed_meta = preprocess_single_image(frame, max_size=input_size)
> 
>     #  detection
>     inference_start_time = time.time()
>     with torch.no_grad():
> 
>         # convert to tensor
>         x = torch.tensor(framed_img, device="cuda:0").unsqueeze(0)
>         x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3, 1, 2)
> 
>         features, regression, classification, anchors = model(x)
> 
>         regressBoxes = BBoxTransform()
>         clipBoxes = ClipBoxes()
> 
>         out = postprocess(x,
>                           anchors, regression, classification,
>                           regressBoxes, clipBoxes,
>                           threshold, iou_threshold)
>     inference_end_time = time.time()
>     logging.info("\t Inference time: %s ", datetime.timedelta(seconds=inference_end_time - inference_start_time))
> 
>     # detection over
> 
>     # log FPS on frame
>     ...
> 
> 
>     # get detection bbox
>     out = invert_affine([framed_meta], out)
> 
>     # reverse to BGR
>     frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
> 
>     # draw bbox on frame and display
>     display(out[0], frame, imwrite=False)
>     if cv2.waitKey(1) & 0xFF == ord('q'):
>         break
> ```

Thanks for this code. I can't use `preprocess_single_image` it is not defined. How can I use that function?

**Comment by GlassyWing** [comment]
> > > > I test the FPS by video
> > > 
> > > 
> > > Is there someway test by video or camera?
> > 
> > 
> > just use cv2, it can read local video or camera, there are some key code:
> > ```
> > 
> > # open video
> > video_path = "E:/python/data/car.flv" # or camera id
> > vid = cv2.VideoCapture(video_path)
> > 
> > while vid.grab():
> >     ret, frame = vid.retrieve()
> >     if not ret:
> >         break
> > 
> >     # BGR 2 RGB
> >     frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
> > 
> >     # preprocss for single image
> >     ori_img, framed_img, framed_meta = preprocess_single_image(frame, max_size=input_size)
> > 
> >     #  detection
> >     inference_start_time = time.time()
> >     with torch.no_grad():
> > 
> >         # convert to tensor
> >         x = torch.tensor(framed_img, device="cuda:0").unsqueeze(0)
> >         x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3, 1, 2)
> > 
> >         features, regression, classification, anchors = model(x)
> > 
> >         regressBoxes = BBoxTransform()
> >         clipBoxes = ClipBoxes()
> > 
> >         out = postprocess(x,
> >                           anchors, regression, classification,
> >                           regressBoxes, clipBoxes,
> >                           threshold, iou_threshold)
> >     inference_end_time = time.time()
> >     logging.info("\t Inference time: %s ", datetime.timedelta(seconds=inference_end_time - inference_start_time))
> > 
> >     # detection over
> > 
> >     # log FPS on frame
> >     ...
> > 
> > 
> >     # get detection bbox
> >     out = invert_affine([framed_meta], out)
> > 
> >     # reverse to BGR
> >     frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
> > 
> >     # draw bbox on frame and display
> >     display(out[0], frame, imwrite=False)
> >     if cv2.waitKey(1) & 0xFF == ord('q'):
> >         break
> > ```
> 
> Thanks for this code. I can't use `preprocess_single_image` it is not defined. How can I use that function?

that's simple since the`preprocess` has been defiened:
```
def preprocess(*image_path, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
    ori_imgs = [cv2.imread(img_path) for img_path in image_path]
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
    imgs_meta = [aspectaware_resize_padding(img[..., ::-1], max_size, max_size,
                                            means=None) for img in normalized_imgs]
    framed_imgs = [img_meta[0] for img_meta in imgs_meta]
    framed_metas = [img_meta[1:] for img_meta in imgs_meta]

    return ori_imgs, framed_imgs, framed_metas
```

the only thing you need to do is process single image:
```
def preprocess_single_image(image, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
    normalized_img = (image / 255 - mean) / std
    img_meta = aspectaware_resize_padding(normalized_img[..., ::-1], max_size, max_size,
                                          means=None)
    framed_img = img_meta[0]
    framed_meta = img_meta[1:]

    return image, framed_img, framed_meta
```

**Comment by MustafaUysal160207077** [comment]
> the only thing you need to do is process single image:
> 
> ```
> def preprocess_single_image(image, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
>     normalized_img = (image / 255 - mean) / std
>     img_meta = aspectaware_resize_padding(normalized_img[..., ::-1], max_size, max_size,
>                                           means=None)
>     framed_img = img_meta[0]
>     framed_meta = img_meta[1:]
> 
>     return image, framed_img, framed_meta
> ```

I've tried this 
```
def preprocess_single_image(*image_path, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
   
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
    img_meta = [aspectaware_resize_padding(img[..., ::-1], max_size, max_size,
                                            means=None) 
    
    framed_img = img_meta[0] 
    framed_meta = img_meta[1:]

    return normalized_img, framed_img, framed_meta
```

But I've seen this error: 
   ```
 framed_img = img_meta[0]
             ^
SyntaxError: invalid syntax
```
Do you have any idea? I am unable to understand why it does happen.

**Comment by MustafaUysal160207077** [comment]
> the only thing you need to do is process single image:
> 
> ```
> def preprocess_single_image(image, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
>     normalized_img = (image / 255 - mean) / std
>     img_meta = aspectaware_resize_padding(normalized_img[..., ::-1], max_size, max_size,
>                                           means=None)
>     framed_img = img_meta[0]
>     framed_meta = img_meta[1:]
> 
>     return image, framed_img, framed_meta
> ```

Thank you very much!
How should I change this line? (I don't use CUDA)

` x = torch.tensor(framed_img, device="cuda:0").unsqueeze(0)`
It raises error:
 ```
   raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```
