### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by xiexu666** [zylo117/Yet-Another-EfficientDet-Pytorch#98]
when i train every thing is ok。When I use`python coco_eval.py -p coco -c 0 -w ./logs/coco/efficientdet-d0_9_430.pth` to test my model get a error。
This is my test log
`
running coco-style evaluation on project coco, weights ./logs/coco/efficientdet-d0_9_430.pth...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "coco_eval.py", line 150, in <module>
    model.requires_grad_(False)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'EfficientDetBackbone' object has no attribute 'requires_grad_'

`

**Comment by zylo117** [comment]
either you changed the code or it's not the latest code.

**Comment by xiexu666** [comment]
> either you changed the code or it's not the latest code.

Thank for your quick reply. I have change my pytorch version to 1.4.0 ，everything is ok.
